Split basic configuration
cyfronet-fid/marketplace pull request #1622
Opened 2020-09-02 10:31 UTC by goreck888

2020-09-07 09:12 UTC, agpul commented
Can you provide me a short scenario of how this PR can be tested?

2020-09-08 09:26 UTC, agpul approved these changes

2020-11-12 13:29 UTC, JanKapala commented on app/controllers/pages_controller.rb
> +    ab_finished(:recommendations)
There is no ab_test funstion usage. Maybe should it be added?

2020-11-12 13:31 UTC, JanKapala commented on app/helpers/application_helper.rb
> +  end
There is no usage of this placeholder. did you mean to use it with ab_test?

2020-11-12 13:35 UTC, JanKapala requested changes
The ab_finished function is used but ab_test isn't so an experiment is not displayed in the Split Dashboard. Maybe should it be added to make example of usage A/B testing more end-to-end? @goreck888

2020-11-12 13:35 UTC, JanKapala commented on config/experiments.yml
> +      percent: 50
This experiment isn't displayed in the Split Dashboard

2020-11-12 13:35 UTC, JanKapala commented on app/helpers/application_helper.rb
> +  end
There is no usage of this placeholder. Did you mean to use it with ab_test?

2020-11-12 13:35 UTC, JanKapala commented on app/controllers/pages_controller.rb
> +    ab_finished(:recommendations)
There is no ab_test function usage. Maybe should it be added?

2020-11-12 15:04 UTC, goreck888 commented on config/experiments.yml
> +      percent: 50
Yes, I removed experiment used for tests in the last commit, just forget about remove it in config files.

2020-11-12 15:05 UTC, goreck888 commented on app/helpers/application_helper.rb
> +  end
I wanted to keep it for future implementations of tests but I can remove it.

2020-11-12 15:05 UTC, goreck888 commented on app/controllers/pages_controller.rb
> +    ab_finished(:recommendations)
I forgot about it

2020-11-12 17:15 UTC, wujuu approved these changes

2020-11-12 18:12 UTC, JanKapala approved these changes

2020-11-18 14:35 UTC, merged