Fix multimedia and use_cases_url fields and logo
cyfronet-fid/marketplace pull request #1626
Opened 2020-09-14 10:13 UTC by goreck888

If logo cannot be downloaded or is bad type,
then is not saved

2020-09-14 17:28 UTC, michal-szostak commented on app/services/service/pc_create_or_update.rb
> +      unless logo.blank? || logo_content_type == "text/html"
Are you sure that `logo_content_type == "text/html"` is good enough? Isn't it better to whitelist accepted types?
(there might be cases of `"application/json"` responses or others.

2020-09-14 17:28 UTC, michal-szostak commented on spec/factories/jms_service.rb
> +            "multimedia" => [
Who decided this latest API to have two nested `multimedia` keys?

2020-09-14 17:28 UTC, michal-szostak commented on app/jobs/jms/manage_message_job.rb
> +  queue_as :pc_subscriber
Why is the name of the job changed?

2020-09-15 09:05 UTC, agpul requested changes
1. Field use_cases, on the provider component side we have two different fields:
![image](https://user-images.githubusercontent.com/43000481/93189007-f5faa300-f741-11ea-93fe-c9af2d2b3229.png)
on the MP side, we treat is as a one link:
![image](https://user-images.githubusercontent.com/43000481/93189084-0e6abd80-f742-11ea-8745-0a68c051a6c2.png)
2. The same situation is if it comes to the Multimedia field
3.  Filed categories:
- provider component:
![image](https://user-images.githubusercontent.com/43000481/93189612-9fda2f80-f742-11ea-826e-748cd112e15a.png)
-MP:
empty one:
![image](https://user-images.githubusercontent.com/43000481/93189652-aec0e200-f742-11ea-8deb-cbd8a2b6d331.png)

4. Check mapping for scientific domains, I chose natural science on the provider component side, in Marketplace we map it as "Other"
5.  Target user:
Provider component: researcher
MP: empty
5. Language Availability (*)
Provider component: English
MP: empty
6. Helpdesk email and Security contact email
Provider component: these fields are filled
MP: empty

2020-09-15 15:14 UTC, goreck888 commented on spec/factories/jms_service.rb
> +            "multimedia" => [
This is eIC schema issue.

2020-09-15 15:16 UTC, goreck888 commented on app/jobs/jms/manage_message_job.rb
> +  queue_as :pc_subscriber
Because queue name should tell us what is for and not the tool we use.

2020-09-15 15:16 UTC, goreck888 commented on app/services/service/pc_create_or_update.rb
> +      unless logo.blank? || logo_content_type == "text/html"
Ok, I'll change it.

2020-09-25 09:37 UTC, agpul approved these changes

2020-09-25 13:17 UTC, martaswiatkowska approved these changes

2020-09-28 11:26 UTC, merged