[#1647] Change name of service to resource in front
cyfronet-fid/marketplace pull request #1648
Opened 2020-10-19 11:18 UTC by goreck888

Change all "services" strings to resources in frontend.

Backend changes will be included in separate PR.

2020-10-19 11:22 UTC, michal-szostak approved these changes
There's not really much code here, so there's nothing to point out. 
@agpul / @roksanaer could you check manually whether there might be some place where `Service` name is still used?

2020-10-19 12:28 UTC, agpul requested changes
1. I can't check the "resources" under leads, but I believe that they were changed @goreck888 
2.  Now the circle is too close to the word: resources - @abacz 
![image](https://user-images.githubusercontent.com/43000481/96449961-e0333e80-1215-11eb-926e-39d1c2e90836.png)
3. Now the button looks bad for me @abacz 
![image](https://user-images.githubusercontent.com/43000481/96450203-2e484200-1216-11eb-9ff5-0c0e2bb5c68c.png)
4.  In the project view @goreck888 
![image](https://user-images.githubusercontent.com/43000481/96450582-b0386b00-1216-11eb-9571-2f13feef4c7b.png)
5. Project form @goreck888 
![image](https://user-images.githubusercontent.com/43000481/96450672-cba37600-1216-11eb-9186-11c4eacc7029.png)
6. The view of a single project @goreck888 
![image](https://user-images.githubusercontent.com/43000481/96450762-ea097180-1216-11eb-996c-c46d6f1d9eba.png)
7. An empty project @goreck888 
![image](https://user-images.githubusercontent.com/43000481/96450827-00afc880-1217-11eb-9655-9be9f71989b5.png)
8. For open access services @goreck888 
![image](https://user-images.githubusercontent.com/43000481/96450903-1ae9a680-1217-11eb-9fd0-1216160a917f.png)
9. Final details of the order @goreck888 
![image](https://user-images.githubusercontent.com/43000481/96451061-51bfbc80-1217-11eb-8fb9-8f4bb36e6ebf.png)
10.  View of the single order @goreck888 
![image](https://user-images.githubusercontent.com/43000481/96451120-68feaa00-1217-11eb-9305-2d978f9056b5.png)

2020-10-20 10:05 UTC, agpul commented
In this comment, I will add places where the "services" word occurs:
1. Backoffice:
- [ ] ![image](https://user-images.githubusercontent.com/43000481/96571504-f26fb400-12cb-11eb-83b2-8b9c2caa601e.png)
- [ ] 
![image](https://user-images.githubusercontent.com/43000481/96571569-061b1a80-12cc-11eb-8820-ea458e9bfb4b.png)
- [ ] service form: 
![image](https://user-images.githubusercontent.com/43000481/96571657-277c0680-12cc-11eb-968b-1548d9027679.png)
![image](https://user-images.githubusercontent.com/43000481/96571696-32369b80-12cc-11eb-8826-02c6234a6c64.png)
![image](https://user-images.githubusercontent.com/43000481/96571736-424e7b00-12cc-11eb-8238-74732a27274d.png)
![image](https://user-images.githubusercontent.com/43000481/96571779-52fef100-12cc-11eb-8851-f00b6a6243db.png)

2. Executive panel
![image](https://user-images.githubusercontent.com/43000481/96571898-7b86eb00-12cc-11eb-8d2d-282bc4e3de0e.png)

2020-10-21 09:10 UTC, agpul approved these changes

2020-10-21 11:25 UTC, merged