Sort resource form in the backoffice
cyfronet-fid/marketplace pull request #1666
Opened 2020-10-29 12:37 UTC by goreck888

Sort resource form similar to the PC component

2020-10-30 10:43 UTC, abacz commented
What i will do ;)

- clickable block (toggle), not only name + some arrow (up/down)
- remove some gaps (e.g. mt-5 here -> 
![Screenshot 2020-10-30 at 11 24 01](https://user-images.githubusercontent.com/26226991/97694186-7ed75f00-1aa2-11eb-994b-f1026dd65d18.png))
- some inputs/selects have green tic which overlap inputs text. More padding from right or different input width (if possible)
- .is-disable in choices__list--multiple i would set bg-color to #c1c1c1 and color: #717070 (more or less;)) to look more "disable" ;) 
![Screenshot 2020-10-30 at 11 31 01](https://user-images.githubusercontent.com/26226991/97694821-69af0000-1aa3-11eb-8993-7b708287a5de.png)
- remove borders in contact section

2020-11-02 07:42 UTC, agpul requested changes
Moreover:
1. 
![image](https://user-images.githubusercontent.com/43000481/97841504-3d36f600-1ce6-11eb-83d4-4afee97b64a4.png)
2. 
![image](https://user-images.githubusercontent.com/43000481/97841745-bfbfb580-1ce6-11eb-8bca-0fa4eff220a3.png)

2020-11-02 18:34 UTC, goreck888 commented
> Moreover:
> 1.
> ![image](https://user-images.githubusercontent.com/43000481/97841504-3d36f600-1ce6-11eb-83d4-4afee97b64a4.png)
> 2.
> ![image](https://user-images.githubusercontent.com/43000481/97841745-bfbfb580-1ce6-11eb-8bca-0fa4eff220a3.png)

Everything should be now ok

2020-11-03 07:14 UTC, agpul approved these changes

2020-11-03 13:55 UTC, michal-szostak approved these changes

2020-11-03 14:53 UTC, merged