1669 improve readme
cyfronet-fid/marketplace pull request #1672
Opened 2020-11-05 09:33 UTC by JanKapala

2020-11-05 11:12 UTC, bwilk commented
looks like a nice progress

2020-11-05 12:17 UTC, michal-szostak requested changes

2020-11-05 12:17 UTC, michal-szostak commented on README.md
> +./bin/rake import:eic MP_IMPORT_EIC_URL=https://providers.eosc-portal.eu/
remove `MP_IMPORT_EIC_URL=https://providers.eosc-portal.eu/` that was a workaround to the workaround :D.
The default `beta` instance should be operational.

2020-11-05 12:17 UTC, michal-szostak commented on README.md
> +[Elasticsearch server](#elasticsearch) in the background.
You can add comment how to disable hooks during `commit` / `push` (run `git <command> --no-verify`

2020-11-05 12:22 UTC, JanKapala commented on README.md
> +./bin/rake import:eic MP_IMPORT_EIC_URL=https://providers.eosc-portal.eu/
ok xD. Is it operational now?

2020-11-05 13:31 UTC, michal-szostak commented on README.md
> +./bin/rake import:eic MP_IMPORT_EIC_URL=https://providers.eosc-portal.eu/
It should be

2020-11-05 13:31 UTC, michal-szostak approved these changes

2020-11-05 13:32 UTC, goreck888 approved these changes

2020-11-10 09:39 UTC, goreck888 commented
@JanKapala Could you merge this PR?

2020-11-10 12:02 UTC, merged