Add `remove array element` in forms
cyfronet-fid/marketplace pull request #1675
Opened 2020-11-09 17:45 UTC by goreck888

2020-11-10 09:47 UTC, agpul commented
Can I test this PR? How? Can you add a description?

2020-11-12 15:08 UTC, bwilk commented
@agpul this is about removing array items. Looks ugly but works. Maybe the frontend logic could be better if the empty fields weren't visualised except after intentionally using "Add new .... "

2020-11-12 16:56 UTC, agpul requested changes
For me, it works in a random way. Sometimes when I try to "Save" changes I need to remove one item a couple of times.

2020-11-12 16:57 UTC, wujuu commented on app/models/service.rb
> +    end
Can't we refactor this into a for loop?

2020-11-12 17:43 UTC, wujuu requested changes

2020-11-12 17:43 UTC, wujuu commented on app/views/backoffice/services/_form.html.haml
> +          "data-class" => "form-control text optional" } Add new related platform
Shouldn't we use I18n translations?

2020-11-12 17:48 UTC, wujuu commented
Also, shouldn't the behaviour to be to not show the 'Remove' button unless it's a second (and further) resource?
![image](https://user-images.githubusercontent.com/30239467/98976359-89204100-2517-11eb-9702-476c37e9c31a.png)

2020-11-12 18:25 UTC, JanKapala reviewed
Maybe some usage of locales would be nice

2020-11-13 14:56 UTC, goreck888 commented on app/models/service.rb
> +    end
Done

2020-11-13 15:05 UTC, goreck888 commented
> Also, shouldn't the behaviour to be to not show the 'Remove' button unless it's a second (and further) resource?
> ![image](https://user-images.githubusercontent.com/30239467/98976359-89204100-2517-11eb-9702-476c37e9c31a.png)

Honestly I think it's a bad idea. When service have eg. 3 entries and want to remove first then he couldn't do this. This solution is simple, working, and doesn't need unnecessary js code to handle this. And it fits to the logic in this form - look at PublicContacts, they're working in the same way.

2020-11-17 11:56 UTC, agpul requested changes
I still can remove only one element during one action.

2020-11-18 18:59 UTC, wujuu approved these changes

2020-11-20 05:05 UTC, goreck888 commented on app/views/backoffice/services/_form.html.haml
> +          "data-class" => "form-control text optional" } Add new related platform
Done.

2020-11-20 09:31 UTC, merged