950 improve front in backoffice
cyfronet-fid/marketplace pull request #1676
Opened 2020-11-10 07:15 UTC by jarekzet

a lot of modifications in all backoffice views - start page , list views, edit forms etc.

2020-11-12 10:11 UTC, abacz commented
Scenario:
Scientific Domains list -> edit eg. Clinical Medicine.
Clicking "cancel" didn't back me to previous page (list) but to scientific domain detail.

2020-11-12 11:14 UTC, jarekzet commented
Added mods of backlinks in edit forms.

2020-11-12 11:26 UTC, abacz approved these changes

2020-11-12 14:47 UTC, bwilk commented
Please take a look at the providers edit as well. It seems odd, but this may not be the case of the current changes, but older bug 
![Uploading Screenshot 2020-11-12 at 15.46.13.png…]()

2020-11-12 15:03 UTC, bwilk commented
> Please take a look at the providers edit as well. It seems odd, but this may not be the case of the current changes, but on older bug
> 
> <img alt="Screenshot 2020-11-12 at 15 48 36" width="1083" src="https://user-images.githubusercontent.com/2674939/98954875-8fee8a00-24fe-11eb-902e-2949501f0a27.png">

ok, this isn't really an issue. Looks about the same in production.

2020-11-12 15:04 UTC, bwilk approved these changes

2020-11-12 16:50 UTC, wujuu requested changes

2020-11-12 16:50 UTC, wujuu commented on app/views/backoffice/categories/show.html.haml
> +                data: { confirm: "Are you sure you want to remove this category" },
Shouldn't we use I18n translations? That goes for all of the explicit strings in this PR's view files.

2020-11-17 12:14 UTC, goreck888 commented on app/views/backoffice/categories/show.html.haml
> +                data: { confirm: "Are you sure you want to remove this category" },
Yeah but I think we will refactor that. Michał is looking for a gem making translations similar like in python or try to find other solution but now we don't have to change everything because we don't know the way we'll refactor things

2020-11-17 12:16 UTC, goreck888 approved these changes

2020-11-17 13:01 UTC, agpul approved these changes

2020-11-18 10:56 UTC, merged