Fix popular resources
cyfronet-fid/marketplace pull request #1686
Opened 2020-11-17 00:26 UTC by goreck888

Add unverified and published resources to popular resources query

2020-11-18 19:06 UTC, wujuu commented on app/controllers/home_controller.rb
> +      @services = Service.where(status: [:published, :unverified]).includes(:providers).popular(6)
Do we want to show unverified services on the front page?

2020-11-19 08:58 UTC, goreck888 commented on app/controllers/home_controller.rb
> +      @services = Service.where(status: [:published, :unverified]).includes(:providers).popular(6)
Yes, now `unverifed` status is used for show imported services, but it's functional in the same way like published.

2020-11-19 14:25 UTC, wujuu requested changes
The only thing I would maybe add is to shift the 'popular' logic to Serivce Model, to call it inside this controller like: service.top(n). Shouldn't the buissness logic like that be in the model instead of the controller?

2020-11-19 15:28 UTC, wujuu approved these changes

2020-11-19 16:19 UTC, agpul approved these changes

2020-11-19 17:05 UTC, merged