[#1682] Add services api tests
cyfronet-fid/marketplace pull request #1693
Opened 2020-11-20 09:03 UTC by goreck888

2020-11-20 11:34 UTC, agpul approved these changes

2020-11-20 12:53 UTC, wujuu requested changes

2020-11-20 12:53 UTC, wujuu commented on spec/requests/api/services_controller_spec.rb
> +      expect(body[0]["URL"]).to eq(published_service.webpage_url)
Maybe we should check if the body[0], contains only and exactly these keys ('Service Unique ID', 'SERVICE_TYPE', etc.). Same goes for body[1] I guess.

2020-11-20 12:53 UTC, wujuu commented on spec/requests/api/services_controller_spec.rb
> +
Should we add also recently introduced 'errored' service here? It shouldn't be visible in the GET request as well

2020-11-20 13:08 UTC, goreck888 commented on spec/requests/api/services_controller_spec.rb
> +
Yeah, and that's what I check, if errored services are not visible in the API

2020-12-08 16:32 UTC, wujuu approved these changes

2020-12-09 14:35 UTC, merged