1698 refactoring of translations
cyfronet-fid/marketplace pull request #1704
Opened 2020-11-24 10:14 UTC by JanKapala

closes #1698

2020-11-24 12:41 UTC, michal-szostak requested changes
I'm happy that it generally works. There are a few things to fix.

Also: 

1. When creating PR the convention is to name the PR as `[#<issue_id>] <Title>
2. In PR it's good to describe the scope, including screenshots is also a nice pracrice, if issue touches UI - it helps in finding feature in the application itself. In case of translations that last part is not required though.

2020-11-24 12:41 UTC, michal-szostak commented on app/controllers/application_controller.rb
> +      session[:locale] = I18n.locale = FastGettext.locale
We do not really support translations, so we should hard code `en_GB` here

2020-11-24 12:41 UTC, michal-szostak commented on locale/README.txt
> +# Folder `locale` is needed for fast_gettext gem and git doesn't commit empty directories that's why this file exist.
In these cases the standard procedure is to add empty file called `.gitkeep` or something like that

2020-11-24 12:52 UTC, JanKapala commented on app/controllers/application_controller.rb
> +      session[:locale] = I18n.locale = FastGettext.locale
en_GB or just en?

2020-11-24 12:52 UTC, JanKapala commented on locale/README.txt
> +# Folder `locale` is needed for fast_gettext gem and git doesn't commit empty directories that's why this file exist.
good to know! :)

2020-11-24 13:02 UTC, JanKapala commented on app/controllers/application_controller.rb
> +      session[:locale] = I18n.locale = FastGettext.locale
Ad 2; I could rewrite a description of issue closed by this PR as a description of this PR but I wonder if is it necessary

2020-11-30 09:57 UTC, agpul commented
Now, I haven't found any problems from my point of view. I will make a final review at the end of the implementation.

2020-11-30 15:10 UTC, wujuu commented on app/views/projects/_project_layout.html.haml
>                .details-box-info.text-uppercase= t("project_items.status.#{project.status}")
Translation missing

2020-11-30 15:10 UTC, wujuu commented on app/views/projects/edit.html.haml
> +-# TODO: refactor dynamic translation
There already is a dynamic tranlastion here?

2020-11-30 15:10 UTC, wujuu commented on app/views/projects/index.html.haml
> +    -# TODO: missing translation (no entry in original i18 locales)
Reminder

2020-11-30 15:10 UTC, wujuu commented on app/views/projects/services/_details.html.haml
>    %dt= t("project_items.service.label.#{map_view_to_order_type(project_item)}")
Dynamic translations missing

2020-11-30 15:10 UTC, wujuu commented on app/views/projects/services/_layout.html.haml
>            = link_to t("common.#{map_view_to_order_type(project_item)}.link"), webpage(project_item),
Translation missing

2020-11-30 15:10 UTC, wujuu commented on app/views/projects/services/_project_item.html.haml
>        = t("project_items.status.#{project_item.status}")
Translation missing

2020-11-30 16:15 UTC, JanKapala commented on Gemfile
> -gem "split", require: "split/dashboard"
Look at line 70

2020-11-30 16:17 UTC, JanKapala commented on app/views/designsystem/index.html.haml
>  - content_for :title, t(".title")
The translation is missing as you can see in the comment ;) Also designsystem directory is probably to remove - out of the scope of this PR

2020-11-30 16:18 UTC, JanKapala commented on app/views/executive/statistics/index.html.haml
> +    -# TODO: refactor dynamic translation (above)
this is obsolete TODO  comment, alreade refactored

2020-11-30 16:19 UTC, JanKapala commented on app/views/home/communities/_card.html.haml
>  .title= t(".#{key}.title")
this is dynamic translation or rather using translation to do something else than translations: maping constant to strings - so it's out of the PR scope

2020-11-30 16:20 UTC, JanKapala commented on app/views/projects/edit.html.haml
> +-# TODO: refactor dynamic translation
It's obsolete TODO comment as well

2020-11-30 16:22 UTC, JanKapala commented on app/views/projects/index.html.haml
> +    -# TODO: missing translation (no entry in original i18 locales)
Yeah, for now we keep missing translations as they are. Same as before

2020-11-30 16:24 UTC, JanKapala commented on app/views/projects/services/_details.html.haml
>    %dt= t("project_items.service.label.#{map_view_to_order_type(project_item)}")
As before: dynamic translations should be marked only, no refactoring in this PR

2020-11-30 16:24 UTC, JanKapala commented on app/views/projects/services/_layout.html.haml
>            = link_to t("common.#{map_view_to_order_type(project_item)}.link"), webpage(project_item),
As before: dynamic translations should be marked only, no refactoring in this PR

2020-11-30 16:24 UTC, JanKapala commented on app/views/projects/services/_project_item.html.haml
>        = t("project_items.status.#{project_item.status}")
As before: dynamic translations should be marked only, no refactoring in this PR

2020-11-30 19:01 UTC, wujuu commented on app/views/executive/statistics/index.html.haml
> +    -# TODO: refactor dynamic translation (above)
So can't we delete this comment?

2020-11-30 19:02 UTC, wujuu commented on app/views/projects/edit.html.haml
> +-# TODO: refactor dynamic translation
Well then it shouldn't be here

2020-11-30 19:07 UTC, wujuu commented on config/initializers/fast_gettext.rb
> +FastGettext.default_text_domain = "marketplace"
No newline

2020-11-30 19:07 UTC, wujuu commented on lib/templates/haml/scaffold/_form.html.haml
> +-#     = f.button :submit
We don't need simple form ????

2020-11-30 19:20 UTC, JanKapala commented on lib/templates/haml/scaffold/_form.html.haml
> +-#     = f.button :submit
I don't know, maybe, but it is in plain erb - not haml - and it was the cause of gettext parser failure :/

2020-12-01 12:58 UTC, agpul requested changes
Please check all places one more time, I've tried to catch all problems but I think that we need a double check.
1. The text on the main page is in polish (should be in english)
![image](https://user-images.githubusercontent.com/43000481/100742946-e2271a80-33db-11eb-98fa-f5baecd561db.png)
2. Title? and More HTML?
![image](https://user-images.githubusercontent.com/43000481/100743075-0e429b80-33dc-11eb-8329-58455b25ac4c.png)

3.  Project page doesn't work! - I am not able to check pages related to the project concept. 
![image](https://user-images.githubusercontent.com/43000481/100743279-65487080-33dc-11eb-9560-c669404df358.png)
https://marketplace-2.docker-fid.grid.cyf-kr.edu.pl/projects
4. Browse service page:
![image](https://user-images.githubusercontent.com/43000481/100743397-8741f300-33dc-11eb-9981-30d4dfba1cd6.png)
5. When the mouse is on the link I see something strange:
![image](https://user-images.githubusercontent.com/43000481/100743580-c4a68080-33dc-11eb-8a1f-9d350c800090.png)
6. Wrong  button name:
![image](https://user-images.githubusercontent.com/43000481/100743863-32eb4300-33dd-11eb-804d-e8e4268ff182.png)

2020-12-02 08:03 UTC, JanKapala commented
@agpul I couldn't reproduce these errors locally, problems doesn't occur apart from polish description at home - I've fix it.
Maybe have you used wrong testing instance?

2020-12-02 12:04 UTC, agpul approved these changes

2020-12-02 12:58 UTC, michal-szostak approved these changes

2020-12-04 15:35 UTC, michal-szostak approved these changes

2020-12-09 10:20 UTC, wujuu approved these changes

2020-12-09 14:10 UTC, merged