Add details helper and refactor details view
cyfronet-fid/marketplace pull request #1706
Opened 2020-11-26 12:26 UTC by wujuu

2020-11-30 10:05 UTC, agpul approved these changes
From my point of view, for current changes, everything looks fine. If something changes in the future (for eg. after Michał review), I will make a second review.

2020-12-01 17:58 UTC, JanKapala requested changes

2020-12-01 17:58 UTC, JanKapala commented on app/helpers/service/details_helper.rb
> +  end
Why not just arrays rather than column function?

2020-12-01 17:58 UTC, JanKapala commented on app/views/services/_details.html.haml
> +                    *group[:fields])) || (group[:clazz] && service.send(group[:clazz]).present?)
This logic looks a bit complicated for the view, maybe should it be moved to the helper?

2020-12-01 17:59 UTC, JanKapala commented
In the browser pages look good

2020-12-02 13:57 UTC, wujuu commented on app/helpers/service/details_helper.rb
> +  end
I guess we can refactor that - the name of the method gives away that the method is actually returning columns

2020-12-02 14:49 UTC, JanKapala approved these changes

2020-12-09 18:45 UTC, merged