1702 use view component for things related to order type
cyfronet-fid/marketplace pull request #1710
Opened 2020-12-02 23:51 UTC by goreck888

Change order type with tooltip rendering to inline view component.
Change displaying order information step to view component.

Now tests are missing so PR is a draft

2020-12-04 08:41 UTC, agpul requested changes
I am not sure if it is a scope of this issue but you can fix it here:
1. For open access, fully open access, and other types of services I can see "Link" instead of button name
![image](https://user-images.githubusercontent.com/43000481/101141535-b642a980-3614-11eb-898f-3ce84f1f1311.png)

The rest works fine for me.

2020-12-07 07:31 UTC, agpul approved these changes

2020-12-07 14:04 UTC, wujuu requested changes

2020-12-08 04:23 UTC, goreck888 commented on app/components/services/inline_order_url_component.rb
> +class Services::InlineOrderUrlComponent < ApplicationComponent
My bad. Resolved.

2020-12-08 04:24 UTC, goreck888 commented on app/components/services/inline_order_url_component.rb
> +      "Order externally"
I'll do that after your merge.

2020-12-08 16:34 UTC, wujuu approved these changes

2020-12-10 15:41 UTC, merged