Experimental token implementation
cyfronet-fid/marketplace pull request #1719
Opened 2020-12-11 15:28 UTC by wujuu

2020-12-17 08:16 UTC, agpul reviewed
![image](https://user-images.githubusercontent.com/43000481/102461292-77ffae00-4048-11eb-8857-9622b7f31ec0.png)
I recommend removing this statement - this is not true, esspecially for unlogged users.

2020-12-18 11:44 UTC, goreck888 commented on app/models/user.rb
> +    authentication_token != "revoked" && (not authentication_token.nil?)
Maybe change (not authentication_token.nil?) to authentication_token.present?

2020-12-18 11:58 UTC, goreck888 requested changes
See my comment about yaml config file and add changelog entry.

2020-12-18 11:58 UTC, goreck888 commented on swagger/v1/swagger.yaml
> +- url: http://{defaultHost}
Use anchor, because {defaultHost} returns just a string and not variable. In this case eg.
url: http://*defaultHost

l45: default: &defaultHost localhost:5000

2020-12-18 13:16 UTC, wujuu commented on app/models/user.rb
> +    authentication_token != "revoked" && (not authentication_token.nil?)
Done

2020-12-18 13:19 UTC, wujuu commented on swagger/v1/swagger.yaml
> +- url: http://{defaultHost}
Actually, this is how it's suposed to be - this file is generated by rswag. The idea is to introduce variables for the end user to choose from (variable - {defaultHost}, is visible to the user, and then he can interpolate it with whatever he wants (or values provided by us)). You could see this behviour in /api-docs, but actually not anymore, because I deleted the variable and added 3 different servers (localhost, production, master)

2021-02-01 15:58 UTC, michal-szostak requested changes

2021-02-01 15:58 UTC, michal-szostak commented on app/controllers/api/v1/services/offers_controller.rb
> +      render json: { msg: "Offer #{@offer.iid} created successfully." }
generally REST message for CREATE (POST) should return `201` and created object.
REST api should avoid returning messages. If it's successful and no content is to be returned just return `200` or `204`

2021-02-01 15:58 UTC, michal-szostak commented on app/controllers/api/v1/services/offers_controller.rb
> +      render json: { msg: "Offer updated successfully." }
Same as with POST - an object should be returned

2021-02-01 15:58 UTC, michal-szostak commented on config/routes.rb
> +  unless ENV['OFFERS_API_DISABLED'] == 'true'
I would advice to put this into application configuration. There you can compare it with string, but in the application itself it would be much better if this flag was a boolean.
Also we should refrain from using ENV[...] directly in the application code.
(it's harder to mock in tests, etc)

2021-02-01 19:13 UTC, michal-szostak approved these changes

2021-02-01 19:13 UTC, michal-szostak commented on app/controllers/api/v1/services/offers_controller.rb
> +      render json: @offer, status: 201
update should not return status `201 created`

2021-02-01 19:26 UTC, michal-szostak approved these changes

2021-02-02 06:13 UTC, bwilk approved these changes

2021-02-02 07:59 UTC, merged