[#1493] Create personalized search results
cyfronet-fid/marketplace pull request #1720
Opened 2020-12-15 08:56 UTC by JanKapala

closes #1493 

- [x] Create a dedicated "Recommended results" section on the search result page.
- [x] The current implementation (for all users) should be based on the most popular resources from the most popular category.
- [x] Some users should see view according to Mockup1 and others according to Mockup2
- [x] Use our split configuration to configure the experiment for each implementation
- [ ] Fine-tune css
- [ ] Finish tests

2020-12-17 09:06 UTC, agpul commented
![image](https://user-images.githubusercontent.com/43000481/102461292-77ffae00-4048-11eb-8857-9622b7f31ec0.png)
I recommend removing this statement - this is not true, especially for unlogged users.

2020-12-17 15:31 UTC, JanKapala commented
"Based on your search" statement removed

2020-12-18 08:34 UTC, agpul approved these changes

2020-12-21 09:13 UTC, goreck888 requested changes
Just one thing to fix, everything else is fine from my point of view.

2020-12-21 09:13 UTC, goreck888 commented on app/services/recommender/simple_recommender.rb
> +    def get_records(n)
Avoid using "get" word in method names.

2020-12-21 09:28 UTC, goreck888 commented
Moreover 
./spec/features/categories_spec.rb:62
 ./spec/features/service_spec.rb:162
are failing because recommendations are services and Rspec sees it as additional services.
Just turn off split experiment in tests or include recommendations in these.

2020-12-21 18:05 UTC, goreck888 approved these changes

2020-12-22 08:13 UTC, wujuu approved these changes

2020-12-22 09:30 UTC, merged