[#1711] Fix filtering by country
cyfronet-fid/marketplace pull request #1721
Opened 2020-12-17 15:37 UTC by kmarszalek

- change to use geographical_availabilities
- fix filter
Closes #1711 .

2020-12-30 10:47 UTC, wujuu requested changes

2020-12-30 10:47 UTC, wujuu commented on spec/controllers/concerns/searchable_spec.rb
> +      let!(:service1) { create(:service).tap { |s| s.geographical_availabilities = Array.wrap(Country.load(collection.first)); s.save } }
You can throw the `gegraphical_availabilities` into the `create` , like 
`create(:service, geographical_availabilities: Array...)`

2020-12-30 11:11 UTC, wujuu reviewed
Also found a really small bug. How to recreate:
Create a *draft* service with a country that hasn't been used before.
This country now appears in the filters drop down menu(bug?), and if chosen returns 'no results' (this part is actually correct of course).

2020-12-30 14:34 UTC, kmarszalek commented on spec/controllers/concerns/searchable_spec.rb
> +      let!(:service1) { create(:service).tap { |s| s.geographical_availabilities = Array.wrap(Country.load(collection.first)); s.save } }
good eye :)
done.

2020-12-31 12:26 UTC, wujuu reviewed
Unfortunately I found another bug regarding the draft service:
In the regular service listing the filter works as intended (doesn't show country used in a draft service).
In the backoffice owned resources (services) listing it also doesn't show the country used in a draft service, even though it should (owner of the service should have the abilitiy to filter by conutry on draft services as well)

2021-01-04 09:11 UTC, wujuu approved these changes

2021-01-05 17:53 UTC, goreck888 requested changes

2021-01-05 17:53 UTC, goreck888 commented on app/models/filter/location.rb
> +      [{ name: "Any", id: "" }] + Service.where(status: :published).pluck(:geographical_availabilities).flatten.uniq.map { |s| { name: s, id: s } }
I suppose it should be status: [:published, :unverified] :)

2021-01-05 17:54 UTC, goreck888 commented
Check my comment, moreover it's ok and I'll approve this PR

2021-01-07 10:41 UTC, goreck888 approved these changes

2021-01-07 10:49 UTC, merged