1726 remove recommendations from services list at backoffice
cyfronet-fid/marketplace pull request #1728
Opened 2020-12-30 17:53 UTC by JanKapala

This PR closes #1726  issue that include turning off recommendations in the backoffice.

### What has changed?
* **Old behaviour**
Recommendations are visible in services catalog and in `Owned resources` view at backoffice.
* **New behaviour**
Now recommendations are displayed only in services catalog - not in backoffice `Owned resources` view.

### How to manually test (for reviewers):
On master go to `Admin` -> `AB experiments`, choose version `v1` or `v2` and click `Force for current user` button.
Next go to both `/services` and `/backoffice/services`. You should see recommendations on services lists in both cases.

On this branch go to `Admin` -> `AB experiments`, choose version `v1` or `v2` and click `Force for current user` button.
Next go to both `/services` and `/backoffice/services`. You should see recommendations on services lists only in the first case

2020-12-31 12:52 UTC, wujuu approved these changes

2020-12-31 13:31 UTC, wujuu commented
Everything looks OK, but:
> PS.: **How to turn on recommendations**: go to `Admin` -> `AB experiments`, choose version `v1` or `v2` and click `Force for current user` button.
 
I would just change the name of the experiments to 'reccomendations_v1', because it's not clear in the AB panel which experiment we are talking about

2021-01-04 10:56 UTC, JanKapala commented
I would rather keep versions' names short, simple and pretty - they're used in code and it's cleaner this way. The name of the experiment is visible in the left top corner of the split dashboard (`AB experiments`) below `Begin typing to filter`, so it's not necessary to repeat it in versions' names.

2021-01-04 13:04 UTC, kmarszalek approved these changes
it works :)

2021-01-07 15:39 UTC, michal-szostak commented
Commits do not include issue id

2021-01-08 15:31 UTC, JanKapala commented
> Commits do not include issue id

Done ;)

2021-01-25 16:04 UTC, wujuu approved these changes

2021-01-25 16:04 UTC, wujuu requested changes
Add changes to changelog

2021-01-26 03:51 UTC, michal-szostak commented
I have one question - Some code has been modified, but no tests needed updating?

2021-01-26 13:42 UTC, bwilk commented
PO review needed @roksanaer @bwilk

2021-01-26 13:43 UTC, bwilk approved these changes

2021-02-04 15:49 UTC, merged