[#1716] Add more fields to the comparison view
cyfronet-fid/marketplace pull request #1739
Opened 2021-01-08 12:10 UTC by kmarszalek

- added more fields
- using https://docs.cyfronet.pl/display/FID/RDT+%28ERV%29+Resource+Profile as a reference point for fields labels after slack conversation with @bwilk 
Closes #1716

2021-01-08 14:07 UTC, goreck888 approved these changes

2021-01-08 14:07 UTC, goreck888 commented on app/views/comparisons/show.html.haml
> +            = service.trl.map { |trl| trl.name.upcase }.join(", ")
Add condition - if service.trl.present especially you call first element of an array

2021-01-08 15:59 UTC, bwilk approved these changes

2021-01-08 16:08 UTC, bwilk commented
Minor issues:
1. Correct wording (from the Resource Profile) should be - Geographical Availability, Language Availability

General issues noticed, but out of scope of this development action:

1. Field order is somehow random. The page should reflect the order in the Resource Profile
2. Categorization and Domains don't represent the hierarchical structure 
   -  Scientific Domain -> Scientific Subdomain
   -  Category -> Subcategory   
3. Resource Access Type, Resource Order Type, Resource Access mode - there is at least 1 not needed. We need to verify which one is legacy and which are represented in the Resource Profile 3.0

If possible to squeeze it in the current sprint please fix this. If not we need to reflect that in the following sprint.

2021-01-08 16:09 UTC, JanKapala approved these changes

2021-01-08 16:12 UTC, bwilk requested changes
Please see the comment above for summary

2021-01-08 16:12 UTC, bwilk commented on app/views/comparisons/show.html.haml
> +          = _("Languages Availability")
see the summary comment

2021-01-08 16:12 UTC, bwilk commented on app/views/comparisons/show.html.haml
> -          = _("Geographical availabilities")
wait - this was ok I think. Please see Resource profile.

2021-01-11 08:38 UTC, kmarszalek commented
Corrected:
1. Minor issue ->  Geographical Availability, Language Availability
2. General issues noticed -> field order

2021-01-11 14:34 UTC, roksanaer requested changes
PR is OK

2021-01-11 14:36 UTC, bwilk approved these changes

2021-01-11 14:37 UTC, roksanaer approved these changes

2021-01-11 14:38 UTC, merged