[#1713] create admins for providers
cyfronet-fid/marketplace pull request #1750
Opened 2021-01-13 13:39 UTC by goreck888

- [ ] Add data_administrator model to provider
- [ ] Add data_administrator section from service view (link: /services/:id/data_administrator/)
- [ ] Add pundit policies (email of data administrator of resource provider must match with current_user email)
- [ ] Add views details and css mods (@JanKapala  @jarekzet)
- [ ] Add tests

2021-01-15 14:47 UTC, roksanaer commented
plaese change:
In this site you can manage your resource offers. Scroll down to section where you can find it.
Below view also show how your resource will look in Catalogue & Marketplace.
->
This is the place where you can manage your resource offers. Please, scroll down to navigate to "Parameters and offers" section, to specify your resource offers along with their ordering parameters.
Please note, this site also reflects how your resource and its offers will be presented to the users in the EOSC Catalogue & Marketplace.

2021-01-16 00:19 UTC, michal-szostak requested changes

2021-01-16 00:19 UTC, michal-szostak commented on app/helpers/service/header_helper.rb
> +      "https://providers.eosc-portal.eu/resource-dashboard/#{service.pid.split(".").first}/#{service.pid}/stats"
This URL musn't be hardcoded here - this should be configurable by env variables / config (in yaml)

2021-01-16 00:19 UTC, michal-szostak commented on app/views/services/data_administrators/_default_parameters.html.haml
> +        - if offer.name == "Offer" && offer.description == "#{offer.service.name} Offer"
Is this the only way we can distinguish default offer?

2021-01-18 16:40 UTC, goreck888 commented on app/views/services/data_administrators/_default_parameters.html.haml
> +        - if offer.name == "Offer" && offer.description == "#{offer.service.name} Offer"
For now yes, we can improve this with default_offer bool in offer model in separate PR.

2021-01-20 11:12 UTC, michal-szostak approved these changes

2021-01-20 17:07 UTC, bwilk commented
Two issues to start with:
Styles:
![image](https://user-images.githubusercontent.com/2674939/105209593-4f3c6e00-5b4a-11eb-83b7-4b27e2683609.png)

Navigation is wrong here:
![image](https://user-images.githubusercontent.com/2674939/105209622-55cae580-5b4a-11eb-8b42-d6e921dce072.png)

2021-01-25 15:58 UTC, wujuu requested changes

2021-01-25 15:58 UTC, wujuu commented on app/controllers/services/ordering_configuration/offers_controller.rb
> +    end
Having worked on Offer API I've noticed that in the db Offfer.parameters is defaulted to [] so this method isn't necessary

2021-01-25 15:58 UTC, wujuu commented on app/policies/ordering_configuration_policy.rb
> +    #   user&.service_owner? ||
I guess we don't need this commented code

2021-01-25 15:59 UTC, wujuu commented
I also noticed that the the button 'add aditional administrator' overlaps a little bit with the next header
![image](https://user-images.githubusercontent.com/30239467/105730473-b1241b80-5f2e-11eb-9abf-d66f7ea30327.png)

2021-01-26 09:09 UTC, goreck888 commented on app/policies/ordering_configuration_policy.rb
> +    #   user&.service_owner? ||
Ok

2021-01-26 09:10 UTC, goreck888 commented on app/controllers/services/ordering_configuration/offers_controller.rb
> +    end
It is necesssary, because without this method if we remove all parameters they're not updated to empty array and it was fixed with this.

2021-01-26 10:24 UTC, wujuu approved these changes

2021-01-27 07:06 UTC, abacz commented
Some visual requests:
1. Offer should have yellow border in opposite to grey Add new offer and Edit parameters in default offer.
2. If user add second offer, default offer should have a blue notice like on preview.
3. Offers should have same height in a row, if description is longer then 4 lines truncate it and add "expand to read more".
4. Need gauge icon before "Technical parameters" header in offer. 

5.  Active about tab doesn't have white background.
![Screenshot 2021-01-27 at 07 54 11](https://user-images.githubusercontent.com/26226991/105955095-061e7980-6076-11eb-8e3e-37002a166067.png)

6. Content in special boxes like "Add new offer" and "Edit parameters" need to be aligned to icon center.
![Screenshot 2021-01-27 at 07 57 01](https://user-images.githubusercontent.com/26226991/105955219-37974500-6076-11eb-9ea7-d6494b24bc5b.png)

7. Provider name need to be aligned to label
![Screenshot 2021-01-27 at 07 56 33](https://user-images.githubusercontent.com/26226991/105955279-53025000-6076-11eb-960b-1a78d96ede07.png)

8. "Hr" should be lighter - equivalent of #f7f7f7 
![Screenshot 2021-01-27 at 07 58 05](https://user-images.githubusercontent.com/26226991/105955430-8fce4700-6076-11eb-8c5e-f8b28b60384b.png)

2021-01-28 17:42 UTC, jarekzet commented
> 2. If user add second offer, default offer should have a blue notice like on preview.

This information is displayed when you add offer in special way: Tiitle should be "Offer" and description "{service_name} Offer"

2021-01-29 16:11 UTC, bwilk approved these changes

2021-01-29 16:29 UTC, merged