[#1711] Fix filtering by country
cyfronet-fid/marketplace pull request #1751
Opened 2021-01-15 11:42 UTC by kmarszalek

- include countries from region

2021-01-15 11:57 UTC, goreck888 approved these changes

2021-01-15 13:40 UTC, goreck888 approved these changes

2021-01-18 14:31 UTC, roksanaer requested changes
the logic works well. there are only 2 minor issues:
- please change the tooltip text to: "Resource available in the territory of the entire selected region"
- please change the header of the filter from "provider location" to "Resource availability"

2021-01-18 14:43 UTC, roksanaer approved these changes

2021-01-18 14:44 UTC, merged