[#1758] Db reccomender serializer
cyfronet-fid/marketplace pull request #1778
Opened 2021-02-01 18:40 UTC by wujuu

Closes #1758

2021-02-13 09:32 UTC, JanKapala requested changes
Description of `rake recommender:serialize_db` can be added to readme

2021-02-13 09:32 UTC, JanKapala commented on lib/tasks/recommender.rake
> +    puts serialized_db.to_json
We can do `rake recommender:serialize_db > some/file.json` now but I think that this task could directly save to the file.

2021-02-18 09:22 UTC, kmarszalek commented on spec/serializers/recommender/user_serializer_spec_spec.rb
> +    s1 = create(:service)
change to full names

2021-02-18 09:40 UTC, michal-szostak approved these changes

2021-02-18 09:51 UTC, JanKapala approved these changes

2021-02-18 10:43 UTC, kmarszalek approved these changes

2021-02-18 11:27 UTC, merged