[#1768] Providers view
cyfronet-fid/marketplace pull request #1794
Opened 2021-02-05 15:36 UTC by kmarszalek

- view
- breadcrumb
- router
- link from list

Closes #1768

2021-02-11 09:02 UTC, roksanaer commented
i did some initial tests. please remember that links from here:
![image](https://user-images.githubusercontent.com/38095945/107617460-4114d580-6c50-11eb-9fea-044a862daec4.png)

also should point at the provider's page :)

2021-02-15 07:54 UTC, kmarszalek commented
> i did some initial tests. please remember that links from here:
> 
> also should point at the provider's page :)

done :)

2021-02-16 11:53 UTC, kmarszalek commented
![Zrzut ekranu 2021-02-16 o 12 50 06](https://user-images.githubusercontent.com/6060538/108059404-bec45100-7055-11eb-8d04-b3e5401c7e7a.png)

@roksanaer 
On Providers view ->
- Contact section in sidebar is working but needs some polishing
- no last added services
- details -> Paweł

2021-02-18 15:15 UTC, roksanaer requested changes
Fixes required before release:
1. change: recent added services -> recently added resources
2. Change: Ask a question about this provider? -> Ask this provider a question
3. On details page change "Esfri" -> "ESFRI"
4. According to the preview:
![image](https://user-images.githubusercontent.com/38095945/108377844-b8280c00-7204-11eb-97ee-f4e0636919ed.png)
Adress is one bullet point. at the moment each verse is a bullet point. Because we put address and contact separately, leave one bullet point from the address tile:
![image](https://user-images.githubusercontent.com/38095945/108378018-ec033180-7204-11eb-9646-209ee10a19dc.png)


4. In multimedia tile, replace URLs with generic "multimedia 1", "multimedia2" ... links:
![image](https://user-images.githubusercontent.com/38095945/108376587-6df25b00-7203-11eb-91f4-40727f2b8ce4.png)
![image](https://user-images.githubusercontent.com/38095945/108378507-59af5d80-7205-11eb-815b-3fc58283056b.png)

similar to resource multimedia tile:
![image](https://user-images.githubusercontent.com/38095945/108376672-819dc180-7203-11eb-9fac-232c1202c2c5.png)
5. Some of the logos are visualised inproperly:
![image](https://user-images.githubusercontent.com/38095945/108376851-b3168d00-7203-11eb-912e-0efdba7756a2.png)
affected providers:
- 100trustit
- BlueBRIDGE
- CESNET
- CWL
- CESSDA ERIC
- CY-Biobank
- many more


Known issues:
1. United Kingdom is not displayed on the map: in both resource and provider PP. It is suggested to release this feature with this known bug and fix it right away along with #1799 
it's painful especially for the Elixir UK, who has empty map because of that fact:
(someone is messing with the PR, cannot take the screenshot because of that :P :D)
2. Some providers have inserted corrupted data, it lowers the value of the product on our side. Notify the onboarding team, ask them to verify such records.
AUTHENIX:
![image](https://user-images.githubusercontent.com/38095945/108377540-7008e980-7204-11eb-87cf-0c74a40dfe01.png)

2021-02-18 15:50 UTC, kmarszalek commented
fixed 1,2,3 and 5-multimedia, 
@goreck888 -> 4 and 5-logo.
+changelog
+schema check

2021-02-19 10:00 UTC, roksanaer commented
Almost all is OK.
the multimedia tile element lacks link visibility. it appears as a polain text:
![image](https://user-images.githubusercontent.com/38095945/108489327-bb250a00-72a1-11eb-9a5e-50475765bf6e.png)

2021-02-19 10:36 UTC, roksanaer commented
Known issues:
1. United Kingdom is not displayed on the map: in both resource and provider PP. It is suggested to release this feature with this known bug and fix it right away along with #1799 
it's painful especially for the Elixir UK, who has empty map because of that fact:
(someone is messing with the PR, cannot take the screenshot because of that :P :D)
2. Some providers have inserted corrupted data, it lowers the value of the product on our side. Notify the onboarding team, ask them to verify such records.
AUTHENIX:
![image](https://user-images.githubusercontent.com/38095945/108377540-7008e980-7204-11eb-87cf-0c74a40dfe01.png)
3. Tiles under recently added resources include the link to the provider. maybe we should have a dedicated resource tile for this view, without this element, another instead? @abacz 
![image](https://user-images.githubusercontent.com/38095945/108379692-77c98d80-7206-11eb-9416-0cd5cdd46475.png)

2021-02-19 11:18 UTC, roksanaer approved these changes

2021-02-19 12:51 UTC, goreck888 approved these changes

2021-02-19 12:51 UTC, merged

2021-02-19 13:56 UTC, wujuu reviewed
Generally it's ok, but there is a lot of duplicated code in the views (provider views <-> service views). It's understandable since these views are awfully similar, but we could generalize them if it wouldn't be too confusing (maybe ViewComponent can help)? But that's for another issue. 

Also if you run `rake dev:prime`, the new provider fields aren't seeded, but that's also for another issue

2021-02-19 13:56 UTC, wujuu commented on app/views/backoffice/services/_form.html.haml
> +            label_method: :first, value_method: :second
I guess the indents here were fine

2021-02-19 13:56 UTC, wujuu commented on app/views/providers/_details.html.haml
> +                              with_desc: group[:with_desc] || false
This is very similar to services/_details view(same as providers/_about to services/_about, as well as header), but I don't think we should make these generic since it would be confusing. Maybe it can be done neatly with ViewComponent?

2021-02-19 13:56 UTC, wujuu commented on app/views/providers/details/_classification.html.haml
> +-# here should be icons variables for classification below
Add a TODO flag to not forget later

2021-02-19 13:56 UTC, wujuu commented on app/views/providers/sidebar/_map.html.haml
> +                                          "data-geographical_availabilities": map_data,
misaligned args

2021-02-19 13:56 UTC, wujuu commented on config/locales/views/home/en.yml
> +    providers:
Didn't we switch to gettext a while back? Unless this is necessary (since there are some TODO: fix dynamic translation comments here and there)

2021-02-19 13:56 UTC, wujuu commented on spec/services/importers/provider_spec.rb
> +    expect(imported_hash[:synchronized_at]).to eq(correct_hash[:synchronized_at])
it would be cool if we could compare these like `expect(imported_hash).to eq(correct_hash), but if it can be done it can be as is