1800 details view countries order
cyfronet-fid/marketplace pull request #1820
Opened 2021-02-26 08:53 UTC by kmarszalek

Closes #1800

2021-02-26 11:45 UTC, goreck888 requested changes

2021-02-26 11:45 UTC, goreck888 commented on app/views/services/details/_array.html.haml
> +            #{element}#{idx == (Array(get_only_countries(service.send(field))).map.size) - 1 ? nil : ", "}
Very nice, but You can do it simple with `.join(", ")` method instead of mapping and adding indices :)

2021-02-26 12:09 UTC, goreck888 approved these changes

2021-02-26 13:25 UTC, bwilk approved these changes

2021-02-26 13:43 UTC, goreck888 approved these changes

2021-03-01 05:40 UTC, kmarszalek commented
![Zrzut ekranu 2021-03-1 o 06 39 54](https://user-images.githubusercontent.com/6060538/109456357-f28d7680-7a58-11eb-85ef-097e8baa476a.png)
 @roksanaer

2021-03-01 05:40 UTC, merged