[#1826] Include `resource_organisation` in provider's filter
cyfronet-fid/marketplace pull request #1844
Opened 2021-03-04 18:04 UTC by goreck888

Filtering by providers includes `resource_organisation`
and `providers` associations

Fixes #1826

2021-03-08 11:09 UTC, kmarszalek commented on spec/controllers/concerns/searchable_spec.rb
> -  let!(:service1) { create(:service, name: "duper super name", providers: providers,
add to context "filter type tests" section tests filtering by provider and resource organisation

2021-03-08 11:09 UTC, kmarszalek commented on db/schema.rb
> -ActiveRecord::Schema.define(version: 2021_02_26_164811) do
necessary?

2021-03-08 11:10 UTC, kmarszalek requested changes
it works on PR instance.

2021-03-16 10:11 UTC, wujuu approved these changes

2021-03-16 10:16 UTC, kmarszalek approved these changes

2021-03-16 10:31 UTC, merged