[#1827] Extend catalog services search
cyfronet-fid/marketplace pull request #1856
Opened 2021-03-15 12:09 UTC by danielkryska

- Services can be found by provider or resource organisation

2021-03-15 12:29 UTC, kmarszalek requested changes
Change Service -> Resource in commit msg and then in changelog entry
also:
- add some tests
- missing entry in the chaangelog

2021-03-24 05:39 UTC, kmarszalek commented on CHANGELOG.md
> +- Extend finding resource in main searchbar including providers (@danielkryska, goreck888)
should only add to search or also highlight RO/RP on the returned list?

2021-03-24 06:23 UTC, Marcelinna approved these changes

2021-03-24 14:07 UTC, kmarszalek commented on app/models/service/search.rb
> +      highlight: [:name, :tagline, :resource_organisation_name, :providers, :provider_names]
.

2021-03-24 17:10 UTC, kmarszalek approved these changes
i don't like providers and some aspects but fundamentally it is ok and it works. :|

2021-03-25 11:20 UTC, michal-szostak approved these changes

2021-03-25 11:29 UTC, merged