[#1859] Fix externally ordered resources
cyfronet-fid/marketplace pull request #1861
Opened 2021-03-16 07:50 UTC by goreck888

Fix conditions for external ordering type
Fix query in executive panel
Add hidden `internal` field to the Offer's form
Fixes #1859

2021-03-16 10:24 UTC, kmarszalek commented on db/schema.rb
> -ActiveRecord::Schema.define(version: 2021_02_26_164811) do
:)

2021-03-16 10:57 UTC, wujuu approved these changes

2021-03-16 13:58 UTC, michal-szostak approved these changes

2021-03-16 16:35 UTC, bwilk commented
@goreck888 please change the button "Order externally" to "Go to the order website"
 
This:
![image](https://user-images.githubusercontent.com/2674939/111345184-529d3300-867d-11eb-9d2d-33a5dbd9704c.png)

Should look that way:
![image](https://user-images.githubusercontent.com/2674939/111345739-d7884c80-867d-11eb-9f24-fceea9b1afd7.png)

2021-03-16 16:39 UTC, bwilk approved these changes

2021-03-16 16:51 UTC, Marcelinna commented
I checked how many resource can be ordered via EOSC Marketplace from (Order required and other) 75 services. I counted 12, so it is posiible that Marketplace ordering 54 is correct number?
![image](https://user-images.githubusercontent.com/59872096/111347655-b45e9c80-867f-11eb-9fb8-dfb58e067840.png)

2021-03-16 16:58 UTC, Marcelinna requested changes
.

2021-03-17 16:01 UTC, Marcelinna approved these changes

2021-03-17 16:34 UTC, roksanaer approved these changes

2021-03-17 16:50 UTC, merged