[#1858] Send additional filters context data to recommender
cyfronet-fid/marketplace pull request #1862
Opened 2021-03-16 08:31 UTC by danielkryska

- Extend resource availability filter with regions
- Extend tree structure like filters to send also child nodes

2021-03-16 12:35 UTC, wujuu requested changes

2021-03-16 12:35 UTC, wujuu commented on app/controllers/concerns/service/recommendable.rb
> +    scientific_domains: -> ids { ids + ids.map { |id| ScientificDomain.descendants_of(id).map(&:id) }.flatten }
I think you can replace `map(&:id)` with `pluck(:id`). It may be more efficient or use `descendant_ids` method

2021-03-16 12:35 UTC, wujuu commented on app/models/scientific_domain.rb
> +  def self.descendants_of(id)
You can just use `descendant_ids` method from ancestry. https://github.com/stefankroes/ancestry#tree-navigation. I think there is no need to rewrite this method

2021-03-16 12:35 UTC, wujuu commented on app/controllers/concerns/service/recommendable.rb
> +    scientific_domains: -> ids { ids + ids.map { |id| ScientificDomain.descendants_of(id).map(&:id) }.flatten }
You can just use `descendant_ids` method from ancestry. https://github.com/stefankroes/ancestry#tree-navigation. Like `ScientificDomain.find(id).descendant_ids

2021-03-16 12:35 UTC, wujuu commented on app/controllers/concerns/service/recommendable.rb
> +    scientific_domains: -> ids { ids + ids.map { |id| ScientificDomain.descendants_of(id).map(&:id) }.flatten }
Example  format of the scientific_domains is ['3', 9, 18, 29, 36, 40, 42, 52, 64, 65, 66, 67, 68] - Every item should be an `int`

2021-03-16 12:35 UTC, wujuu commented on app/controllers/concerns/service/recommendable.rb
> +          filters[key] = value
`category_id` filter is a string, it should be an int as before

2021-03-16 14:43 UTC, wujuu approved these changes

2021-03-16 14:47 UTC, goreck888 submitted a review, later dismissed

2021-03-16 14:47 UTC, goreck888 commented on app/controllers/concerns/service/recommendable.rb
> +          is_empty_value = value.nil? || value == "" || value == []
You can use just value.blank?

2021-03-17 08:23 UTC, goreck888 approved these changes

2021-03-17 10:32 UTC, danielkryska commented
Will be contiuned in PR #1866

2021-03-17 10:32 UTC, closed without merging