[HOTFIX] Fix set upstream for providers
cyfronet-fid/marketplace pull request #1954
Opened 2021-04-01 12:55 UTC by goreck888

Fixes REST and JMS importers should set upstream for providers
exactly like it is in the services

2021-04-06 07:08 UTC, kmarszalek commented on db/schema.rb
> +  create_table "user_services", force: :cascade do |t|
?

2021-04-06 07:09 UTC, kmarszalek requested changes
faulty migration

2021-04-06 08:15 UTC, goreck888 commented on db/schema.rb
> +  create_table "user_services", force: :cascade do |t|
Done.

2021-04-13 08:01 UTC, Marcelinna approved these changes

2021-04-13 12:48 UTC, kmarszalek approved these changes

2021-04-13 13:37 UTC, merged