[#1836] Fix img at /backoffice/providers/<id>
cyfronet-fid/marketplace pull request #2053
Opened 2021-05-07 11:15 UTC by danielkryska

Before
![image](https://user-images.githubusercontent.com/31220811/117441821-3cea1280-af36-11eb-86fb-11e821f91b92.png)

After
![image](https://user-images.githubusercontent.com/31220811/117441763-2a6fd900-af36-11eb-9d49-4680509ec905.png)

2021-05-07 13:05 UTC, kmarszalek approved these changes
Some changelog entry?

2021-05-10 08:40 UTC, jswk requested changes
The PR does somewhat address the issue, but uses a workaround, which probably introduces regression (no resizing and default logo).

The actual fix should correct the way image variants are produced, and handle transparency correctly, not ditch the mechanism.

2021-05-10 08:40 UTC, jswk commented on app/views/backoffice/providers/show.html.haml
> +      = image_tag @provider.logo, class: "align-self-center mr-4 float-left img-responsive"
If the provider_logo isn't necessary then you should also remove it, there are no other usages of it.
Also, for some reason it was resized before, why is it not necessary anymore? Describe the motivation in commit message.

2021-05-10 08:40 UTC, jswk commented on app/controllers/users/auth_mock_controller.rb
> +      @user.roles = params[:roles].blank? ? [] : params[:roles].map(&:to_sym)
Create a separate PR for this, or at least put it in a separate commit, as it totally unreleated to the main problem.

2021-05-10 08:40 UTC, jswk commented on CHANGELOG.md
> +- Fix img at /backoffice/providers/<id> - now colors of image aren't reversed (@danielkryska)
This isn't descriptive for the end-user and is repetitive ("Fixed", "Fix"). It is also incorrect, there was no color reversal there.
I'd rather describe it like this: "Improve transparency handling in provider logo".

2021-05-11 10:58 UTC, jswk requested changes
First of all, this fix isn't as much as a db migration (db migrations mostly deal with schema changes) but data migration unrelated to schema and as such has strong coupling to implementation, which is undesirable for migrations.
Therefore, it has to be moved to a Rake task. As it relates to import, I'd suggest putting it in `import.rake` under key `reimport_logos_with_no_extension`.

Since it should be run after new version's deploy then the necessary task should be described in `docs/upgrade` too.

2021-05-11 10:58 UTC, jswk commented on db/migrate/20210510114948_migrate_providers_images.rb
> +    has_non_ext = attachment.filename.to_s.split(".")[1].blank?
If I understand correctly, the intention is to find cases where `filename="foo."` or `filename="foo.bar."`, but not  `filename="foo"`. Then the line should read something like this to be correct:
```ruby
dot_splitted = attachment.filename.to_s.split(".")
has_blank_extension = dot_splitted.size > 1 && dot_splitted[-1].blank?
```

2021-05-11 11:51 UTC, jswk commented
Another insight, this time from @wojt and I didn't notice.
Don't introduce another envvar just to set the default_url_options. When changing the code placement to task, pass it as a task argument from cmd. The task call then looks as follows: `rails some:task[arg_value,another_arg_value]` (i.e. the args are comma seprated). To define such task (example, beware) with arguments email and role:
```ruby
  task :add_role_to_user, [:email, :role] => :environment do |_, args|
    TestBootstrap::AddRoleToUser.new(args.email, args.role).call
  end
```

Also, when exiting the service call method, in the finally block, restore the initial value of the default_url_options, just to be on the safe side if something throws exception.

2021-05-12 10:06 UTC, jswk reviewed
Mark it ready for review when you take into account things from the call

2021-05-12 10:28 UTC, jswk approved these changes

2021-05-12 11:02 UTC, merged