Improve consistency between MP provider and PC provider
cyfronet-fid/marketplace pull request #2078
Opened 2021-05-17 08:39 UTC by danielkryska

- Provider
  - Basic
    - Abbreviation should be required
    - Website should be required
    - Legal entities should be required
    - Legal statuses should be a select field
  - Marketing
    - Description should be required
    - Logo should be required
  - Classification
    - Scientific domain should be always chosen with subcategory
    - tags should be unique items list instead of input
      - Uniquness of values error
  - Location
    - street should be required
    - postal code should be required
    - city should be required
    - country should be required
  - Maturity
    - Provider life cycle statuses should be select
    - Certifications should be unique items list instead of input
  - Other
    - Merril scientific domains should be always chosen with subcategory

2021-05-24 10:54 UTC, jswk commented on app/javascript/app/controllers/form_controller.js
> +    "relatedPlatforms", "affiliations", "national_roadmaps", "fixme", "tag_list"]
Why add an unused stimulus target? I would rather remove it alongside its definition in `app/views/backoffice/providers/form/_classification.html.haml`. If you're at it you could also see, if there aren't some more unused targets here and purge them if needed as well.

2021-05-24 11:01 UTC, jswk commented on app/policies/backoffice/provider_policy.rb
> +      :description, [multimedia: []], :logo,
I wouldn't change the attributes order if not necessary. Here you switch logo and multimedia with each other.

2021-05-24 11:15 UTC, jswk commented on app/views/backoffice/providers/form/_contact.html.haml
> +        "main_contact.phone".to_sym, "public_contacts.phone".to_sym])) }
Don't you have to put here a list of all the fields that can be present in a section?
You're still missing for example `main_contact.positions`, `public_contacts.first_name`, etc.

2021-05-24 11:17 UTC, jswk commented on app/views/backoffice/providers/form/_other.html.haml
> +        - msd = msd.select {  |_, sd| !sd.parent.blank? }.map { |name, sd| [name, sd.id] }
I would rather keep the value constant, maybe the first assignment could be named `msd_child_names`?

2021-05-24 11:20 UTC, jswk commented on config/application.rb
> +    config.pc_export_token = ENV["PC_EXPORT_TOKEN"]
These should be stashed for now, as you're not doing export in this PR yet.
Also, for the future, there is a compilation of used envvars in README.md that should be updated with these two, when they ship.

2021-05-24 11:27 UTC, danielkryska commented on app/javascript/app/controllers/form_controller.js
> +    "relatedPlatforms", "affiliations", "national_roadmaps", "fixme", "tag_list"]
path: app/views/backoffice/providers/_form.html.haml

```
html: { "data-controller" => "form", "data-target": "form.form",
  "data-disabled": provider.upstream_id.present? }
```

Pointing to JS form-controller.js file. Each array type field that is contained in mentioned path form should be required in it.

2021-05-24 11:27 UTC, jswk commented on db/migrate/20210521054139_improve_consistency_of_provider_between_services.rb
> +class ImproveConsistencyOfProviderBetweenServices < ActiveRecord::Migration[6.0]
You could only define the `def change` method, as we don't do rollbacks in production anyway (only restore from backup if need arises).

2021-05-24 11:28 UTC, danielkryska commented on app/javascript/app/controllers/form_controller.js
> +    "relatedPlatforms", "affiliations", "national_roadmaps", "fixme", "tag_list"]
The JS controller supports the duplication of inputs and submit buttons for array field types.

2021-05-24 11:29 UTC, jswk commented on db/migrate/20210521054139_improve_consistency_of_provider_between_services.rb
> +    )
I would add a few words of comment, as to what this and the following updates do.
I understand, that they set the `sd_id` or `vocab_id` to a sensible value, but it's not apparent from the sql itself.

2021-05-24 11:29 UTC, danielkryska commented on app/policies/backoffice/provider_policy.rb
> +      :description, [multimedia: []], :logo,
Is it crucial in any way? Will the change provide any consequences?

2021-05-24 11:31 UTC, jswk commented on lib/tasks/dev.rake
> +      Importers::Logo.new(provider, "https://picsum.photos/200/300").call
Didn't know that service. I hope they don't block us :D

2021-05-24 11:32 UTC, danielkryska commented on app/views/backoffice/providers/form/_contact.html.haml
> +        "main_contact.phone".to_sym, "public_contacts.phone".to_sym])) }
The field `public_contacts.first_name` isn't validated, so it'll be always skipped. This same with `main_contact.positions`.

2021-05-24 11:33 UTC, jswk commented on lib/tasks/dev.rake
> +      provider = Provider.where(name: hash["name"]).first_or_initialize
`provider = Provider.find_or_initialize_by(name: hash["name"])`?

2021-05-24 11:34 UTC, danielkryska commented on app/views/backoffice/providers/form/_other.html.haml
> +        - msd = msd.select {  |_, sd| !sd.parent.blank? }.map { |name, sd| [name, sd.id] }
Such usage is dictated with consistency between other HAML files.

2021-05-24 11:36 UTC, jswk commented on app/policies/backoffice/provider_policy.rb
> +      :description, [multimedia: []], :logo,
No, but now you're in the blame in case someone wonders why it is this way. :D

2021-05-24 11:43 UTC, jswk commented on app/javascript/app/controllers/form_controller.js
> +    "relatedPlatforms", "affiliations", "national_roadmaps", "fixme", "tag_list"]
```
html: { "data-controller" => "form", "data-target": "form.form",
  "data-disabled": provider.upstream_id.present? }
```
This only defines the `form` target, not the `tag_list`. The `tag_list` is unused, unless there's a dynamic invocation somewhere in `form_controller.js`, but I haven't found any.

Anyway, that's a noop fortunately. So whatever.

2021-05-24 11:46 UTC, jswk commented on app/views/backoffice/providers/form/_contact.html.haml
> +        "main_contact.phone".to_sym, "public_contacts.phone".to_sym])) }
That's a valid point. I didn't consider it's tied to validation.
In that case it's unnecessary to list `main_contact.phone` and `public_contacts.phone` there, as they aren't validated.

2021-05-24 11:46 UTC, jswk commented on app/views/backoffice/providers/form/_contact.html.haml
> +        "main_contact.phone".to_sym, "public_contacts.phone".to_sym])) }
But that's a noop then, so whatever.

2021-05-24 11:47 UTC, jswk commented on app/views/backoffice/providers/form/_other.html.haml
> +        - msd = msd.select {  |_, sd| !sd.parent.blank? }.map { |name, sd| [name, sd.id] }
Which other haml files?

2021-05-24 11:56 UTC, danielkryska commented on app/views/backoffice/providers/form/_other.html.haml
> +        - msd = msd.select {  |_, sd| !sd.parent.blank? }.map { |name, sd| [name, sd.id] }
`collection: Vocabulary.where(type: "Vocabulary::LegalStatus")`
`collection: Country.options.map { |c| [ c.name, "value" => c.alpha2 ] }`
`collection: Vocabulary.where(type: "Vocabulary::ProviderLifeCycleStatus")`
...

Try to search with regex: /collection: [a-zA-Z]+\./ trough files. In this case I've used separate variable in HAML due too problems with line breaking.

2021-05-24 11:57 UTC, danielkryska commented on app/views/backoffice/providers/form/_other.html.haml
> +        - msd = msd.select {  |_, sd| !sd.parent.blank? }.map { |name, sd| [name, sd.id] }
Another regex could be: /- [a-zA-z_]+ = /

2021-05-24 11:59 UTC, jswk commented on app/views/backoffice/providers/form/_other.html.haml
> +        - msd = msd.select {  |_, sd| !sd.parent.blank? }.map { |name, sd| [name, sd.id] }
Okay, but show me one case where a mutable variable is used.

2021-05-24 12:00 UTC, danielkryska commented on db/migrate/20210521054139_improve_consistency_of_provider_between_services.rb
> +class ImproveConsistencyOfProviderBetweenServices < ActiveRecord::Migration[6.0]
I wasn't aware how we make releases. I'll keep it in mind for future releases. Algough `down` method doesn't break anything we can keep it as it is.

2021-05-24 12:01 UTC, jswk commented on app/views/backoffice/providers/form/_other.html.haml
> +        - msd = msd.select {  |_, sd| !sd.parent.blank? }.map { |name, sd| [name, sd.id] }
This regex `- ([a-zA-z_]+) = .+\n.+- \1 = ` only shows one result, the lines you added here.

2021-05-24 12:03 UTC, danielkryska commented on app/javascript/app/controllers/form_controller.js
> +    "relatedPlatforms", "affiliations", "national_roadmaps", "fixme", "tag_list"]
The `tag_list` field inself points to controller target in here

```
= f.input :tag_list, multiple: true, input_html: { class: "form-control" },
              wrapper_html: { "data-target" => "form.tag_list" },
              as: :array, disabled: cant_edit([tag_list: []])

2021-05-24 12:33 UTC, danielkryska commented on db/migrate/20210521054139_improve_consistency_of_provider_between_services.rb
> +    )
Done

2021-06-01 10:41 UTC, Marcelinna commented
In provider Component field Legal status is active only after selecting the checkbox Legal Entity (*) .
Should it work the same for MP?
![image](https://user-images.githubusercontent.com/59872096/120310460-b4f9ed00-c2d6-11eb-86d1-ba3ccc37c8df.png)

2021-06-01 11:46 UTC, Marcelinna commented
After make mistake in form, problem with "Contact" exist
Step to reproduce.
1. Click button "Add new provider"
2. Clikc button "Create provider" - don't fill fields
3. Click on the "Contact"
4. See error, field aren't displayed correctly
After mistake
![image](https://user-images.githubusercontent.com/59872096/120318068-abc14e00-c2df-11eb-8d0b-503ba8f927da.png)
Before mistake
![image](https://user-images.githubusercontent.com/59872096/120318151-ce536700-c2df-11eb-957c-c07344e0271f.png)

2021-06-01 11:52 UTC, Marcelinna commented
why fileds in Contact and Admins arent required, as it is in PC

2021-06-01 11:59 UTC, Marcelinna commented
Please give information why you automatically fill field 
![image](https://user-images.githubusercontent.com/59872096/120319662-8c2b2500-c2e1-11eb-9cb3-aa9b28f7b8f7.png)

2021-06-02 11:19 UTC, danielkryska commented
> In provider Component field Legal status is active only after selecting the checkbox Legal Entity (*) .

Done partially. Without checked `Legal Entity` `Legal status` is hidden, but there is an error that will be continued in other PR.

The error occurring when the checkbox has been set to true it keep the value true even when unchecked.

2021-06-02 13:49 UTC, Marcelinna commented
Provider BlueBRIDGE,
beta: 
![image](https://user-images.githubusercontent.com/59872096/120491666-b7814300-c3b9-11eb-839d-7c986859720b.png)

PR **before update in PC:**
![image](https://user-images.githubusercontent.com/59872096/120491754-c831b900-c3b9-11eb-9620-78a634a33bcd.png)

PR: **after update in PC (click on button Submit):**
![image](https://user-images.githubusercontent.com/59872096/120492069-0d55eb00-c3ba-11eb-8be4-e128b48b426a.png)

it is problem with migration?

2021-06-02 13:58 UTC, Marcelinna commented
provider:  ELIXIR Belgium 

beta:
![image](https://user-images.githubusercontent.com/59872096/120493219-0e3b4c80-c3bb-11eb-90cb-e2ef684f2658.png)

PR before update provider in PC:
![image](https://user-images.githubusercontent.com/59872096/120493253-15faf100-c3bb-11eb-9d39-80dcee1a7158.png)

PR after update provider in PC:
![image](https://user-images.githubusercontent.com/59872096/120493390-35921980-c3bb-11eb-8017-af47f8337cd0.png)

PC: 
![image](https://user-images.githubusercontent.com/59872096/120493296-214e1c80-c3bb-11eb-90ad-bb9f93b49723.png)

problem with migration?

2021-06-04 07:45 UTC, Marcelinna commented
in PR for the country field there is an option to choose "non-European". When user select country "Other" in PC this match "non-European" in MP. Whether this will work when exporting data from MP? 
In documnetation I see "Other" and I dont see "non-European" https://confluence.egi.eu/display/EOSCEN/EOSC+Provider+Profile+v3.00. 

Maybe it would be better if we also had OTHER, "non-European" does not have to equal "Other"

2021-06-04 09:14 UTC, Marcelinna commented
> > In provider Component field Legal status is active only after selecting the checkbox Legal Entity (*) .
> 
> Done partially. Without checked `Legal Entity` `Legal status` is hidden, but there is an error that will be continued in other PR.
> 
> The error occurring when the checkbox has been set to true it keep the value true even when unchecked.

I don't think it can stay that way:
Provider AUTHENTIX

PC:
![image](https://user-images.githubusercontent.com/59872096/120777768-ee746780-c525-11eb-9cdf-d527ab1aebff.png)
BETA:
![image](https://user-images.githubusercontent.com/59872096/120777821-fcc28380-c525-11eb-8013-017e74376c7f.png)
PR:
![image](https://user-images.githubusercontent.com/59872096/120777851-064beb80-c526-11eb-8fa2-5af293c32727.png)

2021-06-04 11:10 UTC, Marcelinna commented
QA:
Provider: Committee for the Accessibility of Publications in Sciences and Humanities
PC:
![image](https://user-images.githubusercontent.com/59872096/120792380-baa13e00-c535-11eb-85ef-b4363bd38871.png)

PR, Beta:
![image](https://user-images.githubusercontent.com/59872096/120792404-c5f46980-c535-11eb-8600-96d123e85208.png)

PR, Beta after click button Submit in PC:
![image](https://user-images.githubusercontent.com/59872096/120792482-e4f2fb80-c535-11eb-8e89-3b4b312888f2.png)

data import does not cause the "Participating Country" field to be filled in MP if it is filled in with Other In PC. It is fill when I make submit on Provider in PC manulally

2021-06-07 12:28 UTC, danielkryska commented
> In provider Component field Legal status is active only after selecting the checkbox Legal Entity (*) .
Done.

2021-06-08 06:13 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

some providers are not displaying correctly, I think it is related to the logo

PR:
![image](https://user-images.githubusercontent.com/59872096/121132400-5e8a3280-c831-11eb-9369-e457b8b613f2.png)

other PR:
![image](https://user-images.githubusercontent.com/59872096/121132439-6a75f480-c831-11eb-968d-e8d99bd9037e.png)

2021-06-08 07:26 UTC, Marcelinna commented
despite unchecking the Legal entity box is still checked
Steps to reproduce:
1. Create new provider, I checked field Legal entity and chose Legal status
2. Edit provider and uncheck field Legal entity, click on button "Update"
3. Edit provider - see error field Legal entity is checked and Legal status is choosed

2021-06-08 07:56 UTC, Marcelinna commented
Problem with Public contact field
Steps to reproduce:
1. Create new provider - fill all required fields
2. Edit provider - delete public contact, try to click button "Update provider" - it isnt possible 
User see:
![image](https://user-images.githubusercontent.com/59872096/121145497-4f11e600-c83f-11eb-8295-abce6f284682.png)
3. Try click button "Update provider" - filed Public Contant is filled (because uppdate from step 2 has not been execute)
4. See bug - save provider isnt possible (despite filed Public Contact is filled), I have to add second Public contact
![image](https://user-images.githubusercontent.com/59872096/121145951-c21b5c80-c83f-11eb-828c-b5e1f2ec027e.png)
5. Click button "Update Provider" - one Public contant is visible
6.

2021-06-08 13:14 UTC, Marcelinna commented on app/javascript/app/controllers/form_controller.js
> +    console.log(child);
delete console.log()

2021-06-09 13:01 UTC, Marcelinna commented
1. Click button "Create new Provider"
2. Don't fill fields, click on button "Create Provider"
eInfraCentral External ID * looks required
![image](https://user-images.githubusercontent.com/59872096/121358530-fde31e80-c932-11eb-9a57-279286a559bb.png)
3. Fill all required field without eInfraCentral External ID * 
4. Click on button "Create Provider" - eInfraCentral External ID *  isnt required, why have red notification?

2021-06-10 11:45 UTC, jswk requested changes
The PR seems ok, besides its size. ;)

Nevertheless, there are several things I have noticed, that could be improved.

I also wonder about the ignored tests, why is it that they fail in case when they are run in a batch?

2021-06-10 11:45 UTC, jswk commented on config/application.rb
> +    Thread.abort_on_exception = true
This is a significant change for the exception handling in threads for the entire application, see e.g. comments for https://stackoverflow.com/a/9095369/1778478.
Why specifically is it needed? Which workers does it prevent from crashing? Maybe you could set this flag on specific threads, so that it wouldn't influence other places?

2021-06-10 11:45 UTC, jswk commented on db/data.yml
> +          F/QoQaP0xpAdCAQItxGBRvwIEWn8M6YFQ4H/g4U11p2PhtgAAAABJRU5ErkJggg==
That's a single blob, which is used in all the providers, isn't it?
Define it as a reference in yaml and reference it throughout the entries.

To define the reference on the first provider (EGI Federation):
```yaml
        image_base_64: &provider_default_logo |
          data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAB4CAYAAABb59j9AAAABGdBTUEAALGPC
```
and use it as such:
```yaml
        image_base_64: *provider_default_logo
```

2021-06-10 11:47 UTC, jswk commented
Also, this PR should have changelog.

2021-06-11 07:28 UTC, danielkryska commented on app/controllers/backoffice/providers_controller.rb
> +          "isn't valid or media doesn't exists, please check URLs: #{invalid_multimedia.join(", ")}"
done

2021-06-11 07:32 UTC, danielkryska commented on app/policies/backoffice/provider_policy.rb
> +      [scientific_domain_ids: []], [tag_list: []], [tags: []],
done

2021-06-11 07:33 UTC, danielkryska commented on app/services/importers/provider.rb
> +      country: Country.for(@data.dig("location", "country")).alpha2,
done

2021-06-11 07:36 UTC, danielkryska commented on app/controllers/backoffice/providers_controller.rb
> +      if @provider.data_administrators.map { |admin| admin.marked_for_destruction? }.all?
done

2021-06-11 08:58 UTC, jswk commented on app/controllers/backoffice/providers_controller.rb
> +          "aren't valid or media don't exists, please check URLs: #{invalid_multimedia.join(", ")}"
`media don't exists` => `media don't exist`

2021-06-11 09:13 UTC, danielkryska commented on db/data.yml
> +          F/QoQaP0xpAdCAQItxGBRvwIEWn8M6YFQ4H/g4U11p2PhtgAAAABJRU5ErkJggg==
done

2021-06-11 09:41 UTC, danielkryska commented on config/application.rb
> +    Thread.abort_on_exception = true
The flag has been set up to prevent crashing workers on thread error. The most common errored place is Image Magic conversion to PNG.

2021-06-11 09:41 UTC, danielkryska commented on config/application.rb
> +    Thread.abort_on_exception = true
done

2021-06-11 11:06 UTC, Marcelinna commented
Please add message, use http://, https://
![image](https://user-images.githubusercontent.com/59872096/121677082-b46f0c80-cab5-11eb-8317-15b633a78d2c.png)

2021-06-11 11:22 UTC, Marcelinna commented
- [ ] DEV
- [ ] QA

there is a problem with checking the uniqueness of name and abbrevation

1. Create new provider
![image](https://user-images.githubusercontent.com/59872096/121677847-bab1b880-cab6-11eb-8bab-7a06661fb3c2.png)
2. Create second provider with the same name and abbrevation as in step one - only Abbrevation is checked
![image](https://user-images.githubusercontent.com/59872096/121678103-0f553380-cab7-11eb-9d84-2f88dfcaa679.png)
3. I change Abbrevation and save
![image](https://user-images.githubusercontent.com/59872096/121678244-3dd30e80-cab7-11eb-8364-2d5eed5b96a7.png)
I have two provider with the same name in MP
![image](https://user-images.githubusercontent.com/59872096/121678405-6ce98000-cab7-11eb-8c85-79659bd5119c.png)
4. Create third provider with the same Name, but write other Abbrevation, it isnt possible to create Provider - name is taken
![image](https://user-images.githubusercontent.com/59872096/121678641-b5a13900-cab7-11eb-8f5f-22fc9fe0bbdd.png)
5. Try to create fourth Provider, with the same abbrevation but other name, abrevation is taken
![image](https://user-images.githubusercontent.com/59872096/121678862-01ec7900-cab8-11eb-8710-a50699a3a14e.png)

2021-06-14 06:09 UTC, danielkryska commented
> there is a problem with checking the uniqueness of name and abbrevation (when name and abbrevation is taken, only one field is checked)

Please make double-check. I can not replicate issue.

![Uploading localhost_5000_backoffice_providers_test.png…]()

2021-06-14 07:32 UTC, kmarszalek approved these changes

2021-06-14 07:46 UTC, jswk commented on app/views/backoffice/providers/form/_basic.html.haml
> +    = f.input :website, disabled: cant_edit(:website), hint: _("use http:// or https://")
Regarding the hints we have a dedicated place to put them, i.e. `config/locales/simple_form.en.yml`.
And there is a generic hint for urls there too, which should be used.

You should add the texts there by adding the provider group, as shown below:
```yaml
    hints:
      [...]
      provider:
        website: |
          Url should start with http or https [e.g. https://example.com]
        multimedia: |
          Urls should start with http or https [e.g. https://example.com]
```

Same goes for multimedia field.

2021-06-14 07:46 UTC, jswk commented on app/views/backoffice/providers/form/_marketing.html.haml
> +              hint: _("use http:// or https://")
See https://github.com/cyfronet-fid/marketplace/pull/2078/files#r650716455.

2021-06-14 09:00 UTC, danielkryska commented on app/views/backoffice/providers/form/_basic.html.haml
> +    = f.input :website, disabled: cant_edit(:website), hint: _("use http:// or https://")
done

2021-06-14 09:00 UTC, danielkryska commented on app/views/backoffice/providers/form/_marketing.html.haml
> +              hint: _("use http:// or https://")
done

2021-06-14 09:13 UTC, jswk commented on config/locales/simple_form.en.yml
> +          Url should start with http:// or https:// prefix [e.g. https://example.com]
It's good to have the full prefix, with `://` included, but please make it consistent throughout the file.
I.e., change all the other url hints text to equal: `Url should start with http:// or https:// prefix [e.g. https://example.com]`.

2021-06-14 09:18 UTC, danielkryska commented on config/locales/simple_form.en.yml
> +          Url should start with http:// or https:// prefix [e.g. https://example.com]
done

2021-06-14 11:45 UTC, Marcelinna commented
> > there is a problem with checking the uniqueness of name and abbrevation (when name and abbrevation is taken, only one field is checked)
> 
> Please make double-check. I can not replicate issue.
> 
> On update
> ![localhost_5000_backoffice_providers_test](https://user-images.githubusercontent.com/31220811/121846800-e1a30100-cce7-11eb-9fe4-16ef3957b3e6.png)
> 
> On create
> ![localhost_5000_backoffice_providers](https://user-images.githubusercontent.com/31220811/121847097-55450e00-cce8-11eb-9bef-94485ffea180.png)

When you put empty sign before name or abbrevation or after, form does not throw an error

2021-06-14 12:11 UTC, danielkryska commented
Because all in-scope issues have been fixed. The current changes will be merged. Other issues will be continued in #2160 and #2161.

2021-06-14 12:11 UTC, merged