[#2118] Vocabularies management in the marketplace
cyfronet-fid/marketplace pull request #2150
Opened 2021-06-08 13:13 UTC by goreck888

Add management panel in the backoffice for vocabularies

Closes #2118

2021-06-08 14:29 UTC, jswk commented
If it's blocking current release than it could be merged (if tests pass and so on), but it must be refactored in the upcoming sprint, taking the above into consideration.

2021-06-08 14:36 UTC, goreck888 commented
> Do we really want to introduce so much repetition with this?
> Each vocabulary type has the same controller and views associated with it, which could be parametrized.
> The routes could include a set of routes `[...]/vocabularies/:vocabulary_type[...]` and you would then have a single controller (with views and policy), which would handle such requests. It could have a static mapping between the `:vocabulary_type` path-param and concrete type. If you represented the type in snake_case then you could generate labels by using appropriate string transformations.
> 
> Is there a reason why it's so duplicated? Maybe each vocabulary will have distinct policy?, or some other editing rules? I may have missed this and it makes sense to keep it this way.

Not all vocabularies are included in `Vocabulary` scope, some are historically implemented as just a non-namespaced class. That's the reason I did it this way.

2021-06-08 15:13 UTC, jswk approved these changes
The issues raised above https://github.com/cyfronet-fid/marketplace/pull/2150#pullrequestreview-678592411 should be addressed in the upcoming sprint, but for now it could be left as is, if @Marcelinna approves that it functions ok.

2021-06-09 07:12 UTC, Marcelinna commented
Why Eid sometimes is required, sometimes no?
![image](https://user-images.githubusercontent.com/59872096/121309604-a927af80-c902-11eb-8cfb-357de8c626a6.png)
![image](https://user-images.githubusercontent.com/59872096/121309663-bcd31600-c902-11eb-992c-44fda434f1db.png)

2021-06-09 07:18 UTC, Marcelinna commented
I am on Funding Bodies but see button Add new Target user
![image](https://user-images.githubusercontent.com/59872096/121310376-995c9b00-c903-11eb-8133-2432f55d6927.png)

2021-06-09 07:20 UTC, Marcelinna commented
For me the text should wrap earlier, now it isnt looks good
![image](https://user-images.githubusercontent.com/59872096/121310536-c0b36800-c903-11eb-8e2a-5e795299566f.png)

2021-06-09 07:30 UTC, Marcelinna commented
When I click on one of the Access Mode, I see error
![image](https://user-images.githubusercontent.com/59872096/121312029-4552b600-c905-11eb-8a23-ca7a50736fb4.png)

2021-06-09 07:48 UTC, goreck888 commented
> Why Eid sometimes is required, sometimes no?
> ![image](https://user-images.githubusercontent.com/59872096/121309604-a927af80-c902-11eb-8cfb-357de8c626a6.png)
> ![image](https://user-images.githubusercontent.com/59872096/121309663-bcd31600-c902-11eb-992c-44fda434f1db.png)

It's ok, eid is not required only in Target User, because it is a model not included in vocabularies, similar like ScientificDomain or Category.

2021-06-09 07:55 UTC, goreck888 commented
> Why Eid sometimes is required, sometimes no?
> ![image](https://user-images.githubusercontent.com/59872096/121309604-a927af80-c902-11eb-8cfb-357de8c626a6.png)
> ![image](https://user-images.githubusercontent.com/59872096/121309663-bcd31600-c902-11eb-992c-44fda434f1db.png)

It's ok, eid is not required only in Target User, because it is a model not included in vocabularies, similar like ScientificDomain or Category.

2021-06-09 09:35 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Header for Life Cycle Statuses is Target User
![image](https://user-images.githubusercontent.com/59872096/121329181-42f85800-c915-11eb-820d-558472a57e27.png)

2021-06-09 12:25 UTC, Marcelinna commented on app/controllers/backoffice/vocabularies/provider_life_cycle_statuses_controller.rb
> +      redirect_to backoffice_vocabularies_provider_life_cycle_status_path(@vocabulary),
I can remove element from Provider Life Cycle Statuses (e.g Under Construction ) despite it is used in provider form.

2021-06-09 12:25 UTC, Marcelinna commented on app/controllers/backoffice/vocabularies/provider_life_cycle_statuses_controller.rb
> +    end
I can remove element from Provider Life Cycle Statuses (e.g Under Construction ) despite it is used in provider form.

2021-06-09 12:27 UTC, Marcelinna commented on app/controllers/backoffice/vocabularies/provider_life_cycle_statuses_controller.rb
> +end
I can remove element from Provider Life Cycle Statuses (e.g Under Construction ) despite it is used in provider form.

2021-06-09 12:42 UTC, Marcelinna commented on app/controllers/backoffice/vocabularies/provider_life_cycle_statuses_controller.rb
> +end
Alert: "This provider life cycle status has resources connected to it..........." it should be changed

2021-06-10 14:31 UTC, goreck888 commented on app/controllers/backoffice/vocabularies/provider_life_cycle_statuses_controller.rb
> +end
In this context "resources" doesn't mean exactly a Resource object, but other resources (other vocabularies set as parent, provider, resource etc.). Of course we could change it to "objects" or something else to have a consistency of our nomenclature.

2021-06-10 14:48 UTC, goreck888 commented on app/controllers/backoffice/vocabularies/provider_life_cycle_statuses_controller.rb
> +end
I changed it to successors.

2021-06-16 14:18 UTC, jswk requested changes
Sorry for slow processing, these are several possible improvements I've determined.

2021-06-16 14:18 UTC, jswk commented on app/controllers/backoffice/vocabularies_controller.rb
> +  }
This is great and all, but to avoid constantizing later on, you could specify the name and klass directly for each path. I.e.
```ruby
  VOCABULARY_TYPES = {
    "target_user": { name: "Target User", klass: TargetUser },
    ...
  }
```
this would remove exact class names from routes, and allow you to only differentiate based on resource name (possibly).

2021-06-16 14:18 UTC, jswk commented on app/controllers/backoffice/vocabularies_controller.rb
> +    end
I would also reorganize this method:
```ruby
    if @vocabulary.descendant_ids.present?
      redirect_back fallback_location: destroy_fallback_location,
                    alert: "This #{@type_name}
        has successors connected to it, therefore is not possible to remove it. If you want to remove it,
        please go to the #{@type_name} list view and edit them
        so they are not associated with this #{@type_name} anymore"
    elsif @vocabulary.services.present?
      redirect_back fallback_location: destroy_fallback_location,
                    alert: "This vocabulary has resources connected to it, remove associations to delete it."
    elsif @vocabulary.providers.present?
      redirect_back fallback_location: destroy_fallback_location,
                    alert: "This vocabulary has providers connected to it, remove associations to delete it."
    else
      @vocabulary.destroy!
      redirect_to send("backoffice_#{@vocabulary.model_name.element.pluralize}_path"),
                  notice: "#{@type_name} removed"
    end
```
The cases for providers and services could be merged too, however, this way it's more specific.

2021-06-16 14:18 UTC, jswk commented on spec/features/backoffice/vocabularies_spec.rb
> +      end
These two seem duplicated.

2021-06-18 08:39 UTC, jswk requested changes
Thanks for the corrections, it looks much better now.
There are only these several minor cases left and I think the PR is ready to go.

Also, remember about the changelog.

2021-06-18 08:39 UTC, jswk commented on app/controllers/backoffice/categories_controller.rb
> +    end
I'd do it the same as it is done in `vocabularies_controller.rb`.
Also, for category you know what associations it has (services, providers), so there is no need to use the syntax with try.

2021-06-18 08:39 UTC, jswk commented on app/controllers/backoffice/scientific_domains_controller.rb
> +                  alert: alert
I'd do it the same as it is done in `vocabularies_controller.rb`.
Also, for scientific_domain you know what associations it has (services, providers), so there is no need to use the syntax with try.

2021-06-18 08:39 UTC, jswk commented on spec/features/backoffice/vocabularies_spec.rb
> +    context "As a service portolio manager" do
I'd add another context level here, for example:
```ruby
context "For #{vocabulary}" do
  ...
end
```

2021-06-18 08:39 UTC, jswk commented on spec/features/backoffice/vocabularies_spec.rb
> +
I would keep the test for removing a vocabulary entry with children:
```ruby
      scenario "I cannot remove a vocabulary if it has children" do
        parent = create(vocabulary)
        create(vocabulary, ancestry: parent.id)

        visit send("backoffice_#{vocabulary}_path", parent)

        click_on "Delete"

        expect(page).to have_text("This #{humanized} " +
                                    "has successors connected to it, therefore is not possible to remove it. If you want to remove it, " +
                                    "please go to the #{humanized} list view and edit them so they are not associated " +
                                    "with this #{humanized} anymore")
      end
```

2021-06-21 10:00 UTC, jswk approved these changes
Looks good to go for me!

2021-06-21 11:12 UTC, Marcelinna commented
Please change notyfiktion:
When user try delete child :
This Legal Status has successors connected to it, therefore is not possible to remove it. If you want to remove it, edit them so they are not associated with this Legal Status anymore

When user try delete vocabularies conntected with resources/providers:

This vocabulary has resources/providers connected to it, remove associations to delete it.

2021-06-21 12:40 UTC, Marcelinna approved these changes

2021-06-21 13:36 UTC, merged