[#2088] Auth services subpages for draft and delete statuses
cyfronet-fid/marketplace pull request #2153
Opened 2021-06-10 06:37 UTC by danielkryska

- auth services offers
- auth services configuration
- auth services information
- auth services summary
- auth services cancel
- auth services question
- auth services opinions
- auth services details
- auth services ordering_configuration
- auth services ordering_configuration offers

2021-06-11 12:03 UTC, Marcelinna commented
Despite service is draft, I can see it in MP
https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/backoffice/services/envidat
![image](https://user-images.githubusercontent.com/59872096/121683227-5e05cc00-cabd-11eb-83a1-122ee9193a5f.png)
https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat now I don't even have to go to the subpage, you can see /service/{service.name}
![image](https://user-images.githubusercontent.com/59872096/121683338-868dc600-cabd-11eb-82e7-4fed7809f14e.png)
https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/details

2021-06-14 05:05 UTC, danielkryska commented
> Despite service is draft, I can see it in MP
> https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/backoffice/services/envidat
> ![image](https://user-images.githubusercontent.com/59872096/121683227-5e05cc00-cabd-11eb-83a1-122ee9193a5f.png)
> https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat now I don't even have to go to the subpage, you can see /service/{service.name}
> ![image](https://user-images.githubusercontent.com/59872096/121683338-868dc600-cabd-11eb-82e7-4fed7809f14e.png)
> https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/details

Your right. I forget to update the description. Here is update

- users with Service portfolio manager privilege or owning/administrating service can see resource in draft mode
- Service with status delete can be seen only in backoffice

2021-06-14 06:49 UTC, Marcelinna commented
Deleted status services 
![image](https://user-images.githubusercontent.com/59872096/121850132-99d2a880-ccec-11eb-962b-a794b02b7b43.png)
https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/backoffice/services/3dbionotes

- https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/3dbionotes/details
notyfication 

This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.

- https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/3dbionotes/offers
You are not authorized to see this page

- https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/3dbionotes/information
You are not authorized to see this page

- https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/3dbionotes/summary
You are not authorized to see this page

- https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/3dbionotes/opinions

This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.


Why notifications are differents

2021-06-14 06:58 UTC, Marcelinna commented
In description PR you point **cancel**
![image](https://user-images.githubusercontent.com/59872096/121851523-87596e80-ccee-11eb-8039-e475101b5cf7.png)


I'm not sure we have subpages /cancel

2021-06-14 07:51 UTC, danielkryska commented
> In description PR you point **cancel**, **question**
> ![image](https://user-images.githubusercontent.com/59872096/121851523-87596e80-ccee-11eb-8039-e475101b5cf7.png)

Some of the endpoints haven't UI representation and should be treated as REST requests. In the code:

```
resource :cancel, only: :destroy
resource :question, only: [:new, :create], constraints: lambda { |req| req.format == :js }

2021-06-14 08:49 UTC, Marcelinna commented
- [ ] DEV
- [ ] QA

Deleted resource

![image](https://user-images.githubusercontent.com/59872096/121865229-04d8ab00-ccfe-11eb-98e8-f975c46229f0.png)
![image](https://user-images.githubusercontent.com/59872096/121865271-0c984f80-ccfe-11eb-9c6c-3c3f21429141.png)

services/3dbionotes/details?from=backoffice_service

When I click on Details (services/3dbionotes/details?from=backoffice_service), Reviews or More about {service.name}, I see 

This resource is not published in the Marketplace **yet**, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab - which doesn't make sense

please change to You are not authorized to see this page, or make button dislabled.

2021-06-16 09:19 UTC, jswk requested changes

2021-06-16 09:19 UTC, jswk commented on app/controllers/api/v1/resources_controller.rb
> +      redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Don't handle it with redirect in API, here the response should just indicate an error.
Also, when removing the Service::NotAuthorizedError these two lines can just be dropped.

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/cancels_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/configurations_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/details_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/information_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/offers_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/opinions_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/ordering_configuration/offers_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/ordering_configurations_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/questions_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services/summaries_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/controllers/services_controller.rb
> +    redirect_to(request.referrer || root_path, alert: I18n.t("pundit.errors.#{e.reason}"))
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/policies/ordering_configuration/service_policy.rb
> +class OrderingConfiguration::ServicePolicy < ApplicationPolicy
Why a separate policy for ordering configuration, actually?

2021-06-16 09:19 UTC, jswk commented on app/policies/ordering_configuration/service_policy.rb
> +      scope.where(status: :published)
Why the narrowed down scope here? Maybe the code doesn't need to be duplicated from the root service_policy?

2021-06-16 09:19 UTC, jswk commented on app/policies/service_policy.rb
> +  end
Drop `Service::NotAuthorizedError` class and use existing mechanism for handling `Pundit::NotAuthorizedError` (see `app/controllers/application_controller.rb:18`, with use of query and proper translation in `config/locales/pundit.en.yml`).

2021-06-16 09:19 UTC, jswk commented on app/views/backoffice/services/_about.html.haml
> +      - if service.status != "deleted"
This can probably be replaced with a `policy(service).sth?` style call, keeping the authorization logic in one place.

2021-06-16 09:19 UTC, jswk commented on app/views/backoffice/services/_header.html.haml
> +      - if service.status != "deleted"
This can probably be replaced with a `policy(service).sth?` style call, keeping the authorization logic in one place.

2021-06-16 09:19 UTC, jswk commented on app/views/layouts/common_parts/services/_new_offer.html.haml
> +    - if service.status != "deleted"
This can probably be replaced with a `policy(service).sth?` style call, keeping the authorization logic in one place.

2021-06-16 09:19 UTC, jswk commented on app/views/services/_tabs.haml
> +        - if service.status != "deleted"
This can probably be replaced with a `policy(service).sth?` style call, keeping the authorization logic in one place.

2021-06-16 09:19 UTC, jswk commented on app/views/services/_tabs.haml
> +        - if service.status != "deleted"
This can probably be replaced with a `policy(service).sth?` style call, keeping the authorization logic in one place.

2021-06-16 09:20 UTC, jswk commented on app/policies/service_policy.rb
> +    )
`additional_access` is only used in the `draft` branch, so it should be calculated there.

2021-06-21 07:17 UTC, danielkryska commented on app/policies/ordering_configuration/service_policy.rb
> +class OrderingConfiguration::ServicePolicy < ServicePolicy
The policy has been created to keep the consistency of the policy system. Each level of nesting has its own Application Controller pointing to its own policies.

2021-06-21 10:29 UTC, jswk commented on app/policies/ordering_configuration/service_policy.rb
> +end
One more thing about this though...
User is now not checked if he has permissions to edit a service when navigating to the ordering_configuration, i.e. https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/elastic-cloud-compute-cluster-ec3/ordering_configuration. I can see it, without having any permissions about this service. (On master instance I get a permission denied error in that case.)
I think that you should make it look like this, so that the administration check is run before the parent's `show?` method:
```ruby
# frozen_string_literal: true

class OrderingConfiguration::ServicePolicy < ServicePolicy
    def show?     
        record.administered_by?(user) && super.show?
    end
end
```

2021-06-21 10:35 UTC, danielkryska commented on app/policies/ordering_configuration/service_policy.rb
> +end
done

2021-06-21 10:40 UTC, jswk approved these changes

2021-06-21 15:14 UTC, Marcelinna commented
on PR deleted services HADDOCK
[https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/backoffice/services/haddock](url)

[https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/haddock/offers](url)
[https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/haddock/information](url)
[https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/haddock/summary](url)
[https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/haddock/configuration](url)
[https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/haddock/ordering_configuration](url)

I see message This resource doesn't have any public offers. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.

![image](https://user-images.githubusercontent.com/59872096/122785915-0da81e80-d2b4-11eb-9b54-5623c83e0215.png)

2021-06-22 08:48 UTC, danielkryska commented
@Marcelinna, please try to test it on localhost using a seeded dataset. The issue you're describing may be related to another bug (importing system), which is not the scope of this ticket. 

**Deleted service**
![3dbionotes-deleted](https://user-images.githubusercontent.com/31220811/122894063-2ca3c080-d347-11eb-92b9-142dc2af7cc2.png)

Going to it without a login
![3dbionotes-deleted-notification](https://user-images.githubusercontent.com/31220811/122894124-375e5580-d347-11eb-9e53-e47c22cd61c8.png)

**Draft service**
![aginfra-agris-draft](https://user-images.githubusercontent.com/31220811/122894198-46dd9e80-d347-11eb-9d79-75d2982e9800.png)

Going to it without a login
![aginfra-agris-draft-notification](https://user-images.githubusercontent.com/31220811/122894266-552bba80-d347-11eb-941c-d6ae7cb02669.png)

Going to it with login and without privileges
![aginfra-agris-draft-notification-ordering](https://user-images.githubusercontent.com/31220811/122894383-6c6aa800-d347-11eb-9d25-f836a672e991.png)

2021-06-22 09:53 UTC, Marcelinna commented on config/locales/pundit.en.yml
> +      draft: "This resource is not published in the Marketplace yet, therefore it cannot be accessed.
You use this for draft status and deleted without privileges?

2021-06-22 10:21 UTC, Marcelinna commented on config/locales/pundit.en.yml
> +      draft: "This resource is not published in the Marketplace yet, therefore it cannot be accessed.
![image](https://user-images.githubusercontent.com/59872096/122908355-50b9ce80-d354-11eb-8507-94ff8388fba6.png)

2021-06-23 08:08 UTC, jswk requested changes

2021-06-23 08:08 UTC, jswk commented on CHANGELOG.md
> +- Secure services subpages access - deleted one can't be edited, those in draft state are visible only by service portfolio manager, its owner or its administrator (@danielkryska)
Move it to the next milestone section, i.e. to `3.16.0-milestone`. The section has to be added yet.

2021-06-24 06:31 UTC, michal-szostak commented
After discussion with @danielkryska , @kmarszalek and @Marcelinna I decided to put merging of this PR on hold until some issues have been clarified by @bwilk and @roksanaer .

There are following points which should be clarified / fixed:

* The code itself (@kmarszalek and @Marcelinna report that in some cases you can still get on some pages which should have been secured)
* Whether we really require different messages for different states. From my point of view user should not be informed why he can not see service - `404` error should be shown and that's it. Maybe some messages could be provided if the user has some additional permissions (access to BackOffice or something). But in the general case message `404 Not found` should be presented. There might be however, some business consideration why we do need more precise messages here - that's why we need to consult this with @roksanaer and @bwilk .

The issue itself is relatively old and is being merged into master - the merging itself can wait a few days until aforementioned points are clarified.

Additionally I agree with @kmarszalek that this PR requires more tests, as there are some cases where user *can* access pages which he / she should not be able to.

2021-06-25 09:27 UTC, Marcelinna commented
**Test case**

- User with role Resource Portfolio Manager
- Draft services (EnviDat - service has default offer, with parameters)

**main page**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat
Actual result: User has access to services 
Expected result:

**/details** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/details
Actual result: User has access to services 
Expected result:

**/offers**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/offers
Actual result: User has access to services and he is redirected to /services/envidat/information
Expected result:

**/information**:  https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/information
Actual result: User has access to services
Expected result:

**/summary**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/summary
Actual result: User has access to services and he is redirected to /services/envidat/configuration
Expected result:

**/configuration** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/configuration
Actual result: User has access to services 
Expected result:

**/ordering_configuration**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/ordering_configuration
Actual result: User has access to services
Expected result: 

**/opinions** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/opinions
Actual result: User has access to services 
Expected result:

**/cancel** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/cancel
Actual result: Page not found 
Expected result:

**/question** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/question
Actual result:Page not found 
Expected result:

**ordering_configuration#offers**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/ordering_configuration#offers
Actual result: User has access to services
Expected result:

2021-06-25 09:43 UTC, Marcelinna commented
**Test case**

-  User with role Resource Portfolio Manager
- Draft services (EnviDat - service has default offer, with parameters)

main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/details
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/offers
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/information
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/summary
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/configuration
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/ordering_configuration: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/ordering_configuration
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/opinions
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/ordering_configuration#offers
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

2021-06-25 09:59 UTC, Marcelinna commented
Test case

    User with role Resource Portfolio Manager or Resource owner
    Draft services (**EGI Archive Storage - service has default offer, without parameters**)

main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage
Actual result: User has access to services
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/details
Actual result: User has access to services
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/offers
Actual result: User is redirected to home page with alert
_This resource doesn't have any public offers. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/offers
Actual result: User is redirected to home page with alert
_This resource doesn't have any public offers. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/summary
Actual result: User is redirected to home page with alert
_This resource doesn't have any public offers. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/configuration
Actual result: User is redirected to home page with alert
_This resource doesn't have any public offers. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/ordering_configuration: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/ordering_configuration
Actual result: User is redirected to home page with alert
_This resource doesn't have any public offers. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/opinions
Actual result: User has access to services
Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/ordering_configuration#offers
Actual result: User is redirected to home page with alert
_This resource doesn't have any public offers. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

2021-06-25 10:08 UTC, Marcelinna commented
Test case

- User without role Resource Portfolio Manager or Resource owner
- Draft services (**EGI Archive Storage - service has default offer, without parameters**)

main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/details
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/offers
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/information
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/summary
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/configuration
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/ordering_configuration: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/ordering_configuration
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/opinions
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/egi-archive-storage/ordering_configuration#offers
Actual result: User is redirected to home page with alert
_This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab._
Expected result:

2021-06-25 10:41 UTC, Marcelinna commented
Test case

    User with role Resource Portfolio Manager or Resource owner
    Draft services (E-CAM Online Training Portal- service has few offers, without parameters)

main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal
Actual result: User has access to services
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/details
Actual result: User has access to services
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/offers
Actual result: User has access to services and he is redirected to /services/envidat/information
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/information
Actual result: User has access to services, he is rediredted to /offers
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/summary
Actual result: User has access to services, he is rediredted to /offers
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/configuration
Actual result: User has access to services, he is rediredted to /offers
Expected result:

/ordering_configuration: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/ordering_configuration
Actual result: User has access to services
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/opinions
Actual result: User has access to services
Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/ordering_configuration#offers
Actual result: User has access to services
Expected result:

2021-06-25 10:52 UTC, Marcelinna commented
Test case

    User without role Resource Portfolio Manager or Resource owner
    Draft services (E-CAM Online Training Portal- service has few offers, without parameters)

main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/details
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/offers
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/information
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/summary
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/configuration
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/ordering_configuration:User is redirected to home page with alert
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/opinions
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/ordering_configuration#offers
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

2021-06-25 11:05 UTC, Marcelinna commented
Test case

- User without role Resource Portfolio Manager or Resource owner
- Draft services (E-CAM Online Training Portal- service has few offers, with parameters)
![image](https://user-images.githubusercontent.com/59872096/123415172-287cda80-d5b5-11eb-961a-f17510c91949.png)
![image](https://user-images.githubusercontent.com/59872096/123415191-30d51580-d5b5-11eb-837e-68c5b6c43c31.png)


main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert
Actual result: User has access to services
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/details
Actual result: User has access to services
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/offers
Actual result: User has access to services
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/information
Actual result: User has access to services, he is redirected to /offers
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/summary
Actual result: User has access to services, he is redirected to /offers
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/configuration
Actual result: User has access to services, he is redirected to /offers
Expected result:

/ordering_configuration:User is redirected to home page with alert
Actual result: User has access to services
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/opinions
Actual result: User has access to services

Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/e-cam-online-training-portal/ordering_configuration#offers
Actual result: User has access to services
Expected result:

2021-06-25 11:23 UTC, Marcelinna commented
Test case

- User without role Resource Portfolio Manager or not the Resource owner
- Draft services (**eduPERT- service has few offers, with parameters**)
![image](https://user-images.githubusercontent.com/59872096/123415172-287cda80-d5b5-11eb-961a-f17510c91949.png)
![image](https://user-images.githubusercontent.com/59872096/123415191-30d51580-d5b5-11eb-837e-68c5b6c43c31.png)


main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/details
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/offers
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/information
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/summary
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/configuration
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/ordering_configuration: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/ordering_configuration
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/opinions
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/edupert/ordering_configuration#offers
Actual result: User is redirected to home page with alert
This resource is not published in the Marketplace yet, therefore it cannot be accessed. If you are the Resource Owner or Resource Portfolio Manager and wish to manage this resource, please log in and go to the Backoffice tab.
Expected result:

2021-06-25 12:13 UTC, Marcelinna commented
**Test case**

- User with role Resource Portfolio Manager or Resource owner
- Deleted services (**resource 1 - service had default offer, without parameters**)

**main page**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1
Actual result: You are not authorized to see this page
Expected result:

**/details** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1/details
Actual result: You are not authorized to see this page
Expected result:

**/offers**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1/offers
Actual result: You are not authorized to see this page
Expected result:

**/information**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1/information
Actual result: You are not authorized to see this page
Expected result:

**/summary**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1/summary
Actual result: You are not authorized to see this page
Expected result:

**/configuration** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1/configuration
Actual result: You are not authorized to see this page
Expected result:

**/ordering_configuration**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1/ordering_configuration
Actual result: You are not authorized to see this page
Expected result: 

**/opinions** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1/opinions
Actual result: You are not authorized to see this page
Expected result:

**/cancel** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/cancel
Actual result: Page not found 
Expected result:

**/question** : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/envidat/question
Actual result:Page not found 
Expected result:

**ordering_configuration#offers**: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-1//ordering_configuration#offers
Actual result: User has access to services, can add services with draft status to the project
Expected result:

2021-06-25 12:21 UTC, Marcelinna commented
Test case

- User with role Resource Portfolio Manager or Resource owner and User without role Resource Portfolio Manager or not the Resource Owner
- Deleted services (resource 2 - service had default offer, with parameters)

main page: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2
Actual result: You are not authorized to see this page
Expected result:

/details : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/details
Actual result: You are not authorized to see this page
Expected result:

/offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/offers
Actual result: You are not authorized to see this page
Expected result:

/information: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/information
Actual result: You are not authorized to see this page
Expected result:

/summary: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/summary
Actual result: You are not authorized to see this page
Expected result:

/configuration : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/configuration
Actual result: You are not authorized to see this page
Expected result:

/ordering_configuration: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/ordering_configuration
Actual result: You are not authorized to see this page
Expected result:

/opinions : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/opinions
Actual result: You are not authorized to see this page
Expected result:

/cancel : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/cancel
Actual result: Page not found
Expected result:

/question : https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/question
Actual result:Page not found
Expected result:

ordering_configuration#offers: https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/resource-2/ordering_configuration#offers
Actual result: User has access to services, can add services with draft status to the project
Expected result:

2021-07-29 07:23 UTC, Marcelinna commented
shouldn't be a changelog?

2021-07-30 07:48 UTC, Marcelinna commented
Case:
1. Go to backoffice - user with admin privilages or PM.
2. Chose service with draft status
![image](https://user-images.githubusercontent.com/59872096/127618054-d4c246b5-98b0-499f-b31e-7247c5c3164d.png)
3. Click "About" - url is https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/backoffice/services/authenix?from=backoffice_service
5. Go to "https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl/services/authenix?from=backoffice_service" - servis is visible in /services, but admin cant add this service to project, after click on the button "Access to resource", user is  not redirected anywhere, stays on the site, you can only add such a service to favorites or comparison
![image](https://user-images.githubusercontent.com/59872096/127619043-010b554f-28eb-45c9-9cee-fba27fb58e1d.png)

this is a very unlikely case please @michal decide if we leave it? or maybe we should fix it.

2021-07-30 11:16 UTC, michal-szostak commented
@Marcelinna that seems like a very narrow case - I'd say - if it's easily fixable (which it may or may not, as our policy framework might just be created in a way where admin can do anything) - we should fix it, but if it's not easily fixable it is alright to leave this edge case and work in it later.

2021-07-30 11:18 UTC, Marcelinna commented
> @Marcelinna that seems like a very narrow case - I'd say - if it's easily fixable (which it may or may not, as our policy framework might just be created in a way where admin can do anything) - we should fix it, but if it's not easily fixable it is alright to leave this edge case and work in it later.

so @danielkryska please give information it is easy to fix, or we should make other issue for this?

2021-07-30 11:20 UTC, michal-szostak approved these changes

2021-07-30 11:23 UTC, michal-szostak commented
Ok, I talked with @danielkryska and there is no quick answer to this. And given the fact that he's pretty occupied Today I'd say we should let this bug pass (I'll make follow up ticket).

I checked the code and it's ok - so if you could do a last check and give approve @Marcelinna .

2021-07-30 16:14 UTC, Marcelinna commented
@danielkryska The PR looks good, but I am asking for changes in the description of PR and commit message, because they are no longer valid.

- **disable all edition/creation of deleted service related items** - this should be removed, because the elements after all changes are visible again, we do not need to hide these elements, because they do not allow any edit for resources with the status deleted, I think that removing from descriptions is enough. 

![image](https://user-images.githubusercontent.com/59872096/127681040-22fc4968-e005-476d-866a-87fb23798556.png).

and I do not see the entry regarding the change: for not found service 404 page will always be shown (previously in some cases user was redirected to services list)

2021-07-30 16:16 UTC, Marcelinna approved these changes

2021-08-02 08:16 UTC, merged