[#1843] Remove corrupted logos
cyfronet-fid/marketplace pull request #2154
Opened 2021-06-10 12:10 UTC by danielkryska

2021-06-10 12:20 UTC, jswk requested changes

2021-06-10 12:20 UTC, jswk commented on lib/tasks/remove_corrupted_logos.rake
> +end
I reckon the name (or rather slug?) should be an argument for the task, as there is a number of services with incorrect logos.
You could pass it as rake arguments or an envvar. I actually recently learned that using rake arguments is not the most preferred way of doing that in rails (despite my using this mechanism recently...).

2021-06-10 12:20 UTC, jswk commented on db/schema.rb
> +
These are some peculiar changes, as you don't introduce any migration in this PR...

2021-06-10 12:32 UTC, danielkryska commented on db/schema.rb
> +
Removed

2021-06-10 12:34 UTC, danielkryska commented on lib/tasks/remove_corrupted_logos.rake
> +end
This rake doesn't need to be generic. The system will handle in the proper way the next occurrences of `SVG` to `PNG` conversion, but there are still crashed images in the app. Like in the `GBIF Spain Spatial Portal` service.

2021-06-10 12:35 UTC, danielkryska commented on lib/tasks/remove_corrupted_logos.rake
> +end
And they need to be handled only once

2021-06-10 13:50 UTC, jswk commented on lib/tasks/remove_corrupted_logos.rake
> +end
Ok, add this rationale to the commit message then, as it's not something that can be inferred from code.

Maybe also renaming the task to something more specific would be good as well, for example `remove_gbif_spain_spatial_portal_corrupted_logo`.

2021-06-10 13:52 UTC, jswk requested changes
Please consider this https://github.com/cyfronet-fid/marketplace/pull/2154#discussion_r649202588, and the PR would be fine by me.

2021-06-11 06:34 UTC, danielkryska commented on lib/tasks/remove_corrupted_logos.rake
> +end
I'd like to keep the rake name as it is and remove it in the next sprint with `add_extension_to_images`. The commit message has been changed.

2021-06-11 06:37 UTC, danielkryska commented on lib/tasks/remove_corrupted_logos.rake
> +end
I've created a task to remove images rakes #2155

2021-06-11 07:32 UTC, jswk reviewed
Was about to approve, but one more thing. :D

Add information about running this task in `docs/upgrade/3.15.0.md`, so that Wojt knows to run it.

2021-06-11 09:12 UTC, danielkryska commented
@wziajka has run the task from the command line in production to save additional work of adding and removing tasks from the repository.

The only influenced user was: https://marketplace.eosc-portal.eu/services/gbif-spain-spatial-portal

2021-06-11 09:12 UTC, closed without merging