Merge v3.14.0 to master
cyfronet-fid/marketplace pull request #2157
Opened 2021-06-11 13:58 UTC by jswk

2021-06-11 14:02 UTC, kmarszalek requested changes
what about version? @wziajka 
https://github.com/cyfronet-fid/marketplace/blob/merge-v3.14.0-to-master/VERSION

2021-06-11 14:08 UTC, jswk commented
> what about version?
> https://github.com/cyfronet-fid/marketplace/blob/merge-v3.14.0-to-master/VERSION

@wziajka?

2021-06-11 14:34 UTC, wziajka approved these changes

2021-06-12 17:31 UTC, kmarszalek approved these changes

2021-06-13 11:41 UTC, merged