[#2176] Only allow to regenerate API token
cyfronet-fid/marketplace pull request #2177
Opened 2021-06-25 14:13 UTC by jswk

Setting authorization_token to `revoked` made authorizing as such user
possible in the API. Having a unique constraint on that column also
prevented several users to have the token revoked simulataneously.

Remove possibility to revoke token altogether, leaving only the ability
to regenerate it.

Fixes: #2176.

2021-06-28 06:27 UTC, Marcelinna approved these changes

2021-06-28 07:56 UTC, wujuu requested changes

2021-06-28 07:56 UTC, wujuu commented on app/views/api_docs/show.html.haml
> -              = current_user.authentication_token
As there are users which indeed don't have a token yet (those that haven't been updated since the simple_token_auth gem was introduced), I think we should keep this part of the view as it looks much better than a simple blank where an authentication token should be

2021-06-28 11:01 UTC, Marcelinna approved these changes

2021-06-29 12:41 UTC, wujuu approved these changes

2021-06-29 12:48 UTC, merged