[#2171] Hide token on API docs page
cyfronet-fid/marketplace pull request #2181
Opened 2021-06-29 13:39 UTC by goreck888

Allow unlogged users to get the api_docs page
After log in api docs shows only '*' signs
Added button to reveal the token
with the ajax request
Closes #2171

2021-06-30 07:59 UTC, jswk requested changes
I'd rather KISS. The premise of #2171 is to hide the token, so for example during screen sharing it isn't accidentally leaked. There is no need to have an extra controller for that and load the token dynamically.
I would rather render both stars and the token into the DOM, but the token should be initially hidden. Then when the user clicks 'Show token'/'Hide token' it be toggled.

You wouldn't have to create all the request-handling machinery in the `unhide_controller.js` and extra routes. The JS controller would be much simpler, as it would only toggle visibility of the elements.

2021-06-30 07:59 UTC, jswk commented on app/controllers/api_docs_controller.rb
> +  before_action :authenticate_user!, only: [:create, :destroy]
I've recently stripped the `:destroy` method, so you can omit it here.

2021-06-30 10:33 UTC, wujuu approved these changes

2021-07-01 09:25 UTC, jswk requested changes
Much better now, I would only do some cleanup.

2021-07-01 09:25 UTC, jswk commented on spec/features/api_docs_spec.rb
> +      expect(page).to have_text("*" * user.authentication_token.size)
Verify that the token isn't visible too:
```ruby
expect(page).not_to have_text(user.authentication_token)
```

2021-07-01 09:25 UTC, jswk commented on app/javascript/app/controllers/unhide_controller.js
> +import Rails from '@rails/ujs'
I believe you no longer need this.

2021-07-01 09:25 UTC, jswk commented on spec/features/api_docs_spec.rb
> +      expect(page).to have_text(user.authentication_token)
Click the toggler again and verify the token is obfuscated again.

2021-07-01 09:25 UTC, jswk commented on spec/features/api_docs_spec.rb
> +    scenario "I can achieve the api_docs page" do
=> `I see api_docs page with login prompt`, `achieve` is incorrect in this context

2021-07-01 09:50 UTC, jswk reviewed
Aaaaand, changelog!

2021-07-02 12:21 UTC, Marcelinna commented
Please change button show/hide token
![image](https://user-images.githubusercontent.com/59872096/124273745-b3734d00-db40-11eb-9fac-11107ab94d73.png)
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/454770927_MyProfile_-_API_-_Token_Generated_Hidden

![image](https://user-images.githubusercontent.com/59872096/124273787-c0903c00-db40-11eb-8e3e-7eb4c4f4f8a0.png)
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/441030132_MyProfile_-_API_-_Token_Generated

2021-07-02 19:43 UTC, jswk approved these changes

2021-07-06 06:02 UTC, Marcelinna commented
Please look at the video
Steps to reproduce:
1. Click button show token
2. Click on button - Authentication - token is hiden
3. Click on button Intruduction - **token is shown for a moment**

is it possible to remove the situation when the token appears for a moment?


https://www.awesomescreenshot.com/video/4378912?key=225e82806a7a60b7b3857f09967375a4

2021-07-06 11:58 UTC, michal-szostak approved these changes

2021-07-06 12:01 UTC, Marcelinna approved these changes

2021-07-06 12:22 UTC, merged