[#1999] Provider search links to the provider page
cyfronet-fid/marketplace pull request #2212
Opened 2021-07-22 08:01 UTC by goreck888

Change link in autocomplete for providers
to the provider_path
Fixes #1999

2021-07-22 09:49 UTC, jswk requested changes
There is a regression regarding service authorization.
It is now possible to find deleted or draft services in all the search bars, not only in backoffice.
![image](https://user-images.githubusercontent.com/583197/126620441-15c4d66e-2239-44f8-9f69-923fd84e8f72.png)
Clicking it leads to:
![image](https://user-images.githubusercontent.com/583197/126620533-b0cc2533-6a48-4343-8b0b-191b54d5624f.png)

2021-07-22 11:13 UTC, Marcelinna commented
Master
![image](https://user-images.githubusercontent.com/59872096/126630378-8eb06e69-2b16-459b-904d-62c1e099dc58.png)

PR
![image](https://user-images.githubusercontent.com/59872096/126630448-11ac0d26-4902-4eac-8721-79856ea8782c.png)

2021-07-22 11:37 UTC, goreck888 commented
> There is a regression regarding service authorization.
> It is now possible to find deleted or draft services in all the search bars, not only in backoffice.
> ![image](https://user-images.githubusercontent.com/583197/126620441-15c4d66e-2239-44f8-9f69-923fd84e8f72.png)
> Clicking it leads to:
> ![image](https://user-images.githubusercontent.com/583197/126620533-b0cc2533-6a48-4343-8b0b-191b54d5624f.png)

Fixed.

2021-07-22 11:40 UTC, goreck888 commented
> Master
> ![image](https://user-images.githubusercontent.com/59872096/126630378-8eb06e69-2b16-459b-904d-62c1e099dc58.png)
> 
> PR it is problem with services
> ![image](https://user-images.githubusercontent.com/59872096/126630448-11ac0d26-4902-4eac-8721-79856ea8782c.png)

We don't have too much influence on what searchkick returns. I try to change the limit of results to 10, it should be better.

2021-07-26 09:04 UTC, jswk requested changes
These two test issues are to be addressed, otherwise only the changelog is missing.

2021-07-26 09:04 UTC, jswk commented on spec/features/search_spec.rb
> +  end
Something is off with this test failing. I cannot pinpoint a concrete place, but when I run the test without headless option for webdriver, it's impossible to find the created provider. Either the provider isn't synced to ES or the search query in autocomplete.rb is done incorrectly?
What's strange is that providers appear in development, or on the testing docker instance, but not in this test.

2021-07-27 18:24 UTC, goreck888 commented on spec/features/search_spec.rb
> +  end
Resolved. The problem was the created provider wasn't reindexed. Now this test pass.

2021-07-28 07:40 UTC, jswk requested changes
Aaand, changelog!

2021-07-28 09:14 UTC, jswk approved these changes

2021-07-28 10:19 UTC, Marcelinna approved these changes

2021-07-28 10:57 UTC, merged