[#1984] Fix questions in the resource opinion form
cyfronet-fid/marketplace pull request #2240
Opened 2021-08-05 14:54 UTC by goreck888

Fixes displayed "Question1" and "Question2" in the form
Remove dynamic translation from i18n and use GetText
Fixes #1984

2021-08-09 08:55 UTC, jswk requested changes
Since you remove dynamic translations, remove dangling entries from the yaml file too. In particular unused keys in `en.yml`, lines 15-31.

2021-08-09 11:27 UTC, wujuu approved these changes
What @jswk said. Besides that it's OK

2021-08-11 07:06 UTC, jswk approved these changes

2021-08-11 10:50 UTC, Marcelinna commented
PR is ok

2021-08-11 10:51 UTC, merged