[#2005] Store query params in comparison view
cyfronet-fid/marketplace pull request #2246
Opened 2021-08-09 15:01 UTC by goreck888

When user navigates from resources list
to the comparison view, query params are saved now
Fixes #2005

2021-08-16 08:41 UTC, jswk requested changes
There is also a problem with multi-valued filters, yet it seems to be a broader problem.

1. Go to services.
2. Select two sci-domains for filtering (path: `/services?scientific_domains[]=1&scientific_domains[]=26`).
3. Change ordering, for example to "Z-A" (path: `/services?scientific_domains[]=26&sort=-name`). The filter is now only for a single sci-domain.
4. If you try to re-add it, then the ordering is cleared (path: `/services?scientific_domains[]=1&scientific_domains[]=26`).

This is also present in master, so it should rather be handled separately.
Nevertheless, if you enter a correct path by hand into the address bar then the correct results are shown.

This seems to be related to what is happening here:
1. Go to services.
2. Select a sci-domain and custom sort (path: `/services?scientific_domains[]=1&sort=-name`)
3. Select two services for comparison, click compare.
4. Click "Add next resource", you are redirected to `/services?scientific_domains[]=1`, without sort.
5. Alternatively, if in the comparison view (step 3) you click "Clear all", then filter is cleared totally (e.g. you go to `/services`).

I would expect the sort to be saved too, though I may be mistaken and it's correct.
Multiply valued filter should be retained too, although this may be a deeper problem with searchable, may be left for later.
Also, in the code you add the query handling to the `destroy` method, yet it doesn't work at all. I would either make it work, or assume you don't handle it at all (when using `destroy` user anyway goes back to search, she may enter the filters again).

@Marcelinna what's your view on this?

2021-08-16 08:41 UTC, jswk commented on app/controllers/application_controller.rb
> +    end
Why is this necessary? You extract the params in comparisions_controller manually anyway.

I would define such before_action directly in comparisions_controller, as other controllers don't need this information (the `@query_params` variable).

2021-08-16 08:41 UTC, jswk commented on app/controllers/comparisons_controller.rb
> +    @query_params = session[:query] || {}
This would go.
You could keep the default-setting in before_action though.

2021-08-16 08:41 UTC, jswk commented on app/controllers/comparisons_controller.rb
> +    @query_params = session[:query_params]
This seems not to work since you use `:query` session key in other places, and not `:query_params`.

2021-08-17 10:01 UTC, Marcelinna commented
testing by adding and removing resource from comparison, on screen see that Alien and Invasive Species Virtual Research Environment is added to comparison, despite checkbox is not selected.
![image](https://user-images.githubusercontent.com/59872096/129705774-0048ba88-27db-4eb9-9ca3-32b4f8dd7a69.png)

2021-08-17 10:01 UTC, jswk requested changes
The comment about page is blocking, other two cosmetic.

2021-08-17 10:04 UTC, jswk commented
BTW, how about we don't store and restore the query params at all here, but open the comparison in a new tab, as other webpages sometimes do? See https://x-kom.pl for an example of this behaviour.
In that case state is stored in a separate tab, just like this. And a user can navigate between tabs as she wishes.

2021-08-17 10:36 UTC, goreck888 commented on app/controllers/comparisons_controller.rb
> +    def query_params
Ok

2021-08-17 10:40 UTC, goreck888 commented on app/controllers/concerns/service/searchable.rb
> +      session[:query][:per_page] = params[:per_page] unless params[:per_page].blank?
Done

2021-08-17 11:51 UTC, jswk commented on app/views/services/_index.html.haml
> +.container
Later on you have the call `if (not defined? show_comparison) || show_comparison`, I would assign it here such as:
```haml
- effective_show_comparison = local_assigns.fetch(:show_comparison, true)
```
And later on use just the `effective_show_comparison`.

2021-08-17 11:51 UTC, jswk commented on app/views/services/_index.html.haml
> +    .col-lg-9{ "data-controller": "comparison favourite" }
I believe the `comparison` controller shouldn't be loaded if `effective_show_comparison` is false.
The line would read:
```
     .col-lg-9{ "data-controller": "favourite" + (effective_show_comparison ? " comparison" : "") }
```

2021-08-17 11:51 UTC, jswk commented on app/views/services/_index.html.haml
> +      - if (not defined? show_comparison) || show_comparison
And you could use the `effective_show_comparison` here too.

2021-08-17 11:52 UTC, jswk commented on CHANGELOG.md
> +- Storing resource query parameters by visiting the comparison page (@goreck888)
I'd say it's rather an added feature.

2021-08-17 11:53 UTC, jswk commented on app/controllers/comparisons_controller.rb
> +    session[:comparison] = @services = []
Setting `@services` to an empty array seems unnecessary here.
There is no view associated with this method anyway.

2021-08-17 12:13 UTC, jswk approved these changes

2021-08-17 13:06 UTC, Marcelinna approved these changes

2021-08-17 14:04 UTC, jswk requested changes

2021-08-17 14:04 UTC, jswk commented on CHANGELOG.md
> +>>>>>>> Move comparison data-controller to service box partial
Please resolve this conflict before pushing

2021-08-17 14:19 UTC, jswk approved these changes

2021-08-17 14:44 UTC, merged