[#1961] Fix sorting for resources
cyfronet-fid/marketplace pull request #2247
Opened 2021-08-10 09:47 UTC by kmarszalek

- Fixed sorting by name
- Added test that checks sorting with lower/upper cases

Elasticsearch follows ASCII sort order, the bytes that represent
capital letters have lower ASCII values than that of lowercase letters.
By changing name to name.downcase in search_data we can sort resources
in alphabetical order regardless of their ASCII codes.

Closes #1961

2021-08-10 11:07 UTC, jswk approved these changes

2021-08-10 11:40 UTC, Marcelinna approved these changes

2021-08-10 12:10 UTC, jswk requested changes
The change in search_data propagates to the autocomplete unfortunately. (Only the "Resources" section, "Providers" and "Offers" stay correct.)
![image](https://user-images.githubusercontent.com/583197/128864224-6bd74749-63e6-4fe5-870c-3c77fd129abb.png)

2021-08-16 13:08 UTC, jswk requested changes
There's sort_options in backoffice/services_controller.rb too, it should have the sorting field altered too.

2021-08-16 13:24 UTC, jswk approved these changes

2021-08-16 13:40 UTC, merged