[#2003] Fix new resource preview error
cyfronet-fid/marketplace pull request #2248
Opened 2021-08-10 11:49 UTC by danielkryska

2021-08-10 12:42 UTC, Marcelinna commented
changelog

2021-08-11 07:39 UTC, Marcelinna commented
Step to reproduce problem
1. Go to backoffice
2. Choose Resource "100 Percent IT Trusted Cloud"
![image](https://user-images.githubusercontent.com/59872096/128988829-c992143e-1968-4567-889e-e8c8b62ec200.png)
3. Click buuton "EDIT"
4. Click button "Preview"
5. See error - resource doesnt have logo
![image](https://user-images.githubusercontent.com/59872096/128988107-b0a27653-7516-48ba-8da2-17038a95b9a3.png)


beta:
![image](https://user-images.githubusercontent.com/59872096/128988793-c052e94a-b6ec-42bf-86f5-e54925bdee3f.png)

2021-08-11 07:57 UTC, danielkryska commented
> Step to reproduce problem
> 
> 1. Go to backoffice
> 2. Choose Resource "100 Percent IT Trusted Cloud"
>    ![image](https://user-images.githubusercontent.com/59872096/128988829-c992143e-1968-4567-889e-e8c8b62ec200.png)
> 3. Click buuton "EDIT"
> 4. Click button "Preview"
> 5. See error - resource doesnt have logo
>    ![image](https://user-images.githubusercontent.com/59872096/128988107-b0a27653-7516-48ba-8da2-17038a95b9a3.png)
> 
> beta:
> ![image](https://user-images.githubusercontent.com/59872096/128988793-c052e94a-b6ec-42bf-86f5-e54925bdee3f.png)

Issue fixed

2021-08-12 09:13 UTC, Marcelinna commented
**Logo The logo** format you're trying to attach is not supported. Supported formats: png, gif, jpg, jpeg, pjpeg, tiff, vnd.adobe.photoshop or vnd.microsoft.icon.

![image](https://user-images.githubusercontent.com/59872096/129170523-b64b7792-974b-4176-82c8-0cbaaf1adac3.png)


Please delete repeating

2021-08-12 09:22 UTC, danielkryska commented
> **Logo The logo** format you're trying to attach is not supported. Supported formats: png, gif, jpg, jpeg, pjpeg, tiff, vnd.adobe.photoshop or vnd.microsoft.icon.
> 
> ![image](https://user-images.githubusercontent.com/59872096/129170523-b64b7792-974b-4176-82c8-0cbaaf1adac3.png)
> 
> Please delete repeating

done

2021-08-12 11:43 UTC, goreck888 requested changes
Just leave `get` in method names. Otherwise everything looks ok

2021-08-12 11:43 UTC, goreck888 commented on app/helpers/image_helper.rb
> +  def self.get_default_logo_path
In rails we avoid to use `get` in the method names.

2021-08-12 11:49 UTC, Marcelinna commented
Steps to reproduce 
1. Go to /backoffice/services
2. Click the button "Create new resource"
3. Fill required field and add logo in valid format
4. Click button "Preview"
5. Click button "Go back to edit"
6. Click button "Create resource"

See error 
![image](https://user-images.githubusercontent.com/59872096/129191363-ed3796fe-c4bb-4e90-bf35-dce16b9c59c1.png)

2021-08-16 11:00 UTC, Marcelinna commented
please add some the tests

2021-08-17 08:24 UTC, Marcelinna approved these changes

2021-08-17 10:36 UTC, goreck888 approved these changes

2021-08-17 10:52 UTC, merged