[#2255] Fix unauthorized access to ordering_configuration
cyfronet-fid/marketplace pull request #2257
Opened 2021-08-12 07:21 UTC by goreck888

Change the policy for Resource authorization
in `ordering_configurations_controller`
Pundit used default `ServiceContextPolicy`
instead of correct
`OrderingConfiguration::ServiceContextPolicy`
Fixes #2255

2021-08-12 08:54 UTC, Marcelinna commented
only the resource administrator should be able to access / ordering_configuration, Portfolio Manager should not be able to access

2021-08-12 09:17 UTC, jswk requested changes

2021-08-12 09:17 UTC, jswk commented on app/policies/ordering_configuration/service_context_policy.rb
> +    super && (record.service.administered_by?(user) || user.service_portfolio_manager?)
As @Marcelinna mentioned, this shouldn't be added.
The test will have to be adjusted.

2021-08-12 09:17 UTC, jswk commented on app/controllers/services/ordering_configurations_controller.rb
> +                policy_class: OrderingConfiguration::ServiceContextPolicy)
I don't like this construct, it seems to go against the rails conventions.

However, I've noticed a way this could be done better. Just make this class extend `Services::OrderingConfiguration::ApplicationController` instead of `Services::ApplicationController`, then the policy is resolved correctly.

Then you can safely drop the line 4 (i.e. `before_action :authenticate_user!`) from this class too.

2021-08-12 13:23 UTC, goreck888 commented on app/policies/ordering_configuration/service_context_policy.rb
> +    super && (record.service.administered_by?(user) || user.service_portfolio_manager?)
Ok

2021-08-12 13:24 UTC, goreck888 commented on spec/features/ordering_configuration_spec.rb
> +          visit service_ordering_configuration_path(service)
Done

2021-08-12 13:41 UTC, jswk approved these changes

2021-08-13 05:55 UTC, Marcelinna commented
Steps to reproduce 
1. I am admin and go to resource
2. Resource has to offer, I choose one and click button "EDIT" 
3. I have two button (Delete offer and Update Offer)
![image](https://user-images.githubusercontent.com/59872096/129311253-820c32e0-f2d8-4613-adbf-bec6f359a1fd.png)
4**. I lost admin privilage**
5. I click the button "Delete"
6. I see error 
![image](https://user-images.githubusercontent.com/59872096/129311365-57eb9915-fca3-4ab8-9525-408cc74b9089.png)

@goreck888  Should I create a separate tiket for this issue?

2021-08-13 08:06 UTC, Marcelinna approved these changes

2021-08-13 08:09 UTC, merged