[#2085] Fix incorrect classification value on PC sync
cyfronet-fid/marketplace pull request #2258
Opened 2021-08-12 09:17 UTC by danielkryska

2021-08-13 07:05 UTC, Marcelinna approved these changes

2021-08-13 09:37 UTC, jswk requested changes

2021-08-13 09:37 UTC, jswk commented on CHANGELOG.md
> +- Fix incorrect classification value on PC sync - better User Experience (@danielkryska)
Please add the changelog in the correct section (i.e. in `3.19.0-milestone`)

2021-08-13 09:37 UTC, jswk commented on app/models/concerns/importable.rb
> +    domains.present? && domains.length > 0 ?
It's unnecessary to check for the length. The `present?` call already takes it into account, see:
```
$ rails c
Loading development environment (Rails 6.0.3.7)
[1] pry(main)> nil.present?
=> false
[2] pry(main)> [].present?
=> false
[3] pry(main)> [1].present?
=> true
```

2021-08-13 09:37 UTC, jswk commented on app/services/service/pc_create_or_update.rb
> +      source.update(errored: check_service&.errors&.messages)
`check_service` is a boolean as it's set like this `check_service = Service.new(service_hash).invalid?`, so it won't have more state.
I would just set the errored to `check_service`, i.e.:
```
       source.update(errored: check_service)
```

2021-08-16 07:41 UTC, jswk approved these changes

2021-08-16 08:41 UTC, merged