[#2083] Fix choices field on modals
cyfronet-fid/marketplace pull request #2262
Opened 2021-08-13 09:59 UTC by wujuu

Closes #2083

2021-08-13 11:47 UTC, goreck888 approved these changes

2021-08-13 11:53 UTC, goreck888 commented
It looks ok, just add a changelog entry :)

2021-08-13 13:04 UTC, jswk requested changes
Split the PR into two commits: one with stylistic corrections and the other with actual issue fix.

2021-08-16 05:58 UTC, Marcelinna approved these changes

2021-08-16 14:35 UTC, jswk approved these changes

2021-08-17 07:33 UTC, merged