[#1965] Reindex resource by offer update
cyfronet-fid/marketplace pull request #2289
Opened 2021-08-27 16:18 UTC by goreck888

Add resources reindexing by offer update/remove
(needed for valid `order_type` queries in ES)
Add changing resource order type
after multiple offers deletion
Fixes #1965 

## Offers logic

@jswk this is information for offers logic update

- Add a new offer with different order_type as in service causes change labels to the "various types", filters are searching by order_type of offers and a service
- Set default offer by removing other offers will update offer order_type from a service
- Create the first offer will update offer order_type from a service

### NOTICE
If we remove default offer (offer with the same order_type as in a service) and we have a few offers with different types, existing offers will be not updated for compatibility with the service order_type.

2021-08-30 07:29 UTC, Marcelinna commented
When I delete offer I has error, but offer is deleted
![image](https://user-images.githubusercontent.com/59872096/131302005-bbb9b463-0def-4179-8dae-6fdb5e56db34.png)

2021-08-30 09:57 UTC, Marcelinna commented
1. create resource - full open access
2. add offer - open acces
3. order required
4. other 
5. delete full open access, open access, order required
6. resource is Various order types and I can see resource on (full open access, opne access, order required and other filtr)

@goreck888 we can do not consider deleted offers??

2021-08-30 11:08 UTC, Marcelinna commented
1. Create resource - order type Other 
2. Delete all offer via API
![image](https://user-images.githubusercontent.com/59872096/131330192-fcdb9b50-83ce-4696-b6b0-e0007346af12.png)
3. Create new offer - Order required
4. Service is order type Other and has oreder required offer
![image](https://user-images.githubusercontent.com/59872096/131330397-23ee08e4-11aa-47ce-a256-119bcc476194.png)
![image](https://user-images.githubusercontent.com/59872096/131330350-80bddc0f-2e18-4a40-9e0b-3216bad1dab7.png)

2021-09-02 07:08 UTC, kmarszalek requested changes
it doesn't work as expected. Service changes status to the wrong one when there is deleted offer. it works fine when there are no deleted offers.

2021-09-03 09:52 UTC, Marcelinna commented
1. Create resource Order required - resource is _Order Required Internal_, make update in PC - all time resource is order required internal. Change type to Open Access In PC, and change again to Order Required - Resource is _Order Required External_.  

2. Create resource Order required - resource is _Order Required Internal_. Add new offer Open Access. Delete first offer Order required, Resource is _Order required external_. 

The logic from point 1 is known to me and talking to @jswk, this is how it should work, I do not know how to do the second point, but I think it should go to the offert documentation and be determined.

2021-09-03 10:18 UTC, kmarszalek approved these changes
now it looks ok :)

2021-09-03 10:36 UTC, Marcelinna approved these changes

2021-09-03 11:35 UTC, merged