[#2299] Fix default offer's order_type bad mapping
cyfronet-fid/marketplace pull request #2300
Opened 2021-09-08 08:00 UTC by goreck888

Issue caused by wrong sequence of methods.
Offer::Create takes order_type from the persisted,
not updated object
Fixes #2299

2021-09-08 08:47 UTC, Marcelinna commented
Test cases 1

1. Create resource - Open Access - order type: Open Access
2. Update in PC - Order Required -  order type: Order Required
3. Update in PC - Other - order type: Other order type 
4. Add offer Full Open Acces - Various order types (too offers) Filters: Other, Full Open Access
5. Delete Other offer - order type: Other order type, Filters: Other
6. Update in PC - Open Access - order type: Open Access


Test case 2
1. Create resource - Order Required - order type: Order required
2. Add offer Open Access - Various order types (too offers) Filters: Order required, Open Access
3. Add to the project Open Access offer
4. Delete offer Open Access - order type: Order required, Filters: Order required
5. Update in PC - Full Open Access - order type: Full Open Access, Filters: Full Open Access

2021-09-08 08:55 UTC, Marcelinna commented
Problem in PR 
1. Create resource - Order required
2. Add new offer - Open Access
3. Order Open Access offer
4. Delete Open Access offer
5. Resource has one offer order required
![image](https://user-images.githubusercontent.com/59872096/132478512-e92bdcad-5d3d-4103-b166-5453bdbdcd64.png)
6. Click button "Edit offer"
7. Change order type to Open Access
8. See problem Resource has one offer but it is Various order types, service and offer has different type
![image](https://user-images.githubusercontent.com/59872096/132478673-bbd96cc0-291d-41c5-a12b-c7d3a28563ce.png)

2021-09-08 12:19 UTC, Marcelinna approved these changes

2021-09-09 11:37 UTC, jswk requested changes
I'd say that the lines 10-12 in app/services/offer/create.rb should be removed to fix this issue.
when Offer::Create is called the order_type should already be correctly set.
However, the order change is also okay and should work for now, until the offer logic isn't revamped.
Nevertheless, **a test for this behaviour must be added**, so that it isn't lost later on in development.

The extra changes (i.e. the added published) seem to be ok, but I would extract them to another commit, as they don't affect the main issue here.

2021-09-10 09:23 UTC, Marcelinna commented
The PR looks ok. 

It is possible to edit the offer when the resource has only one. If the resource has two offers, you just need to open both in edit mode in two separate tabs. One to delete and the other to edit. After editing such an offer, we have the problem indicated above in the comment. Resource has a different type and its only offer is different. This is an unlikely case, probably not for this PR, because this problem also applies to the possibility of removing the default offer (if it is fixed, it can be together)

2021-09-13 13:09 UTC, jswk commented on app/services/service/update.rb
> +    end
Since you removed the lines from Offer::Create, reordering this isn't needed anymore.

2021-09-13 13:09 UTC, jswk commented on app/views/backoffice/services/offers/_form.html.haml
> +                    readonly: service.offers.published.size == 0 && service.order_type.present?
Why such a condition?, and why apply it only to this field and not to `:internal` or some other fields? I don't understand the logic behind it, could you elaborate?

2021-09-13 16:34 UTC, goreck888 commented on app/views/backoffice/services/offers/_form.html.haml
> +                    readonly: service.offers.published.size == 0 && service.order_type.present?
Default offer should have the same order_type as a service. So the first condition is met if we create the first offer.  
The second condition applies to situation, when order_type in service is not set (because it's not mandatory field in the service form). 
Any other field isn't service-dependent, so that's the reason we leave it editable :)

2021-09-14 08:34 UTC, jswk requested changes
Thanks for the clarification, this logic seems correct indeed.

Only thing left is that you reverted the changes from `update.rb` in the second commit, but introducing it in the first one. Just remove this reorder from the first commit, then reverting it in the second one won't be necessary.

Otherwise it's good to go.

2021-09-16 06:38 UTC, jswk approved these changes

2021-09-16 06:51 UTC, jswk reviewed
Please add a changelog entry too in a the first, fixing, commit.

2021-09-16 09:06 UTC, jswk approved these changes

2021-09-16 09:17 UTC, kmarszalek approved these changes

2021-09-16 09:29 UTC, merged