[#1975] Include resources without offers in statistics
cyfronet-fid/marketplace pull request #2301
Opened 2021-09-10 08:07 UTC by goreck888

Method `Service.joins(:offers)` doesn't include
resources without offers,
which causes they were not included
in order_type statistics.
Use `Service.left_outer_joins` instead.
Fixes #1975

2021-09-10 10:34 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/132840138-6a515442-def6-475e-a28a-a6498036dd2b.png)
Add resource order required - internal
![image](https://user-images.githubusercontent.com/59872096/132840648-a4ed61f4-e84f-4d5b-8e5c-d97282196513.png)
Change resource ro order required - external
![image](https://user-images.githubusercontent.com/59872096/132840767-906cdf1f-c58b-4177-a618-3b99570b4d0b.png)

Statistic doesn't changed

2021-09-10 10:42 UTC, Marcelinna commented
1. Statistic before editing
![image](https://user-images.githubusercontent.com/59872096/132841456-32a3517d-cf9c-47c5-aa96-a2ca02268880.png)
2. Update resource in PC from Order required internal to Open Access
![image](https://user-images.githubusercontent.com/59872096/132841554-0b4a1d62-d8ac-4736-983b-f04ce67a1f1e.png)
3. Update resource in PC from Ordering internal to Ordering external
![image](https://user-images.githubusercontent.com/59872096/132841651-c53433e7-bc8a-4c95-aa92-0ff2ef36c8e6.png)

Resource Ordering external all count in Marketplace ordering, Number of EOSC resources with offerings using EOSC Marketplace ordering process

2021-09-14 08:35 UTC, jswk commented
I understand that this requires correction, since numbers don't match up. Is it correct @goreck888?

2021-09-16 09:47 UTC, goreck888 commented
> I understand that this requires correction, since numbers don't match up. Is it correct @goreck888?

Yeah, it's fixed

2021-09-16 11:18 UTC, jswk requested changes
The tests for the usage report were not updated and they give a wrong impression that services without offers should be ignored in the counts, for example:
![image](https://user-images.githubusercontent.com/583197/133602795-11d1d4de-3785-4e90-83af-8244373e26a3.png)

They should be updated to match changes introduced in this PR. You should also add test cases for services that should be counted now.

2021-09-17 13:23 UTC, jswk approved these changes

2021-09-17 13:28 UTC, kmarszalek approved these changes
wait for Marcelina

2021-09-17 15:16 UTC, jswk requested changes
Since 3.21.0-beta.0 was already released, please move the changelog entry to 3.22.0-milestone section.

2021-09-21 07:51 UTC, jswk requested changes

2021-09-21 07:51 UTC, jswk commented on CHANGELOG.md
> +## [3.22.0-milestone]
Please don't remove the section for 3.21.0, even though it's empty.
Add the changelog entry in a new section.

2021-09-21 08:01 UTC, goreck888 commented on CHANGELOG.md
> +## [3.22.0-milestone]
Ok

2021-09-21 10:41 UTC, Marcelinna approved these changes

2021-09-21 12:40 UTC, jswk approved these changes

2021-09-21 13:08 UTC, merged