[#2139] Fix project message caption
cyfronet-fid/marketplace pull request #2309
Opened 2021-09-20 12:03 UTC by wujuu

Closes #2139

2021-09-20 12:34 UTC, jswk requested changes

2021-09-20 12:34 UTC, jswk commented on config/locales/en.yml
> +          answer: "Message from the project support"
The scope of the ticket was only to change the title for the user messages. If you want to handle provider/ops-team messages then you should differentiate based on `message.author_role`.
For example, if a message from provider is shown in the context of a project, then the text "Message from the project support" will be incorrect, as the message will be from a resource provider. The inverse will happen if you are in the context of a project_item.

So, either stick to the ticket or extend the ticket to handle other author_roles correctly.

2021-11-15 12:01 UTC, jswk commented on app/helpers/project_items_helper.rb
> +    date = message.created_at.to_formatted_s(:short)
Format the date with a more complete format. I would use `:db`, as it creates a nice "2021-11-15 11:25:06", following the prevs more closely.

2021-11-15 12:04 UTC, jswk commented on app/helpers/project_items_helper.rb
> +    "#{date}#{author_identity(message)}, #{author_title(message)}"
The ordering should actually depend on whether it's a provider/mediator message or a user message. In the latter case the order should be reversed.
The prev:
![image](https://user-images.githubusercontent.com/583197/141778947-641aac25-9a3d-45ba-a87a-a3fe4b1245a1.png)
And in this branch:
![image](https://user-images.githubusercontent.com/583197/141778999-3cd8964e-9ac3-4967-bf3a-1e41962ec9a2.png)

2021-11-15 12:12 UTC, jswk commented on app/views/messages/_message.html.haml
> +  -# TODO: Change the class name from "edited" to something else ("message_to_user" perhaps?)
Change the class name, not leaving behind a TODO. In the styles it only defines a different background anyway.
When changing it's name follow up to rename `$edited-comment-background-color` and `$edited-comment-border-color` as they won't describe edited styles anymore.

2021-11-15 12:19 UTC, wujuu commented on app/helpers/project_items_helper.rb
> +    "#{date}#{author_identity(message)}, #{author_title(message)}"
I thought this was a mistake on the prev, will fix

2021-11-15 12:24 UTC, wujuu commented on app/helpers/project_items_helper.rb
> +    date = message.created_at.to_formatted_s(:short)
How about ""November 15, 2021 13:24", isn't this more readable and user-friendly?

2021-11-15 12:56 UTC, jswk commented on app/helpers/project_items_helper.rb
> +    date = message.created_at.to_formatted_s(:short)
I would stick to the `:db` version for now, it's more standard. If there arise issues with `:db` we could migrate to `:long` or something more custom (however, I would leave the `:db` rendering in `alt` in that case).

2021-11-15 13:00 UTC, jswk approved these changes
Perfect, thanks!
Just remember to squash before merging.

2021-11-16 07:31 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/141940466-63573a30-2be1-4011-8c87-8d0259228d8c.png)
we should indicate what time we use

2021-11-16 08:34 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/141949004-03421861-3c4f-4b7b-ae9e-275ddebe5e4d.png)
on previews I see pink underline with word "NEW". It has not been implemented in this PR?

2021-11-16 08:43 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/141951776-cb085145-d1ce-4fcd-9160-519bf613b9b2.png)
![image](https://user-images.githubusercontent.com/59872096/141951943-ce402798-191c-4bbd-a245-6e01a8f7f654.png)

the styles should be the same for both views

2021-11-16 08:52 UTC, wujuu commented
> ![image](https://user-images.githubusercontent.com/59872096/141949004-03421861-3c4f-4b7b-ae9e-275ddebe5e4d.png) **QA comment:** on previews I see pink underline with word "NEW". It has not been implemented in this PR? **DEV comment:**

You're right, but this is a feature that will be implemented in another PR: #2406

2021-11-16 10:18 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/141966748-c0572671-a48b-48a6-b03a-27ae32b028df.png)
email is write in brackets, when email isn't entered, bracet is empty. Maybe we should get rid of the bracket?

2021-11-16 13:36 UTC, wujuu commented
> ![image](https://user-images.githubusercontent.com/59872096/141966748-c0572671-a48b-48a6-b03a-27ae32b028df.png) email is write in brackets, when email isn't entered, bracet is empty. Maybe we should get rid of the bracket?

This is dues to ability to enter an empty string ("") instead of nil in the `email` field in the Message model. This should not be possible. Will add the ticket to add proper validation to this field (nil or email regex)

2021-11-16 14:20 UTC, wujuu commented
> ![image](https://user-images.githubusercontent.com/59872096/141940466-63573a30-2be1-4011-8c87-8d0259228d8c.png) we should indicate what time we use
> 
> QA comment: It will be continue in other PR

This is a scope for another issue: https://github.com/cyfronet-fid/marketplace/issues/2410

2021-11-16 14:40 UTC, Marcelinna approved these changes

2021-11-16 20:02 UTC, merged