[#2273] Improve preview functionality
cyfronet-fid/marketplace pull request #2327
Opened 2021-10-04 07:57 UTC by goreck888

Add all hidden buttons and links in preview
and disable them via js controller
Closes #2273

2021-10-04 13:43 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/135862254-7f37192a-4a6f-4281-908b-0249b4086d61.png)
 public contact is clickable

2021-10-12 11:47 UTC, Marcelinna commented
@kmarszalek @goreck888 it is ok, If I try to open the link in a new tab in preview mode, in the new tab I see URL - > _javascript:;_ ?
![image](https://user-images.githubusercontent.com/59872096/136950340-784eab6f-6223-4402-9c9e-35eeaec3d739.png)

2021-10-12 12:00 UTC, Marcelinna commented
Looks ok, I am waiting for a review from the developer before final approval

2021-11-02 19:08 UTC, Marcelinna commented on app/javascript/app/controllers/preview_controller.js
> +
console.log() shouldn't be deleted?

2021-11-02 22:45 UTC, goreck888 commented on app/javascript/app/controllers/preview_controller.js
> +
Done

2021-11-03 09:55 UTC, Marcelinna commented
Can you check this?

Steps to reproduce
1. Go to backoffice/services/new
2. Add logo in the wrong format
3. Click button "Preview"
4. See error
![image](https://user-images.githubusercontent.com/59872096/140039835-abadc2e9-8190-4bb3-b1eb-61d7b18e621c.png)

Expected result: Error message about wrong format should be displayed

2021-11-10 12:00 UTC, Marcelinna commented
Steps to reproduce 
1. Go to  backoffice/services/new
2. Add wrong format 
3. Click "Previews" - error message is displayed correctly
4. Add wrong format
5. Click "Create resource"
6. See error
![image](https://user-images.githubusercontent.com/59872096/141109329-c0972c6d-6d58-411f-93d9-a3a8db6c65e2.png)

2021-11-15 14:12 UTC, kmarszalek commented on app/views/services/_about.html.haml
> +        %a.more-details{ href: service_details_path(service), "data-shepherd-tour-target": "service-more-about",
i would refactor this line like the one at 48

2021-11-15 14:15 UTC, kmarszalek requested changes
looking good, some minors.
console.log, one-line refactor and missing changelog

2021-11-16 09:33 UTC, kmarszalek approved these changes

2021-11-16 09:47 UTC, Marcelinna approved these changes

2021-11-16 09:48 UTC, merged