Bundle configuration form validation
cyfronet-fid/marketplace pull request #2379
Opened 2021-11-02 08:17 UTC by goreck888

Add a validation of bundled parameters
in the configuration step of the service ordering form

Fixes #2342

2021-11-02 13:44 UTC, jswk requested changes
Also, the test: `ProjectItem::Create#bundle with error creates nothing` fails in the CI.
It's most likely because I depended on project being invalid when there are multiple offers from the same service. It's no longer enforced for bundled offers, so no error is generated.
You should make the project in that test invalid again, so that the test remains functional.

2021-11-02 13:44 UTC, jswk commented on app/models/offer.rb
> +    bundle? && (parameters.present? || bundled_offers.map(&:parameters).present?)
I understand, that in `bundled_offers.map(&:parameters).present?` you wanted to catch a case, when any of the bundled offers has any params. However, this part will always return true, given any bundled offer, see below for why.

The `bundled_offers.map(&:parameters)` will return an array of parameters, e.g. `[{...}, {...}]`. If parameters are absent, then it will look like `[nil]`. If you call `[nil].present?`, you still get true.

What you wanted was rather `bundled_offers.map(&:parameters).any?(&:present?)`. It returns true for `[nil, {...}]` and false for `[nil, [], {}]`, as expected.

2021-11-02 13:44 UTC, jswk commented on app/models/offer.rb
> +  end
Do you use this method anywhere? It seems to me that it's unused and could be removed.

2021-11-02 13:44 UTC, jswk commented on app/models/project_item/customization.rb
> +      if offer.present? && offer.bundle?
Wouldn't `if offer&.bundle?` be better?

2021-11-02 13:44 UTC, jswk commented on app/models/project_item/customization.rb
> +                                                                                          .reject { |o, _| o == offer }
I would be more explicit here and transform it to an expanded `if`, i.e.
```ruby
if self.bundled_parameters.present?
  self.bundled_parameters.transform_keys { |offer| offer.instance_of?(Offer) ? offer : Offer.find(offer) }
else
  offer_values.attributes_map.reject { |o, _| o == offer }
end
```

Current formatting is really difficult to follow.

2021-11-02 13:44 UTC, jswk commented on app/models/project_item/project_validation.rb
> +    properties? || offer.present? && (offer.bundle? || offer.source_offer_links.count.positive?)
Add parens to make logic more explicit.
```ruby
    properties? || (offer.present? && (offer.bundle? || offer.source_offer_links.count.positive?))
```
At least that is what I think you had on your mind.

Otherwise you rely on priorities between `||` and `&&`, which are non-trivial to follow at times.

2021-11-02 13:44 UTC, jswk commented on spec/factories/customizable_project_items.rb
> +    end
This seems to be unused, good for pruning.

2021-11-02 13:49 UTC, Marcelinna commented
Steps to reproduce
1. Order bundle offer where no parameters
![image](https://user-images.githubusercontent.com/59872096/139859753-37c47bf6-a819-47d5-85d7-a628331f16a7.png)
2. Click button "Next final details"
3. See error - page is blank

2021-11-02 13:59 UTC, Marcelinna commented
I can order bundle
![image](https://user-images.githubusercontent.com/59872096/139861124-889aaf1b-ce43-4fa1-827c-1b0d022d3d5b.png)

I can't order bundle
![image](https://user-images.githubusercontent.com/59872096/139861628-1f8a9f99-4e4f-4165-a557-26413d8839ac.png)
![image](https://user-images.githubusercontent.com/59872096/139861657-7197001d-ba26-439b-8026-0b690a6db377.png)

2021-11-02 14:05 UTC, Marcelinna commented
changelog?

2021-11-02 17:00 UTC, goreck888 commented on app/models/offer.rb
> +    bundle? && (parameters.present? || bundled_offers.map(&:parameters).present?)
Ok

2021-11-02 17:12 UTC, goreck888 commented on spec/factories/customizable_project_items.rb
> +    end
Ok

2021-11-02 17:27 UTC, goreck888 commented on app/models/project_item/project_validation.rb
> +    properties? || offer.present? && (offer.bundle? || offer.source_offer_links.count.positive?)
Done

2021-11-03 07:41 UTC, Marcelinna commented
the current ordering logic. 
1. User can add to the project only once an offer that has no parameters
2. User can add an offer with parameters to the project many times
3. A bundle offer can be added many times to a project, whether it has parameters or not

4. An offer that belongs to the bundle can be added to the project many times, whether it has parameters or not (
    B2DROP -For Premium)
5. When in project user has a Bundle offer (EGI Notebook+B2DROP) adding second offer EGI Notebook without parameters isn't possible.
6. When in project user has a Bundle offer (EGI Notebook+B2DROP) adding second offer B2DROP without parameters isn't possible.

2021-11-03 09:13 UTC, jswk requested changes
Thanks for resolving most problems. There's two things to consider though introduced in the meantime. Have a look at these.

2021-11-03 09:13 UTC, jswk commented on app/views/projects/services/_project_item.html.haml
> +        = link_to _("Visit website"), webpage(project_item)
Wouldn't you need to enclose the other branches of this if in `<span>` too?

2021-11-03 10:09 UTC, kmarszalek commented on app/models/offer.rb
> +  def bundle_has_parameters?
bundle_parameters?

2021-11-03 10:16 UTC, kmarszalek requested changes
almost good

2021-11-03 11:55 UTC, goreck888 commented on app/services/project_item/create.rb
> +          bundled_parameters = @bundle_params.present? && @bundle_params&.has_key?(offer.id) ?
Unfortunately it doesn't work. If `@bundle_params` is an empty Array it calls method `has_key?` and returns `NoMethodError`. Safe navigator `&.` protects only from calling a method on `nil`. So the `@bundled_params.present?` is necessary to return `false` in case of empty array and don't call `has_key?` method.

2021-11-03 12:03 UTC, jswk commented on app/services/project_item/create.rb
> +          bundled_parameters = @bundle_params.present? && @bundle_params&.has_key?(offer.id) ?
Right, then you can still get errors here, if the array has any element.
I'd suggest then to check if `@bundle_params` responds to `:has_key?`. Then you are safer than currently.

The condition would be then: `@bundle_params&.respond_to?(:has_key?) && @bundle_params.has_key?(offer.id)`.
You would only need the safe `&.` in the first part.

2021-11-04 08:03 UTC, kmarszalek commented on app/views/projects/services/_project_item.html.haml
> +      %span
still here?

2021-11-04 09:15 UTC, goreck888 commented on app/views/projects/services/_project_item.html.haml
> +      %span
No :)

2021-11-04 09:55 UTC, jswk approved these changes

2021-11-04 10:24 UTC, kmarszalek reviewed
wait for Marecelina

2021-11-04 10:24 UTC, kmarszalek approved these changes
wait for Marecelina

2021-11-04 10:38 UTC, Marcelinna approved these changes

2021-11-05 09:02 UTC, merged