[#2371] Handle provider deletion in JMS
cyfronet-fid/marketplace pull request #2384
Opened 2021-11-08 12:30 UTC by goreck888

Add possibility to delete a provider via JMS
Closes #2371

2021-11-08 13:08 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/140747345-86de4caf-4d3b-4850-831e-429fe8e92fd3.png)

2021-11-08 13:28 UTC, kmarszalek requested changes
also i would include changelog :)

2021-11-08 13:28 UTC, kmarszalek commented on app/jobs/provider/delete_job.rb
> +    Provider::Destroy.new(provider).call
since Provider::Destroy doesn't call destroy, maybe it should be renamed to Provider::Delete and then do like Service. 
```
Provider::Delete.new(service_id).call
```

2021-11-08 13:31 UTC, kmarszalek commented
is ES aware of deleting the provider via JMS?

2021-11-08 13:35 UTC, jswk commented on app/jobs/provider/delete_job.rb
> +    Provider::Destroy.new(provider).call
It's probably called in `app/services/provider/destroy.rb`, but verify it's actually the case.

2021-11-08 13:36 UTC, jswk commented on app/services/jms/manage_message.rb
>        end
Unnecessarily nested if, instead do:
```ruby
elsif resource["providerBundle"]["active"]
  Provider::PcCreateOrUpdateJob.perform_later(resource["providerBundle"]["provider"], modified_at)
end
```

2021-11-08 13:37 UTC, jswk commented
> is ES aware of deleting the provider via JMS?

It's likely done in `app/services/provider/destroy.rb`, but verify it's actually the case.

2021-11-08 13:51 UTC, Marcelinna commented
changelog?

2021-11-08 21:11 UTC, goreck888 commented on app/services/jms/manage_message.rb
>        end
Done

2021-11-08 21:12 UTC, goreck888 commented on app/jobs/provider/delete_job.rb
> +    Provider::Destroy.new(provider).call
Done

2021-11-09 07:54 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce
1. Go to PC create a new provider with resource - resource is visible in MP
2. Delete Provider in PC
3. See error - Provider isn't deleted, resource isn't go to deleted status

2021-11-09 08:28 UTC, jswk commented on app/services/importers/provider.rb
> +      status: "published"
Better use enum in that case, i.e. `status: :published`.

2021-11-09 12:58 UTC, Marcelinna approved these changes

2021-11-09 13:18 UTC, jswk approved these changes

2021-11-09 13:22 UTC, kmarszalek approved these changes

2021-11-09 13:55 UTC, merged