[#2265] Store resource's parameters from a form
cyfronet-fid/marketplace pull request #2396
Opened 2021-11-09 16:25 UTC by goreck888

Clear session after go back to the
edit form from a preview mode.
Stored session data caused overwriting
data edited after go back to the form
Fixes #2265

2021-11-10 08:07 UTC, jswk commented on CHANGELOG.md
> +- Store resource parameters from an edit form instead of parameters stored in preview mode (@goreck888)
Move it to a section for `3.26.0-milestone`, as we already branched `3.25.x` from master.
Use the template from https://docs.cyfronet.pl/display/FID/Github#Github-Changelog.

2021-11-10 08:39 UTC, jswk requested changes

2021-11-10 08:39 UTC, jswk commented on app/controllers/backoffice/services_controller.rb
> +    def clear_session
Analogously to `store_in_session!`, it would be better to name it `clear_session!`, with the trailing exclamation mark. Better conveying that it modifies the state.

2021-11-10 12:10 UTC, jswk approved these changes

2021-11-10 13:56 UTC, kmarszalek approved these changes

2021-11-16 12:37 UTC, Marcelinna commented
Steps to reproduce

1. Go to /backoffice/services/new
2. Fill form, add logo in correct format
3. Click button "Preview"
![image](https://user-images.githubusercontent.com/59872096/141986493-0b413fb1-d94f-4933-b8c0-f1e0c01341ea.png)
4. Click button "Go back to the edit"
5. Click create resource
6. See problem - the logo has disappeared

![image](https://user-images.githubusercontent.com/59872096/141986372-fb9689dd-0a65-4db3-b5ca-bffece6aa47e.png)

2021-11-18 13:46 UTC, Marcelinna approved these changes

2021-11-18 14:10 UTC, merged