[#2386] Improve review functionality
cyfronet-fid/marketplace pull request #2403
Opened 2021-11-15 12:50 UTC by goreck888

Change rating minimum value from 0 to 1
Saved clicked value of rating
after wrong validation is visible now
by page reload
Closes #2386

2021-11-15 13:15 UTC, jswk requested changes

2021-11-15 13:15 UTC, jswk commented on app/views/projects/services/opinions/new.haml
> +    .col-md-12{ data: { controller: "stars" } }
Move `data-controller` attribute back where it was. Currently only the service_rating can be modified, even when I click on the order_rating stars.
It makes submitting a review impossible, since now you introduce validation.

2021-11-15 14:50 UTC, jswk approved these changes

2021-11-15 14:54 UTC, kmarszalek approved these changes

2021-11-17 10:45 UTC, Marcelinna commented
I wait for changes in css
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/461056259_Review_Form_V2_Error_Handler
https://projects.invisionapp.com/share/JXOZKC8WMDU#/screens/461041194_Review_Form_V2

2021-11-18 13:15 UTC, Marcelinna approved these changes

2021-11-18 15:39 UTC, merged