[#2066] Fix logic of adding offers to a project
cyfronet-fid/marketplace pull request #2413
Opened 2021-11-17 14:37 UTC by kmarszalek

Open_access offer can be added only once.
Order_required offer and Bundled offer
that consist of open_access can be added multiple times.

2021-11-17 14:48 UTC, jswk commented
> **Fix** logic of adding offers to a project

How about simplify? It's actually about clearing up the logic there.

2021-11-18 11:29 UTC, Marcelinna commented
I can add many time the same offer open access 
![image](https://user-images.githubusercontent.com/59872096/142407315-9879c7fb-c9dc-4620-94fe-364266e00a03.png)

2021-11-18 12:35 UTC, jswk requested changes

2021-11-18 12:35 UTC, jswk commented on spec/factories/services.rb
> +    factory :other do
=> `other_service`

2021-11-18 12:35 UTC, jswk commented on spec/factories/services.rb
> +    factory :order_required do
=> `order_required_service`

2021-11-18 13:41 UTC, jswk approved these changes

2021-11-18 16:09 UTC, Marcelinna commented
Steps to reproduce:
1. Go to /services
2. Choose B2FIND
![image](https://user-images.githubusercontent.com/59872096/142452349-edc434bf-d2db-4311-adac-04020baee212.png)
3. Order the first offer
4. Order the second offer - "Project already pinned with this offer" error message is displayed

Expected result: second offer should be ordered properly

2021-11-19 12:06 UTC, Marcelinna commented
Tests: 

1. Add offer open access
2. Add offer full open access
3. Add offer other
4. Add order required internal
5. Add order required external
6. Try to add second time the same offer open acccess 
7. Try to add second time the same offer full open acccess 
8. Add second time the same offer order required internal
9. Try to add second time the same offer order required external
10. Try to add second time the same offer other
11. Try add offer open access and order required internal from the same service
12. Try add offer order required and open access from the same service
13. Try add two open access offer from the same services
14. Try add two order required internal offer from the same services

2021-11-19 16:25 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce

1. Add to project service open access
2. Try add the same service open access to the same project
3. See error - user is redirected to previous step
![image](https://user-images.githubusercontent.com/59872096/142656967-fe38d6d8-0004-4ac5-bfe2-98191e374f61.png)

2021-11-22 14:23 UTC, jswk approved these changes

2021-11-22 15:24 UTC, Marcelinna approved these changes

2021-11-22 15:29 UTC, merged