Run default rubocop
cyfronet-fid/marketplace pull request #2450
Opened 2021-12-09 09:03 UTC by danielkryska

Turing on rubocop in rubymine:
https://www.jetbrains.com/help/ruby/rubocop.html#disable_rubocop

2021-12-16 08:16 UTC, kmarszalek commented on app/components/conversations/message_box_component.rb
> +    project = if @message.messageable_type == "Project"
do you know which rule changed this code?

2021-12-16 09:36 UTC, jswk reviewed
Running `rbprettier --write .` changes a number of files, for starters:
![image](https://user-images.githubusercontent.com/583197/146342305-bf92c8f7-462a-4d8a-932c-8e86e2863268.png)

I would also remove the scripts (`pre-commit-prettier-*`) from root, as we should check all the files in the pre-commit. Otherwise no files will be cheked in CI.

2021-12-16 09:36 UTC, jswk commented on .github/workflows/styles.yml
> +        bundle exec overcommit --sign && bundle exec overcommit --sign pre-commit
I would verify this is necessary

2021-12-16 09:36 UTC, jswk commented on .rubocop.yml
> +  prettier: rubocop.yml
If you do:
```yml
inherit_gem:
  prettier: rubocop.yml
  rubocop-rails_config:
    - config/rails.yml
```
then you don't have to add all the exclusions at the end of the file. Only the cyclomatic complexity exclude for `'app/services/project_item/create.rb'`.

2021-12-17 08:10 UTC, danielkryska commented
Automatic check issue, that can't be reproduced manually (skipped temporarily):

```
scenario "sorting will set query param and preserve existing ones", js: true do
      create(:service, name: "DDDD Something 1", rating: 4.1)
      create(:service, name: "DDDD Something 2", rating: 4.0)
      create(:service, name: "DDDD Something 3", rating: 3.9)

      visit services_path(q: "DDDD Something", sort: "rating")

      expect(page).to have_text("by rate 1-5")
      expect(page).to have_select("sort", selected: "by rate 1-5")
      expect(page).to_not have_select("sort", selected: "by rate 5-1")
    end
```

2021-12-17 13:47 UTC, jswk requested changes
Much easier to check thanks to splitting into commits!

2021-12-17 13:47 UTC, jswk commented on app/policies/service_context_policy.rb
>      record.published? || record.unverified? || record.errored?
Since it seems the intention was for the following methods to be private (but they weren't...), please actually make them private, i.e.
```ruby
    private_class_method def self.has_public_access(record)
      record.published? ||
        record.unverified? ||
        record.errored?
    end

    private_class_method def self.has_additional_access(user, record)
      if user.blank?
        return false
      end

      user.service_portfolio_manager? ||
        record.owned_by?(user) ||
        record.administered_by?(user)
    end
```

2021-12-17 13:47 UTC, jswk commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 20_211_116_143_044) do
The `db/schema.rb` file should be ignored as it's autogenerated.

When removing the rails rubocop config, you should include some of the excludes from it anyway. See https://github.com/toshimaru/rubocop-rails_config/blob/main/config/rails.yml#L12 for source.
I would propagate the following excludes:
```yml
AllCops:
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
```

2021-12-17 13:49 UTC, jswk commented on app/helpers/image_helper.rb
>      file_name = file_path.split("/")[-1]
Also a problem with class_private here.

2021-12-17 13:50 UTC, jswk commented on app/models/project_item/wizard.rb
>      include ActiveModel::Model
Also a problem with class_private here, but I don't know if there's a way to make nested classes private this way.

2021-12-20 09:52 UTC, danielkryska commented on app/controllers/concerns/service/searchable.rb
> +    result.to_h.transform_keys { |s| s.id }
turn off and add a comment to the hash rule in .rubocop.yml file

2021-12-20 10:30 UTC, danielkryska commented on app/controllers/concerns/service/searchable.rb
> -          h
to @danielkryska: is the returning value influence anything?

2021-12-20 10:30 UTC, danielkryska commented on app/controllers/tour_feedbacks_controller.rb
> +          .collect { |question| [question["name"], "This field is required"] }.to_h
to @danielkryska: refactor/update hash change

2021-12-20 10:30 UTC, danielkryska commented on app/controllers/users/auth_mock_controller.rb
> +    encrypted_password = ::BCrypt::Password.create("#{params[:password]}nil", cost: 11).to_s
to @danielkryska: update this line of code and check rue providing this change

2021-12-20 10:30 UTC, danielkryska commented on app/helpers/scientific_domains_helper.rb
> +      .each_with_object({}) do |record, acc|
check if it works correctly

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute.rb
> +               end
check rule providing change and turn it off

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute.rb
> +    attr = case json["type"]
check rule providing change and turn it off

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute.rb
> -  protected
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute/date.rb
> -  protected
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute/input.rb
> -  protected
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute/multiselect.rb
> +    @value = case @value_type
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute/range.rb
> +               end
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute/range.rb
> -  protected
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute/range_property.rb
> -  protected
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/attribute/select.rb
> +        begin
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on app/models/filter.rb
> +  def initialize(field_name:, type:, title:, index:, params: {})
check if code is working correctly

2021-12-20 10:30 UTC, danielkryska commented on app/models/jira/checker.rb
> +          raise CheckerWarning, "Webhook \"#{wh.name}\" does not define proper \"Issue related events\" - required: " +
check rule providing change and turn it off, refactor

2021-12-20 10:30 UTC, danielkryska commented on config/initializers/split.rb
> +  config.persistence_cookie_length = 2_592_000 # 30 days
turn off rule changing numbers formatting

2021-12-20 11:14 UTC, danielkryska commented on app/components/conversations/message_box_component.rb
> +    project = if @message.messageable_type == "Project"
Rules providing changes:|
- Lint/UselessAccessModifier: Useless private access modifier
- Lint/IneffectiveAccessModifier: private (on line 27) does not make singleton methods private. Use private_class_method or private inside a class << self block instead

2021-12-20 13:47 UTC, jswk commented on app/policies/service_context_policy.rb
>      record.published? || record.unverified? || record.errored?
Okay, so you chose to ignore the rubocop suggestions.
This makes sense too, we will turn these cops on one a time in future and correct it.

2021-12-20 13:47 UTC, jswk commented on app/helpers/image_helper.rb
>      file_name = file_path.split("/")[-1]
Okay, so you chose to ignore the rubocop suggestions.
This makes sense too, we will turn these cops on one a time in future and correct it.

2021-12-20 13:47 UTC, jswk commented on app/models/project_item/wizard.rb
>      include ActiveModel::Model
Okay, so you chose to ignore the rubocop suggestions.
This makes sense too, we will turn these cops on one a time in future and correct it.

2021-12-20 13:54 UTC, jswk reviewed
This looks good now. I would just move the `.rubocop` changes to the first PR commit and generate all the changes from scratch.
In current commits you have for example missed the `protected` keyword from `app/models/attribute/quantity_price.rb`, running the formatters again would just ignore these.

I would also split the changes into four commits within this PR:
1. configuration changes etc. (the same as the current first commit)
2. prettier changes (the same as the current second commit)
3. automatic rubocop fixes (incorporating necessary prettier runs)
4. manual rubocop fixes (incorporating necessary prettier runs)

2021-12-20 13:57 UTC, jswk commented on Gemfile
> +gem "rails", "6.1.4.1"
And I would still disable this, i.e. turn off the `Bundler/OrderedGems` cop.
It will scramble Gemfile history otherwise.

2021-12-21 07:42 UTC, kmarszalek commented on app/models/attribute/quantity_price.rb
> +
it will take time to remember this rule. luckily, it's automatic.

2021-12-21 08:22 UTC, jswk approved these changes

2021-12-21 08:25 UTC, Marcelinna approved these changes

2021-12-21 08:32 UTC, kmarszalek approved these changes

2021-12-21 08:58 UTC, merged