Add delete test for providers
cyfronet-fid/marketplace pull request #2451
Opened 2021-12-09 11:26 UTC by Marcelinna

2021-12-14 12:52 UTC, jswk requested changes

2021-12-14 12:52 UTC, jswk commented on test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
> +  it("should deleted provider with resource with deleted status", () => {
Shouldn't it read `should delete provider...`? The current grammar is incorrect.
I would correct it in the tests below too.

2021-12-14 12:52 UTC, jswk commented on test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
>      cy.contains("div.invalid-feedback", "Webpage url is not a valid URL")
In these two tests you verify the validation works for logo and other fields. However, you pass both incorrect logo and other fields to `fillFormCreateResource` in both cases. I would either pass only the incorrect field(s) for each case, or verify both the other fields and the logo in a single test.

2021-12-14 13:36 UTC, Marcelinna commented on test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
>      cy.contains("div.invalid-feedback", "Webpage url is not a valid URL")
I can't directly verify the other fields and the logo in a single test, because there is a bug in the application. 
I want to rewrite the previous test for Preview mode because it fails too often.

2021-12-14 13:44 UTC, jswk commented on test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
>      cy.contains("div.invalid-feedback", "Webpage url is not a valid URL")
Okay, makes sense!

2021-12-14 13:44 UTC, jswk approved these changes

2021-12-15 08:26 UTC, kmarszalek approved these changes

2021-12-15 08:30 UTC, merged