Rubocop rules extension 2
cyfronet-fid/marketplace pull request #2467
Opened 2021-12-22 07:45 UTC by danielkryska

2021-12-23 08:17 UTC, danielkryska commented on app/controllers/concerns/service/recommendable.rb
> -      3
By default services size is 3

2021-12-23 09:26 UTC, michal-szostak approved these changes

2021-12-23 09:40 UTC, jswk commented on app/controllers/concerns/service/recommendable.rb
> -      3
I guess OK, although having explicit values for test versions is a nice thing.
I would consider going for the following, which neither triggers Rubocop nor removes the explicit values for test versions:
```ruby
  def get_services_size_by(ab_test_version)
    { "v1": 3, "v2": 2 }[ab_test_version] || 3
  end
```

2021-12-23 10:08 UTC, jswk commented on app/views/providers/details/_object.html.haml
> +- Array(provider.send(clazz)).map.with_index do |object, _idx|
```ruby
Array(provider.send(clazz)).map do |object|
```

2021-12-23 10:08 UTC, jswk commented on app/views/providers/sidebar/_object.html.haml
> +  - Array(provider.send(clazz)).map.with_index do |object, _idx|
```ruby
Array(provider.send(clazz)).map do |object|
```

2021-12-23 10:09 UTC, jswk commented on app/views/services/details/_object.html.haml
> +- Array(service.send(clazz)).map.with_index do |object, _idx|
```ruby
Array(service.send(clazz)).map do |object|
```

2021-12-23 10:11 UTC, jswk commented on app/views/services/_active_filters.html.haml
> +    - if !params[:q].blank?
```ruby
if params[:q].present?
```

2021-12-23 10:13 UTC, jswk commented on config/initializers/rswag-ui.rb
> -
Why remove this?

2021-12-23 10:15 UTC, jswk commented on spec/requests/api/v1/omses/messages_controller_spec.rb
>          let(:message_payload) {}
Couldn't these be just removed?

2021-12-23 10:32 UTC, Marcelinna requested changes
PR errored resource
![image](https://user-images.githubusercontent.com/59872096/147227787-64d65980-31c2-4d92-8d65-72c86ca1ccb2.png)
Beta
![image](https://user-images.githubusercontent.com/59872096/147227815-59ff49d5-bbc9-423b-9eb1-3b09c7031ece.png)

2021-12-23 10:35 UTC, danielkryska commented on spec/requests/api/v1/omses/messages_controller_spec.rb
>          let(:message_payload) {}
missing param cause error:

```
NoMethodError: undefined method `message_payload' for #<RSpec::ExampleGroups::ApiV1OMSesMessagesController::ApiV1OmsOmsIdMessages::Post::UserNotRecognized "returns a 401 response" (/home/eland/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/example_group_helpers.rb:97)>

  0) Api::V1::OMSes::MessagesController /api/v1/oms/{oms_id}/messages post user not recognized returns a 401 response
     Failure/Error: super

     NoMethodError:
       undefined method `message_payload' for #<RSpec::ExampleGroups::ApiV1OMSesMessagesController::ApiV1OmsOmsIdMessages::Post::UserNotRecognized "returns a 401 response" (/home/eland/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rswag-specs-2.4.0/lib/rswag/specs/example_group_helpers.rb:97)>
     # <internal:kernel>:90:in `tap'
     # -e:1:in `<main>'

2021-12-23 10:40 UTC, jswk commented on spec/requests/api/v1/omses/messages_controller_spec.rb
>          let(:message_payload) {}
Aah, ok. I assumed it's being defined somewhere above.
So maybe:
```ruby
        let(:message_payload) { nil }
```
The block isn't empty then.

2021-12-23 10:46 UTC, Marcelinna commented on app/views/services/_errors.html.haml
> +              "Reason: #{service.sources.first.errored}")
.

2021-12-23 10:48 UTC, danielkryska commented on app/controllers/concerns/service/recommendable.rb
> -      3
done :)

2021-12-23 10:51 UTC, jswk commented on app/views/services/_active_filters.html.haml
> +    - if params[:q]&.present?
Ok, but the safe navigation `&.` is unnecessary.
```
pry(main)> {}[:c].present?
=> false
```

2021-12-23 11:05 UTC, danielkryska commented on app/views/services/_active_filters.html.haml
> +    - if params[:q]&.present?
done

2021-12-23 11:06 UTC, jswk approved these changes

2021-12-23 11:28 UTC, danielkryska commented on spec/requests/api/v1/omses/messages_controller_spec.rb
>          let(:message_payload) {}
done

2021-12-27 09:58 UTC, Marcelinna commented on app/views/services/configurations/attributes/_multiselect.html.haml
>      collection: attr.config["values"].map { |e| ["#{e} #{attr.unit}", e] },
id: "parameter_#{attr.id}", it is not necessary?

2021-12-27 10:05 UTC, Marcelinna commented on config/environments/production.rb
>    # SMTP settings
it is ok?

2021-12-27 10:27 UTC, jswk commented on app/views/services/configurations/attributes/_multiselect.html.haml
>      collection: attr.config["values"].map { |e| ["#{e} #{attr.unit}", e] },
I'll have a look, although it seems that apart from a few places setting the `id` on configuration attributes adds more problems than profit (checkbox and select labels don't work as expected then).

2021-12-27 10:43 UTC, jswk commented on config/environments/production.rb
>    # SMTP settings
Yeah, it's equivalent, though not enforced by linter formatter anyway. I will scrap this one in the next push.

2021-12-27 10:45 UTC, jswk commented on app/views/services/_errors.html.haml
> +              "Reason: #{service.sources.first.errored}")
It should work now, please resolve if handled properly now.

2021-12-27 10:46 UTC, jswk commented on app/views/services/configurations/attributes/_multiselect.html.haml
>      collection: attr.config["values"].map { |e| ["#{e} #{attr.unit}", e] },
Ok, `id`s in most of the attributes weren't necessary. I've stripped them altogether. Have a look.

2021-12-27 12:00 UTC, Marcelinna commented
When I fill field Hosting legal entity in Provider creation form
pr
![image](https://user-images.githubusercontent.com/59872096/147469702-b447db51-c10f-4a12-bba1-b6b5505a2abd.png)
![image](https://user-images.githubusercontent.com/59872096/147469826-71a37ed3-0296-4255-b4eb-3d38ae39bae5.png)
beta
![image](https://user-images.githubusercontent.com/59872096/147469795-eda8c63c-5f86-4805-947e-f9699bbec7be.png)

2021-12-27 16:05 UTC, Marcelinna approved these changes

2021-12-27 16:48 UTC, merged