Rubocop rules extension 3
cyfronet-fid/marketplace pull request #2470
Opened 2021-12-23 13:14 UTC by danielkryska

2021-12-29 12:25 UTC, Marcelinna commented on app/helpers/image_helper.rb
>      tmp_logo = Tempfile.new(["logo_temp", ext])
changes in  app/helpers/image_helper.rb looks fine? 
On PR is a problem with the image, so it is hard to check it.

2021-12-29 12:31 UTC, jswk commented on app/helpers/image_helper.rb
>      tmp_logo = Tempfile.new(["logo_temp", ext])
Yes, they're fine. There were several affected tests in `spec/lib/import/resources_spec.rb`, which traced the modified code paths and are now corrected.

2021-12-29 13:49 UTC, kmarszalek commented on app/controllers/favourites/services_controller.rb
> +    UserService.where(user: current_user).size > 1 || (cookies[:favourites]&.size || 0) > 1
brackets

2021-12-29 13:54 UTC, kmarszalek commented on app/helpers/scientific_domains_helper.rb
> -    if !values.empty?
unless [']

2021-12-29 14:10 UTC, kmarszalek requested changes
git. git pl
squash smth, after Marcelinas approval and add brackets.

2021-12-29 14:59 UTC, Marcelinna approved these changes

2021-12-30 12:24 UTC, kmarszalek approved these changes

2021-12-30 12:24 UTC, merged