[#2446] Fix updating resources with invalid providers
cyfronet-fid/marketplace pull request #2474
Opened 2021-12-30 13:16 UTC by goreck888

This PR fixes adding providers to the resource
even if chosen provider has improper data
Fixes #2446

2021-12-30 16:05 UTC, jswk requested changes
Correct one test and strip the other as described. Otherwise it's good to go.

2021-12-30 16:05 UTC, jswk commented on spec/features/backoffice/services_spec.rb
> +    end
Actually, when updating through `record.update(params)` as is done in `backoffice/services_controller.rb`, the failing validation doesn't stop saving. So this test is unnecessary - it also doesn't fail when the `validate: false` is removed.
I would remove it.

2021-12-30 16:05 UTC, jswk commented
Aah, and rebase onto the new master.

2021-12-31 09:33 UTC, goreck888 commented on spec/features/backoffice/services_spec.rb
> +    end
Ok.

2021-12-31 10:20 UTC, jswk approved these changes

2022-01-03 09:58 UTC, Marcelinna commented on app/controllers/backoffice/services_controller.rb
>        render :edit, status: :bad_request
You can change to "New service created successfully"

2022-01-03 10:43 UTC, Marcelinna approved these changes

2022-01-03 10:49 UTC, goreck888 commented on app/controllers/backoffice/services_controller.rb
>        render :edit, status: :bad_request
Done

2022-01-03 10:54 UTC, kmarszalek approved these changes

2022-01-03 11:11 UTC, merged