[#2446] Add missing text improvements and tests
cyfronet-fid/marketplace pull request #2475
Opened 2022-01-03 11:17 UTC by goreck888

2022-01-03 11:37 UTC, jswk reviewed
In general ok, although I would go through messages in the entire project looking for "services".
For example: there's another instance of "service" in `app/controllers/backoffice/services_controller.rb`. Maybe it's all, but I would grep the project nonetheless.

2022-01-03 11:40 UTC, jswk commented
Have a look in particular at the files in `config/locales`. We have some instances of "service" there too.

2022-01-03 11:44 UTC, Marcelinna commented
changelog?

2022-01-03 12:01 UTC, Marcelinna commented
It nice to change message "Service ordered successfully" in app/controllers/services/summaries_controller.rb, depending on the type of offer. 

"Offer ordered successfully" - order required internal
"Offer pinned successfully" other

2022-01-04 08:49 UTC, jswk requested changes
Please also update the commit message, as it seems to have been copied from the current master's HEAD.

2022-01-04 08:49 UTC, jswk commented on config/locales/simple_form.en.yml
> +          We will send your report to our customer resource.
This should stay "customer service". It's not about services/resources in the meaning of Resource Profile.

2022-01-04 09:07 UTC, goreck888 commented on config/locales/simple_form.en.yml
> +          We will send your report to our customer resource.
Sorry, I remember that text and i had to click a wrong button, thanks!

2022-01-04 09:38 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/148039227-7e1aae1f-1644-46d2-82ad-8c9b98d97119.png)
here, we should change to Resource?

2022-01-04 09:45 UTC, Marcelinna commented
in mail notification we have service too
![image](https://user-images.githubusercontent.com/59872096/148040293-dcbdad7f-eed3-4bbf-8bc4-b1f32bf40898.png)

2022-01-04 10:41 UTC, jswk commented
The commit message is still wrong.

Please also correct the inconsistencies in [emails](https://github.com/cyfronet-fid/marketplace/pull/2475#issuecomment-1004661167) and [profile](https://github.com/cyfronet-fid/marketplace/pull/2475#issuecomment-1004656043) identified by @Marcelinna.

2022-01-04 10:48 UTC, jswk requested changes
Push to 462ee85ee7b8e373cdd8455dcd44e0390451db87 handled the profile text, yet not all text in emails is corrected. Go through all the email texts and subjects to catch them all.

2022-01-04 12:05 UTC, jswk requested changes
Please correct failing tests.

2022-01-04 12:57 UTC, Marcelinna approved these changes

2022-01-04 13:51 UTC, jswk approved these changes

2022-01-04 13:51 UTC, merged