[#2445] Provider draft status
cyfronet-fid/marketplace pull request #2477
Opened 2022-01-03 12:48 UTC by kmarszalek

Closes #2445

2022-01-04 10:15 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/148043762-2dd79902-5913-4ce9-a74c-151b26f6fe48.png)
![image](https://user-images.githubusercontent.com/59872096/148043801-1607d5dc-b334-432a-b6c6-ec38c2bf49c0.png)

make sure that  provider with status draft aren't shown in this summary

2022-01-05 07:59 UTC, kmarszalek commented on CHANGELOG.md
> +- Fix redirect from MP to Resource dashboard in PC (@kmarszalek)
will delete this line after successful github tests

2022-01-05 11:21 UTC, jswk requested changes

2022-01-05 11:21 UTC, jswk commented on app/models/provider.rb
> +  STATUSES = { published: "published", deleted: "deleted", draft: "draft" }.freeze
Maybe change the order to better map provider's lifecycle?
```ruby
   STATUSES = { draft: "draft", published: "published", deleted: "deleted" }.freeze
```

2022-01-05 11:21 UTC, jswk commented on spec/services/provider/pc_create_or_update_spec.rb
> +        true,
Please create an analogous test for `active: false`.

2022-01-05 11:34 UTC, jswk approved these changes

2022-01-05 11:59 UTC, Marcelinna approved these changes

2022-01-05 12:11 UTC, merged