[#2266] Fix Reource reviews counters
cyfronet-fid/marketplace pull request #2479
Opened 2022-01-03 14:28 UTC by goreck888

Add rake task for fixing opinions counters
Fix singularization when a resource has 1 review
Closes #2266

2022-01-03 14:44 UTC, jswk commented on app/views/services/_header.html.haml
> +              "data-target": local_assigns[:preview] ? "preview.link" : ""
There's an analogous case in `backoffice/services/_header` to fix.

2022-01-03 14:44 UTC, jswk commented on app/views/services/_header.html.haml
> +              "data-target": local_assigns[:preview] ? "preview.link" : ""
And in ordering_configurations

2022-01-03 14:46 UTC, jswk commented on app/views/services/_header.html.haml
> +              "data-target": local_assigns[:preview] ? "preview.link" : ""
I would move generating this text to a helper, since it satisfies the https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming) already.

2022-01-03 14:48 UTC, jswk reviewed
About the task itself, I would not add this corrective step as a task. I would just pass the script to run to @wziajka directly, as it was done in such occasions recently for such fire-once corrections.

2022-01-04 13:17 UTC, goreck888 commented on app/views/services/_header.html.haml
> +              "data-target": local_assigns[:preview] ? "preview.link" : ""
Done.

2022-01-05 09:26 UTC, Marcelinna approved these changes

2022-01-05 09:45 UTC, kmarszalek commented on app/helpers/service/header_helper.rb
> +    link_to "#{service.service_opinion_count} review#{service.service_opinion_count == 1 ? "" : "s"}",
via slack

2022-01-05 09:49 UTC, kmarszalek requested changes
translation or minimum: (review or reviews)

2022-01-05 10:06 UTC, kmarszalek approved these changes

2022-01-05 10:16 UTC, merged