[#2505] Fix adding parameters to the default offer
cyfronet-fid/marketplace pull request #2507
Opened 2022-01-19 12:11 UTC by goreck888

Problem caused by hidden field which is blank
when no order_type is chosen in a service.
Add default "other" order_type in this case
Fixes #2505 #2302

2022-01-19 14:04 UTC, Marcelinna commented on app/services/service/create.rb
>          status: "published",
Why change order type from open access to other help?

1. I create a new service, I didn't set "order type"
2. I see on the label that service is  "Other order type" and offer is "other" type
![image](https://user-images.githubusercontent.com/59872096/150145077-a993ce5c-4dd8-4cb1-a489-bdd86831e269.png)
3. I delete the offer - service doesnt have any offer
4. I create offer offer open access - on label I see Other order type for service, offer is open access
5. I add parameters - parameters are added

I have the same situation in bug descripton, but there adding parametres don't working.

2022-01-19 15:44 UTC, jswk commented on app/services/service/create.rb
>          status: "published",
The suggestion to make `order_type` a required field seems to make sense to me, although for some reason it wasn't marked required before. Do you know why such case was allowed? I cannot think of anything in particular, but maybe whitelabel-related stuff?

Nevertheless, I don't see any services in staging (apart from the ones created for testing) that have `order_type == nil`. Resource Profile marks this field as mandatory, so it shouldn't be a problem in the main MP instance.

-----

About falling back to `"other"` here, I would rather make the `ServiceHelper::order_type` default to `open_access` in that case. It wouldn't modify the DB population process.
Also, historically we defaulted to `"open_access"` and `"external"` there, not to `"other"` (e.g. https://github.com/cyfronet-fid/marketplace/blob/2602338d7492493b5a14cc3ebc9b53de6d657a53/app/helpers/service_helper.rb#L70 and https://github.com/cyfronet-fid/marketplace/blob/2602338d7492493b5a14cc3ebc9b53de6d657a53/app/helpers/service_helper.rb#L81).

2022-01-19 16:15 UTC, Marcelinna commented on app/services/service/create.rb
>          status: "published",
I don't know why in past order_required filed wasn't required but according to https://github.com/cyfronet-fid/marketplace/issues/1977 we should set in BO required field as are in PC. In PC order type is required, so I think we can make it required in this PR too.

2022-01-19 16:28 UTC, goreck888 commented on app/services/service/create.rb
>          status: "published",
So let's return to the `open_access` default matching and show unmarked services as an `open_access` resource

2022-01-20 08:01 UTC, Marcelinna approved these changes

2022-01-20 08:37 UTC, jswk requested changes

2022-01-20 08:37 UTC, jswk commented on app/services/service/create.rb
> +        order_type: @service.order_type || "other",
As per https://github.com/cyfronet-fid/marketplace/pull/2507#discussion_r787928143 let's not change the current handling. Will you add a default on the column, the part `|| "open_access"` should be dropped.

2022-01-20 08:37 UTC, jswk commented on app/services/service/update.rb
> +          order_type: order_type,
I don't think these are necessary when field order_type will be required in the form and have a default in DB.

2022-01-20 08:37 UTC, jswk commented on app/views/backoffice/services/offers/_one_offer_edit_form.html.haml
> +    = f.hidden_field :order_type, value: service.order_type || "other"
Same here.

2022-01-20 08:37 UTC, jswk commented on app/models/service.rb
> +  validates :order_type, presence: true
I would also add a DB constraint: `null: false, default: "open_access"` to the column, when we're at it.
I would add the default so that even if we had such records in the DB we don't have errors.

You may also add a data migration to fill the missing order_type, and only then impose the constraint.

2022-01-20 08:55 UTC, jswk commented
The two failing tests in `spec/features/backoffice/services_spec.rb` need correction too, since this PR introduces a change in validation.

2022-01-20 11:59 UTC, jswk requested changes
Why not combine both migrations? I don't see why we need two separate ones.
```ruby
class SetOrderTypeAsRequiredInService < ActiveRecord::Migration[6.1]
  def change
    exec_update "UPDATE services SET order_type = 'open_access' WHERE order_type = '' OR order_type IS NULL"
    change_column :services, :order_type, :string, null: false
  end
end
```

Actually, I'd also remove the default value, since it won't be necessary. I know I suggested it, but it only makes sense in case we wouldn't do a data migration. Now it's a no-op.

2022-01-20 11:59 UTC, jswk commented on db/schema.rb
> +
These tables were removed some time ago. Please remove them.
Don't you have some local migrations which are not checked-in to the repository that generate those records? It doesn't happen to others.

2022-01-20 12:17 UTC, jswk approved these changes

2022-01-20 12:32 UTC, goreck888 commented on db/schema.rb
> +
I had loaded anonymized production db.

2022-01-20 12:32 UTC, merged