draft providers
cyfronet-fid/marketplace pull request #2533
Opened 2022-02-09 07:10 UTC by Marcelinna

2022-02-14 14:16 UTC, jswk commented on test/system/package.json
> +    "cy:run": "TZ=Europe/Warsaw cypress run --browser chrome --headless --quiet --env grepTags='-@extendend-test'",
A typo: `extendend` should instead read `extended`. Please correct it so it doesn't propagate.

2022-02-14 14:18 UTC, jswk approved these changes
Apart from the typo in the tag it's good to go.

2022-02-15 10:02 UTC, kmarszalek approved these changes

2022-02-15 10:54 UTC, jswk requested changes
Please remove the unresolved conflicts from the first commit.

2022-02-15 10:54 UTC, jswk commented on test/system/cypress/integration/regression_tests/backoffice/providers/providers.spec.ts
> ->>>>>>> Add e2e tests for draft and created by fully form providers
Don't commit unresolved conflicts, even if they are to be removed in a subsequent commit.

2022-02-15 11:22 UTC, jswk approved these changes

2022-02-15 11:23 UTC, merged