fix(projects): fix projects notifications
cyfronet-fid/marketplace pull request #2539
Opened 2022-02-14 10:33 UTC by danielkryska

2022-02-14 11:01 UTC, Marcelinna commented
If you change all notifications for consistency, change all of them:
"Category removed" -> "Category removed successfully"
"Platform destroyed" -> "Platform removed successfully"
"Provider has been removed" -> "Provider removed successfully"
"New scientific_domain created successfully" -> "New scientific domain created successfully"
"Scientific Domain removed" -> "Scientific Domain removed successfully " 
"Service destroyed" -> "Resource removed successfully"
"#{@Vocabulary type} removed" -> "#{@Vocabulary type} removed successfully"
"New offer has been created" -> "New offer created successfully"
and maybe other

2022-02-14 11:52 UTC, jswk requested changes
Have a look at several leftover "destoyed"s:
![image](https://user-images.githubusercontent.com/583197/153859111-c6dead74-428a-4ed7-bdae-de63970849e0.png)

Just correct the commit message to conform to the repo's conventions and it seems good to go to me (with tests possing).

2022-02-14 13:54 UTC, Marcelinna commented on app/controllers/projects_controller.rb
>      end
Please change to Project removed successfully, we use word "removed" for other notification

2022-02-14 14:43 UTC, jswk commented on app/controllers/projects_controller.rb
>      end
There's also "Profile information deleted successfully" in profiles_controller.rb if we want to unify this.

2022-02-15 08:50 UTC, jswk commented on app/views/services/_paginate_simple.haml
> +          = link_to "30", params.merge(per_page: 30, page: 1), class: "page-link"
Why remove the `.permit!`?

2022-02-15 08:52 UTC, jswk requested changes
There's also still the phrase `deleted successfully` in the notices instead of `removed successfully`. Please correct these two remaining instances.

2022-02-15 09:27 UTC, danielkryska commented on app/views/services/_paginate_simple.haml
> +          = link_to "30", params.merge(per_page: 30, page: 1), class: "page-link"
`brakeman` throws errors in styles about it. After the removal of the `.permit!` flag page resources number is still working fine.

2022-02-15 09:27 UTC, danielkryska commented
> There's also still the phrase `deleted successfully` in the notices instead of `removed successfully`. Please correct these two remaining instances.

done

2022-02-15 09:42 UTC, Marcelinna approved these changes

2022-02-15 09:42 UTC, jswk commented on app/views/services/_paginate_simple.haml
> +          = link_to "30", params.merge(per_page: 30, page: 1), class: "page-link"
How does one reproduce these errors? I run `brakeman` and don't get any errors. I can see these lines being ignored in `brakeman.ignore`.

These `.permit!`s seem indeed not necessary here though. I would extract these changes to a separate commit and also update the `brakeman.ignore` in that commit then by running an interactive `brakeman -I`.

2022-02-15 09:44 UTC, jswk requested changes
Extract the unrelated `.permit!` changes to a separate commit and update `brakeman.ignore` appropriately.

2022-02-15 09:56 UTC, jswk approved these changes

2022-02-15 10:07 UTC, merged