[#1809] Unify service/provider views by the ViewComponent
cyfronet-fid/marketplace pull request #2540
Opened 2022-02-14 13:12 UTC by goreck888

Add new `view_components` for displaying unified
header, description, sidebar and details.
Unify method names
Commit with implementation of header_component,
header_links_component
Fixes https://github.com/cyfronet-fid/marketplace/issues/1809

2022-02-14 15:46 UTC, jswk requested changes
First of all, good job on refactoring all these.

I've only several suggestions in comments, they are mostly some improvement on code deduplication and nothing major.

There's also these few unaddressed comments from #1794 which should be easy to incorporate:
- https://github.com/cyfronet-fid/marketplace/pull/1794#discussion_r579142621
- https://github.com/cyfronet-fid/marketplace/pull/1794#discussion_r579145217
- https://github.com/cyfronet-fid/marketplace/pull/1794#discussion_r579178639

2022-02-14 15:46 UTC, jswk commented on app/helpers/service_helper.rb
>    def data_for_map(geographical_availabilities)
Do we still need this helper? Wouldn't the helper `data_for_map_provider`, maybe renamed to `data_for_map`, be enough?
They are duplicated 1-to-1.
See also: https://github.com/cyfronet-fid/marketplace/pull/1794#discussion_r579148705.

2022-02-14 15:46 UTC, jswk commented on app/helpers/service_helper.rb
>    def data_for_map(geographical_availabilities)
Similar situation with the two helper methods below, i.e. `data_for_region` and `any_non_european?`.
Probably both should be moved to presentable_helper? The `any_non_european?` may be made private.

2022-02-14 15:46 UTC, jswk commented on app/helpers/application_helper.rb
> +  end
I feel like this one would better fit in `app/helpers/presentable_helper.rb`.
Also, isn't it actually a `presentable_logo`?

2022-02-14 15:46 UTC, jswk commented on app/helpers/application_helper.rb
>    end
I feel like this one would better fit in `app/helpers/presentable/header_helper.rb`.
I know it's not your changes it was added in, but anyways, it's only used in the header_component.

Maybe even better, it could be incorporated into the `/app/components/presentable/header_component.rb` directly not to pollute the helpers namespace?

2022-02-14 15:46 UTC, jswk commented on app/helpers/presentable_helper.rb
>      fields.map { |f| record.send(f) }.any?(&:present?)
A short-circuiting implementation maybe:
```ruby
fields.any? { |f| record.send(f).present? }
```
It won't call `send` for every field before checking if any is present but return early.

2022-02-14 18:29 UTC, goreck888 commented on app/helpers/service_helper.rb
>    def data_for_map(geographical_availabilities)
Done.

2022-02-14 18:32 UTC, goreck888 commented on app/helpers/application_helper.rb
> +  end
Done.

2022-02-14 18:37 UTC, goreck888 commented on app/helpers/application_helper.rb
>    end
I moved it to the `HeaderHelper`, because this method is not used directly in the `HeaderComponent`, but in partials

2022-02-14 18:38 UTC, goreck888 commented on app/helpers/presentable_helper.rb
>      fields.map { |f| record.send(f) }.any?(&:present?)
Done.

2022-02-15 07:14 UTC, Marcelinna commented
beta 
![image](https://user-images.githubusercontent.com/59872096/154011066-2a873d4a-0277-431a-a2db-396ca2196765.png)
pr
![image](https://user-images.githubusercontent.com/59872096/154011135-2cd1b8e5-8f3f-418a-b1ef-26f3dcd06ec0.png)

2022-02-15 08:43 UTC, jswk approved these changes
From my side this PR looks good now.

As it's massive, I would suggest to only add the `[#1809]` tag to all commits' messages and __not squash__ prior to merging. This will make the changes more readable in the repo's history.

2022-02-15 10:34 UTC, kmarszalek approved these changes

2022-02-15 11:40 UTC, Marcelinna commented
please check the "Updates" display

beta
![image](https://user-images.githubusercontent.com/59872096/154055079-cf1caa64-9a34-44ff-919f-2aa0892f0ab1.png)
pr
![image](https://user-images.githubusercontent.com/59872096/154055118-4a3f879f-d5de-4d79-8cdf-fa1e9c1f9f44.png)

2022-02-15 11:44 UTC, Marcelinna commented
pr
![image](https://user-images.githubusercontent.com/59872096/154055456-b66c75ff-7036-4217-8164-43e5c50b8c6f.png)
beta
![image](https://user-images.githubusercontent.com/59872096/154055515-cfc975bd-2048-4a5f-a734-a300ff39e916.png)


We don't have "Add to favorite", "Add to comparison" button on the beta instance in BO
In the back office, these buttons do not work, I don't know if we should leave them?

2022-02-15 12:42 UTC, Marcelinna approved these changes

2022-02-15 13:50 UTC, merged