[#2331] Remove redundant comma in service details languages
cyfronet-fid/marketplace pull request #2551
Opened 2022-02-18 08:53 UTC by danielkryska

2022-02-18 09:25 UTC, Marcelinna commented
Please resolve second problem from isuue too
![image](https://user-images.githubusercontent.com/59872096/154655083-3393b150-f6c3-4809-bec9-3d3e486407cd.png)

2022-02-18 09:28 UTC, Marcelinna commented
> Please resolve second problem from isuue too ![image](https://user-images.githubusercontent.com/59872096/154655083-3393b150-f6c3-4809-bec9-3d3e486407cd.png)

**Go to Resource Details, see the problem - field language availability isn't filled but "Languages" is visible on details**

Languages isn't required field, if you don't fill it, should be visible in details

2022-02-18 09:50 UTC, jswk commented
> Go to Resource Details, see the problem - field language availability isn't filled but "Languages" is visible on details

I believe the whole issue arose from the fact that when editing with the multiselect input, the first element will always be `""` (empty string).
Examples is DB:
```
irb(main):008:0> Service.all.filter {|s| s.languages[0] == "" }.map {|s| [s.name, s.languages] }
=> 
[["Science Software on Demand", ["", "English"]],
 ["test", [""]],
 ["OpenAIRE Research Graph", [""]],
 ["EnviDat", ["", "English"]],
 ["test", [""]],
 ["O3as: ozone assessment", ["", "English"]],
 ["EGI Cloud Compute", ["", "English"]]]
```

Then when you render service `"test"` for example, then the field is rendered since it contains an element.
The same goes for the comma, `["", "English"].join(", ")` will give `, English`.

I'd say the way to tackle this is to make the multiselect input not create this empty string at the beginning. It would normalize the DB and make the problems outlined in the #2331 go away (it would also possibly make sense to verify we don't have such entries in the production and execute a corrective action there once this PR is deployed there).

2022-02-18 09:51 UTC, jswk commented
Last but not least, verify no other array columns are affected by this bug. If they are correct their handling either.

2022-02-18 11:12 UTC, danielkryska commented
Languages are fixed

2022-02-18 11:36 UTC, jswk requested changes
Apart from the migration which needs to be corrected, the current fix works well.

2022-02-18 11:36 UTC, jswk commented on db/migrate/20220218104738_remove_empty_strings_from_service_languages.rb
> +      end
Don't add references to code in migration, rather correct this using plain SQL.
This could lead to failures in future, when we'll want to refactor some code used here.

Alternatively, add this command to the upgrade doc to run directly in console.

2022-02-22 07:50 UTC, danielkryska commented on db/migrate/20220218104738_remove_empty_strings_from_service_languages.rb
> +      end
Done

2022-02-22 08:59 UTC, danielkryska commented
`Simple form` input param `include_hidden: false` doesn't work with an empty array.

2022-02-22 10:43 UTC, danielkryska commented
Looking for a solution I found excellent lib for our purposes:
https://github.com/holli/auto_strip_attributes

2022-02-22 11:02 UTC, Marcelinna approved these changes

2022-02-22 12:47 UTC, jswk requested changes
Please remove the unnecesary extend and it's good to go.

2022-02-22 12:47 UTC, jswk commented on app/models/service.rb
> +  extend AutoStripAttributes
This line isn't needed since all ActiveRecords will extend it anyway.

2022-02-22 12:56 UTC, jswk approved these changes

2022-02-22 12:57 UTC, merged