[HOTFIX] Fix EGI Notebooks backoffice page
cyfronet-fid/marketplace pull request #2563
Opened 2022-02-22 17:04 UTC by goreck888

Add missing direct path to the `notebook_openaire_explore`
partial. Now it's impossible to see EGI Notebooks page
in the backoffice

2022-02-23 07:05 UTC, Marcelinna commented
When I try to visit EGI Notebook in BO
![image](https://user-images.githubusercontent.com/59872096/155274548-9044d52b-e2da-4b45-b234-76065331f8e6.png)

2022-02-23 07:09 UTC, Marcelinna commented
When I visit EGI Notebook on BO
![image](https://user-images.githubusercontent.com/59872096/155274894-51d33228-0fbe-4c83-9036-3436dedf08c4.png)

2022-02-23 07:11 UTC, kmarszalek requested changes
bad PR instance for this PR, please check this out. some test?

2022-02-23 07:17 UTC, Marcelinna commented
Is there any other service with which we can have a similar problem?

2022-02-23 09:08 UTC, jswk requested changes
Please add a check for this in the `features/service_spec.rb`.

This will be enough:
![image](https://user-images.githubusercontent.com/583197/155289216-a50444bc-043d-402e-a5d6-6f22c4bd8aa7.png)
and we'll have this case covered.

**PG:** Not really, the problem was in the backoffice, so I just add similar test in the backoffice/ordering_configuration context

2022-02-23 09:17 UTC, jswk commented
> Is there any other service with which we can have a similar problem?

@Marcelinna: This error is specific to the "EGI Notebook" only, as only it has this openaire integration.

2022-02-24 09:29 UTC, Marcelinna approved these changes

2022-03-01 12:30 UTC, jswk approved these changes

2022-03-01 12:47 UTC, kmarszalek requested changes
we change the scope of this from hotfix to normal bug, change the base to master.sorry.

2022-03-01 15:53 UTC, kmarszalek approved these changes

2022-03-01 20:32 UTC, merged