[#2498] Add "engine_version" field in the body of the /recommendations request
cyfronet-fid/marketplace pull request #2565
Opened 2022-02-23 15:02 UTC by Michal-Kolomanski

closes #2498 

By using "engine_version" we can specify which algorithm should be used to serve recommendations.

Changes:
- "engine_version" in the body of the /recommendations request,
- "engine_version" parameter is set to the environmental variable: DEFAULT_RECOMMENDATION_ALG if it exists;
 otherwise, it's set to "RL".

2022-02-23 18:16 UTC, kmarszalek requested changes
env name and I would like to see the changelog entry.
this can be reported somewhere and entry may help with that. also, it affects user indirectly :)

2022-02-24 08:08 UTC, Michal-Kolomanski commented on config/application.rb
> +    config.default_recommendation_alg = ENV["DEFAULT_RECOMMENDATION_ALG"] || "RL"
You are right, however, I wanted to keep the name the same as it is in the [RS](https://github.com/cyfronet-fid/recommender-system/blob/789433d186b14d0c6048a038c4c3836fad4f08c0/README.md?plain=1#L185) (there it is indeed the default) such that Wojtek, our colleague, never has a doubt about which variable to utilize. However, because it is not the default, I will alter the name to: RECOMMENDATION_ALG.

2022-02-24 08:40 UTC, kmarszalek approved these changes

2022-02-24 09:35 UTC, Marcelinna approved these changes

2022-02-24 09:44 UTC, merged