[#2553] Fix backoffice fields validation on update
cyfronet-fid/marketplace pull request #2579
Opened 2022-03-01 11:25 UTC by danielkryska

2022-03-01 11:29 UTC, danielkryska commented
@jswk, @michal-szostak, @goreck888 let me know if I should put the solution info into the CHANGELOG.

2022-03-01 11:39 UTC, Marcelinna commented
We give a changelog if the change affects the end-user regardless of whether it is MP or BO. You should add a changelog.

2022-03-01 11:42 UTC, jswk requested changes
I would verify this new behaviour in `spec/services/service/update_spec.rb`.
In particular, check that when update fails then no Offer::Create is called.

2022-03-02 07:27 UTC, danielkryska commented
@Marcelinna I'll include the preview case in the scope of the ticket

2022-03-15 10:42 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

1. Go to /backoffice/services/new
2. Don't fill fields, click on button "Create resource"
3. See error

![image](https://user-images.githubusercontent.com/59872096/158360648-e391cb48-89e0-4325-9309-5abb90a132b8.png)

2022-03-15 11:18 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

1. Go to /backoffice/services/new
2. Click on the button "Preview" - fom is validated properly
3. Go to "Contact" section - see error "Public Contact" is duplicated

2022-03-16 08:05 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce

1. Go to /backoffice/services/new
2. Fill required field and add logo 
3. Click button "Preview"
4. See error 
![image](https://user-images.githubusercontent.com/59872096/158544324-82ed2f8e-bb94-4d27-9998-ff615f099dd1.png)

2022-03-24 06:50 UTC, Marcelinna commented
Other pr after tiring update Check-in in PC
![image](https://user-images.githubusercontent.com/59872096/159858411-7cdc94a2-71f3-4974-a151-f7f1db435757.png)
This pr after tiring update Check-in in PC - but seems that the problem with validation exist because the resource doesn't update but error message doesn't displayed
![image](https://user-images.githubusercontent.com/59872096/159858605-55d1096f-b852-4d0e-b040-a77f372fe3e0.png)

2022-03-26 06:48 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce

1. Go to /backoffice/services/new
2. Fill required field and add logo
3. Click the button "Preview"
4. Click the button "Go back to edit"
5. Click the button "Create resource"
6. See error - resource doesnt have logo

![obraz](https://user-images.githubusercontent.com/59872096/160228328-58cf0277-4e1b-4880-bf77-5468d5af46c1.png)

2022-03-26 07:10 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce

1. Go to /backoffice/services/new
2. Go to Contact section
3. Enter "test" or "test@mail.pl" to Email* for Public Contact
![obraz](https://user-images.githubusercontent.com/59872096/160228972-e65067e7-38d2-46ac-b378-a48e636ef283.png)
4. Click on button "Preview"
5. See error - Public contact is duplicated
![obraz](https://user-images.githubusercontent.com/59872096/160229008-b5770fa5-8034-4b47-9edf-5254bf944a6f.png)

2022-03-26 07:40 UTC, Marcelinna commented
Validation url:
1. https://www.example - OK
2. https://example - NOT OK

![obraz](https://user-images.githubusercontent.com/59872096/160229798-f829606c-0f69-4c3b-bd0b-8e0769bc1cba.png)
![obraz](https://user-images.githubusercontent.com/59872096/160229817-443b64ee-de7d-44b2-8e18-2549916fdc94.png)


QA: I think we have an invalid validation? Am I right? If so, this is an issue for a different PR

2022-03-29 11:52 UTC, jswk requested changes
Please have a look a the comments. Please also squash the changes into a single commit, since the "automatic fixes" also contain some logic changes anyway.

2022-03-29 11:52 UTC, jswk commented on app/services/service/create.rb
> +    Offer::Create.new(new_offer).call
Better use the mini-service convention of calling the symbol directly without an intermediate `new`, i.e. `Offer::Create.call(new_offer)`.

2022-03-29 11:52 UTC, jswk commented on app/helpers/image_helper.rb
> +    unless logo.present? && logo.original_filename&.present? && logo.path&.present? && logo.content_type&.present?
The `.present?` method is defined also for nil, so you don't need to use safe navigation to invoke them.

2022-03-29 11:52 UTC, jswk commented on app/helpers/backoffice/services_session_helper.rb
> +  SESSION_KEY = "service"
Why not retain the solution to add service's id to the session key? Are collisions impossible now for some reason?

2022-03-29 11:52 UTC, jswk commented on app/helpers/backoffice/services_session_helper.rb
> +  def store_attr!(attr)
Isn't `attr` more like `attrs`? You're attempting to iterate over it and perform collection operations.

2022-03-29 11:52 UTC, jswk commented on app/helpers/backoffice/services_session_helper.rb
> +  def store_logo!(attr)
Here you're also passing attributes here, rather than a single attribute.

2022-03-29 11:52 UTC, jswk commented on app/controllers/backoffice/services/logo_previews_controller.rb
> +    preview_session = session["service"]
Better use the constant from the helper directly

2022-03-29 11:52 UTC, jswk commented on app/helpers/backoffice/services_helper.rb
> +  end
It's only used in the backoffice/services controller. I would keep it there.

2022-03-29 11:52 UTC, jswk commented on app/helpers/backoffice/services_helper.rb
> +  ].freeze
I would keep the sort options in the controller, the same way it's done in the `app/controllers/services_controller.rb`.
Otherwise, unify the way these options are generated dynamically based on context, but I'm not sure we need such a mechanism.

2022-03-29 11:52 UTC, jswk commented on app/controllers/backoffice/services_controller.rb
> +  end
Why do it twice?

2022-03-29 11:52 UTC, jswk commented on app/controllers/backoffice/services_controller.rb
> +      @service = Service.new(**attr, status: :draft)
`attrs`

2022-03-29 11:52 UTC, jswk commented on app/controllers/backoffice/services_controller.rb
> +    unless @service.valid?
`if @service.invalid?`? Easier to process logically.

2022-03-29 11:52 UTC, jswk commented on app/controllers/backoffice/services_controller.rb
> +    unless Service::Update.new(@service, attr).call
Better use the version with direct `call`, instead of `new.call`

2022-03-29 11:52 UTC, jswk commented on app/controllers/backoffice/services_controller.rb
> +    unless Service::Update.new(@service, attr).call
`attrs`

2022-03-30 07:36 UTC, jswk commented on app/helpers/backoffice/services_session_helper.rb
> +  SESSION_KEY = "service"
What about this?

2022-03-30 07:55 UTC, jswk requested changes
https://github.com/cyfronet-fid/marketplace/pull/2579#discussion_r838212461
Try opening previews of two services in separate tabs, it doesn't work in this branch, while it works on master.

2022-03-30 10:10 UTC, jswk commented
Also, please update changelog, as this won't be included in 3.35 but in 3.36 after all.

2022-03-30 13:54 UTC, jswk requested changes
Great, now the preview works as expected.
Only update the changelog and it looks good from my side: https://github.com/cyfronet-fid/marketplace/pull/2579#issuecomment-1082893337.

2022-03-31 12:46 UTC, Marcelinna commented
- [ ] Add all required fields (no logo) and click the button Create resource - resource should be created
- [ ] Add all required fields (with logo) and click the button Create resource - resource should be created
- [ ] Don't add required fields and click the button Create resource - validation of form should work properly
- [ ]  Add the wrong format to  fields and click the button Create resource - validation of form should work properly
- [ ] Add all required fields (no logo) and click the button Preview - Go back to edit - Create resource - resource should be created
- [ ]  Add all required fields (with logo) and click the button Preview - Go back to edit - Create resource - resource should be created
- [ ] Add required fields (no logo) and click the button Preview - Confirm changes - resource should be created
- [ ] Add required fields (with logo) and click the button Preview - Confirm changes - resource should be created
- [ ] Add required fields (no logo) and click the button Preview - Go back to edit - delete required field and wrong format - Create resource - validation of form should work properly
- [ ] Don't add required fields and click the button Preview - validation of form should work properly
- [ ]  Add the wrong format to  fields and click the button Preview - validation of form should work properly
- [ ] Check integration with PC

2022-04-05 11:02 UTC, Marcelinna commented
> * [ ]  QA
> 
>     * [x]  DEV
> 
> 
> Other pr after tiring update Check-in in PC ![image](https://user-images.githubusercontent.com/59872096/159858411-7cdc94a2-71f3-4974-a151-f7f1db435757.png) Master ![image](https://user-images.githubusercontent.com/59872096/160418186-a53c9191-8dbc-480d-88c6-cd712c3f0553.png)
> 
> This pr after tiring update Check-in in PC - but seems that the problem with validation exist because the resource doesn't update but error message doesn't displayed ![image](https://user-images.githubusercontent.com/59872096/159858605-55d1096f-b852-4d0e-b040-a77f372fe3e0.png)

Please check in again locally because for me it isn't working. 
Master
![image](https://user-images.githubusercontent.com/59872096/161739975-b8fdf34f-3093-487b-9876-69b4dfbd8103.png)

PR locally 
![image](https://user-images.githubusercontent.com/59872096/161740015-751b4bdb-ad04-4cf9-90d6-255855d85bcd.png)

When the instance is connected with beta.provider, the red message should be visible for EGI Accounting

2022-04-05 15:34 UTC, Marcelinna approved these changes

2022-04-05 15:53 UTC, merged