Resource extended
cyfronet-fid/marketplace pull request #2582
Opened 2022-03-02 10:06 UTC by Marcelinna

2022-03-30 11:32 UTC, danielkryska commented on db/schema.rb
> +    t.index %w[record_type record_id name], name: "index_action_text_rich_texts_uniqueness", unique: true
The file had been formatted, probably by the `rbprettier` (?) or your own tool for formatting.

2022-03-30 11:32 UTC, danielkryska commented on db/schema.rb
> +    t.index %w[record_type record_id name], name: "index_action_text_rich_texts_uniqueness", unique: true
Please check out the latest master version of the document. Unless changes were intentional and provided with a new migration.

2022-03-30 11:32 UTC, danielkryska commented on test/system/README.md
> +```
Why had you provided the additional dependency into the e2e pipeline?

2022-03-30 11:32 UTC, danielkryska commented on test/system/cypress.json
> +    "openMode": 1
Why do you want refresh run on fail? I was thinking that we stopped using such an approach.

2022-03-30 11:32 UTC, danielkryska commented on test/system/cypress/integration/regression_tests/backoffice/category/category.spec.ts
> +  const alertNameValidation = "Name can't be blank";
Do you have thinking about accessing the language YAML files to receive specific messages?

2022-03-30 11:32 UTC, danielkryska commented on test/system/cypress/integration/regression_tests/backoffice/platforms/platforms.spec.ts
> +  const alertNameValidation = "Name can't be blank";
Do you have thinking about accessing the language YAML files to receive specific messages?

2022-03-30 11:32 UTC, danielkryska commented on test/system/cypress/integration/regression_tests/backoffice/resources/owned_resources.spec.ts
> +  const alertEmailValidation = "Email is not a valid email address";
Do you have thinking about accessing the language YAML files to receive specific messages?

2022-03-30 11:32 UTC, danielkryska commented on test/system/cypress/integration/regression_tests/backoffice/scientific-domain/scientific-domain.spec.ts
> +  const alertNameValidation = "Name can't be blank";
Do you have thinking about accessing the language YAML files to receive specific messages?

2022-04-04 11:39 UTC, Marcelinna commented on db/schema.rb
> +    t.index %w[record_type record_id name], name: "index_action_text_rich_texts_uniqueness", unique: true
I had a problem with formatting and I used the command you gave me

2022-04-04 11:41 UTC, Marcelinna commented on test/system/cypress.json
> +    "openMode": 1
I don't remember using it before

2022-04-05 17:46 UTC, Marcelinna commented on test/system/README.md
> +```
because in test I use  "http://localhost/get" for fields where form check URL.

2022-04-06 09:40 UTC, jswk commented on db/schema.rb
> +    t.index %w[record_type record_id name], name: "index_action_text_rich_texts_uniqueness", unique: true
Please revert the changes in this file anyway, when I run `rbprettier --write .` in the repo's root dir then it ignores this file. It should work the same for you.
Maybe you run the command in `/db`? When I do this rbprettier indeed applies the changes, somehow it doesn't check parent directories for a `.prettierignore` files...

2022-04-06 09:42 UTC, jswk commented on test/system/cypress/factories/resource.factory.ts
> +        basicWebpage_url: "https://example.com",
Won't using `example.(com|org)` domain here also lead to intermittent errors? I mean, most likely not, but have you considered it?

2022-04-06 09:48 UTC, jswk requested changes
Revert the formatting changes in `db/schema.rb` (see https://github.com/cyfronet-fid/marketplace/pull/2582#discussion_r843727164) and I feel the PR is good to go.

2022-04-06 10:00 UTC, Marcelinna commented on test/system/cypress/factories/resource.factory.ts
> +        basicWebpage_url: "https://example.com",
will not lead, because we do not check the response code in the resources form, we only check in provider form

2022-04-06 10:47 UTC, jswk approved these changes

2022-04-06 11:06 UTC, jswk approved these changes

2022-04-07 05:36 UTC, kmarszalek approved these changes

2022-04-07 06:05 UTC, merged