[#2537] Integrate user_actions with JMS
cyfronet-fid/marketplace pull request #2598
Opened 2022-03-17 14:59 UTC by wujuu

2022-03-21 10:53 UTC, Michal-Kolomanski requested changes
The [scope](https://github.com/cyfronet-fid/marketplace/issues/2537) of the ticket was also to create an env variable to control user_actions destination. This variable should support 3 values. Sending user_actions:
1)  directly to the recommender,
2)  sending to databus, 
3)  both ways at the same time.

For now, it should be set to the third option. 

Furthermore, the whole mechanism should be extensively tested.

2022-03-21 10:53 UTC, Michal-Kolomanski commented on config/stomp_publisher.yml
> +  recommender-topic: <%= ENV["MP_STOMP_PUBLISHER_RECOMMENDER_TOPIC"] || "recommender" %>
- I wonder if "recommender-topic" is the best name. I would rather use something like "user_action_topic" in that case.
- Add a description of this variable to the README

2022-03-28 12:38 UTC, jswk reviewed
~~Other than the misleading docs the PR looks ok.~~

2022-03-28 12:40 UTC, jswk requested changes
Please also add the test for the added behaviour to `spec/services/jms/publisher_spec.rb`.

2022-03-29 09:11 UTC, wujuu commented
> Please also add the test for the added behaviour to `spec/services/jms/publisher_spec.rb`.

I've added tests, but to the UserActionController, because the Jms::Publisher didn't actually change. (it was Jms::Publish helper class). Left a TODO (for another PR) to expand the tests, possibly a task for @Michal-Kolomanski

2022-03-29 09:36 UTC, jswk commented
> > Please also add the test for the added behaviour to `spec/services/jms/publisher_spec.rb`.
> 
> I've added tests, but to the UserActionController, because the Jms::Publisher didn't actually change(rather Jms::Publish helper class, which we do not test as for now - I've felt that we should test the UserActionController, because it enapsulates more of the logic added). Left a TODO (for another PR) to expand the tests, possibly a task for @Michal-Kolomanski

Right, my bad. You're right that the Jms::Publish doesn't have tests.

2022-03-29 11:54 UTC, jswk approved these changes
Seems ok now.

2022-03-29 12:00 UTC, Michal-Kolomanski approved these changes

2022-03-29 12:03 UTC, Michal-Kolomanski commented
We need to inform Wojtek about the variables we've added and what values they should have.

2022-03-29 12:11 UTC, merged