[#2621] Publish model changes to JMS databus
cyfronet-fid/marketplace pull request #2649
Opened 2022-04-22 06:47 UTC by wujuu

2022-04-22 06:57 UTC, wujuu commented on lib/recommender/serialize_db.rb
> +module RecommenderLib
Changed, to not conflict with the Recommender module namespace. Before, it caused the `Vocabulary` being treated as a `Recommender::Vocabulary` module instead of the Active Record `Vocabulary` model.

2022-04-27 08:53 UTC, Michal-Kolomanski requested changes
1) Unfortunately, it seems that there is an error in this PR.
[Stack trace](https://pastebin.com/nj40PKKB)
2) Please add annotation on which ticket this PR is closing,
3) After discussing with @m.szostak it was decided to send DB events to another topic (different from user_actions).

Testing + checking the code will be done in the next iteration.

2022-06-22 13:57 UTC, Michal-Kolomanski reviewed
It's challenging to test this feature in all scenarios, but I did what I could locally, and it worked flawlessly. Excellent work! :clap: 

However, we should have better integration tests for this feature (many services will rely on this), and that's the only thing stopping me from giving it my full approval. I'm talking about integrating with any queue, making a modification to users and services and determining whether it was propagated to that queue.

Open question
- should changes in offers be published to the databus?

Also please make a rebase. Changelog?

2022-06-23 11:13 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/175286072-dfaa1510-b73b-4281-98c9-6cc74a5349ef.png)
You don't need more information for provider changes?

2022-06-23 11:23 UTC, Marcelinna commented
For target user you take description
![image](https://user-images.githubusercontent.com/59872096/175287487-86a92d83-3a3b-4b8d-bd4f-1424f89621e5.png)
For category and scientific domain not, why?

2022-06-23 12:07 UTC, Michal-Kolomanski commented
> ![image](https://user-images.githubusercontent.com/59872096/175286072-dfaa1510-b73b-4281-98c9-6cc74a5349ef.png) You don't need more information for provider changes?

From the point of our recommender, we do not (we store only id and name).
![image](https://user-images.githubusercontent.com/47147210/175294827-fd6bfb32-f922-4ca0-9fae-304b40243a46.png)

2022-06-23 12:17 UTC, Michal-Kolomanski commented
> example for vocabularies: target user you take the description ![image](https://user-images.githubusercontent.com/59872096/175287487-86a92d83-3a3b-4b8d-bd4f-1424f89621e5.png) For category and scientific domain not, why? ![image](https://user-images.githubusercontent.com/59872096/175287736-a3badda6-3e01-4c43-8d9e-27c9bf045d43.png)

It's also based on that which properties of objects we exactly store in the recommender's database. In that case, Patrick's implementation reflects the recommender's needs. 

BUT, on the other hand, we are introducing NLP, and the issue raised by Marceline is very intriguing. The category description, scientific domain description, providers description, etc., seem to be extremely helpful and valuable in this circumstance. We definitely should store information like descriptions from now. Please address that in this PR.

2022-07-08 13:18 UTC, wujuu commented
Also added integration tests:
- ActiveMQ to docker-compose.yml
- `stomp_publisher.yml` and `stomp_subscriber.yml` test configurations

Please check it out @wziajka

2022-07-11 10:40 UTC, michal-szostak approved these changes

2022-07-11 10:52 UTC, Marcelinna approved these changes

2022-07-11 11:38 UTC, merged