[#2608] add name to specific links
cyfronet-fid/marketplace pull request #2653
Opened 2022-04-26 11:53 UTC by goreck888

Prepare for the Resource and Provider Profile 4.0

2022-04-26 14:38 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce
1. Go to /backoffice/services/new
2. Fill form, add multimedia url, use case url
![image](https://user-images.githubusercontent.com/59872096/165325299-fb93abe2-d075-4f27-85a3-14887e10dabf.png)
3. Click button "Create resource"
4. Go to Details - see error 
![image](https://user-images.githubusercontent.com/59872096/165325450-b962e830-2496-439d-8342-ef5c38bce8de.png)

2022-04-26 14:47 UTC, Marcelinna commented
![image](https://user-images.githubusercontent.com/59872096/165327310-edc6807b-eafd-448a-8259-5b63718b4144.png)
Change to "Url can't be blank"

2022-04-26 14:53 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce
1. Go to /backoffice/services/new
2. Fill form, add multimedia url, use case url
![image](https://user-images.githubusercontent.com/59872096/165325299-fb93abe2-d075-4f27-85a3-14887e10dabf.png)
3. Click button "Preview"
4. Go to Details - see error 
![image](https://user-images.githubusercontent.com/59872096/165325450-b962e830-2496-439d-8342-ef5c38bce8de.png)

2022-04-26 14:58 UTC, Marcelinna commented
Go to /backoffice/providers/new, make element Multimedia urls expanded
![image](https://user-images.githubusercontent.com/59872096/165329764-a56a9d20-7eab-4d2b-a274-9786bf4ccb22.png)

2022-05-09 07:00 UTC, Marcelinna commented
Step to reproduce 
1. Add 3 Multimedia urls and 3 use case url (don't fill all required fields)
![image](https://user-images.githubusercontent.com/59872096/167356804-d41872f0-ea98-4744-afbd-06d927d3398c.png)
2. Click button "Create resource" - see error - second urls disappear
![image](https://user-images.githubusercontent.com/59872096/167356965-cf46743f-9d87-4729-bce4-854fa19c4ba9.png)

2022-05-09 09:47 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Please add information 
Url should start with http:// or https:// prefix [e.g. https://example.com] 
![image](https://user-images.githubusercontent.com/59872096/167384906-e103ac50-cc16-46ba-bfb7-5bab9f6fc576.png)
just like here
![image](https://user-images.githubusercontent.com/59872096/167385028-2f5aac95-56d9-44ad-a7dd-6442864a6dd2.png)

2022-05-09 10:25 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV
Step to reproduce
1. Go to /backoffice/services/new
2. Fill required field, add Multimedia urls and Use cases urls 
3. ![image](https://user-images.githubusercontent.com/59872096/167391066-a16662a8-6f14-4461-9ee7-99023b171eab.png)
4. Click the button "Create resource"
![image](https://user-images.githubusercontent.com/59872096/167391234-a9753288-4a49-41b8-98ac-6d9372f18222.png)
5. Click the button "Edit resource"
6. Delete a value from Multimedia urls and Use cases urls 
![image](https://user-images.githubusercontent.com/59872096/167391411-8d90421c-a518-4f14-8487-5954ef7c5b20.png)
7. Click the button "Update resource"
8. See error - Multimedia nad Use cases are visible in Details, despite fields are empty
![image](https://user-images.githubusercontent.com/59872096/167391568-064d3875-a952-4ce3-9c51-8db98bf7e39c.png)
![image](https://user-images.githubusercontent.com/59872096/167391670-b21369fc-ef4b-4577-8297-8e02524e0072.png)

2022-05-09 11:03 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce: 

1. /backoffice/providers/new
2. Fill required fields and Multimedia urls 
![image](https://user-images.githubusercontent.com/59872096/167396900-040848d0-9c89-4f17-9331-b191a273bf83.png)
4. Click button "Create Provider"
![image](https://user-images.githubusercontent.com/59872096/167397078-2d750f1e-282a-4f77-96ce-64cb9efd9d7f.png)
6. Click the button "Edit"
7. Delete value from Multimedia urls 
![image](https://user-images.githubusercontent.com/59872096/167397140-a43cb222-ee61-4f1a-b893-dc06fb58442b.png)
8. Click the button "Update provider" - see error - no possible update provider 
![image](https://user-images.githubusercontent.com/59872096/167397269-f7d0caea-2f6e-42c9-8be8-72b032a9d662.png)

2022-05-16 06:29 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Step to reproduce
1. Create provider in beta.provider and add Multimedia URL 
2. Go to provider in Marketplace
3. See error - Multimedia Url doesn't visible
![image](https://user-images.githubusercontent.com/59872096/168532265-c03ea1be-27a6-40a0-8696-b0027703874b.png)

2022-05-17 18:50 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Steps to reproduce
1. Go to Provider Portal
2. Create Providers and add Multimedia URL, Multimedia Name
3. Go to MP - multimedia URL is visible properly
![image](https://user-images.githubusercontent.com/59872096/168887826-f3ed83f1-5223-499e-96a4-4f980de375ce.png)
4. Go to Provider Portal and delete Multimedia URL, Multimedia Name
5. See error - link is not removed from MP
![image](https://user-images.githubusercontent.com/59872096/168888355-142ebe78-cccb-48db-8e37-78aa227bd812.png)

2022-05-18 15:30 UTC, Marcelinna approved these changes

2022-05-19 07:05 UTC, kmarszalek commented on spec/factories/links/link_multimedia_urls.rb
> +    sequence(:url) { |n| "http://example#{n}.org" }
exampleN.org will be unavailable for N > 3

2022-05-19 07:05 UTC, kmarszalek commented on spec/factories/links/link_use_cases_urls.rb
> +    sequence(:url) { |n| "http://example#{n}.org" }
exampleN.org will be unavailable for N > 3

2022-05-19 07:09 UTC, kmarszalek commented on db/migrate/20220426103925_move_links_to_links_table.rb
> +  def change
is it easily reversibly or do you need up/down ?

2022-05-19 07:13 UTC, kmarszalek commented on app/views/components/presentable/details_component/_links.html.haml
>            "data-target": local_assigns[:preview] ? "preview.link" : "")
shouldn't there also be a comment like in sidebar_component _links ? about refactor?

2022-05-19 07:13 UTC, kmarszalek commented on app/views/components/presentable/details_component/_links.html.haml
> +          = link_to(link.name? ? link.name : t(".#{field}", idx: idx + 1), link.url, "data-probe": "",
comment about refactor after release as in sidebar_component/_links?

2022-05-19 07:16 UTC, kmarszalek commented on app/views/backoffice/services/_form.html.haml
> +            class: ("show" unless collapsed?(service, [:description, :tagline, :logo, :"link_multimedia_urls.url",
both fields missing at line 63

2022-05-19 07:17 UTC, kmarszalek commented on app/views/backoffice/providers/form/_marketing.html.haml
> +          :link_multimedia_urls, :"link_multimedia_urls.url"])) }
both fields missing at line 3

2022-05-19 07:19 UTC, kmarszalek commented on app/helpers/url_helper.rb
> +    response.status == 200 || 301
why 301?

2022-05-19 07:23 UTC, kmarszalek requested changes
looks fine, some minors, one question. + rebase :)

2022-05-19 12:18 UTC, goreck888 commented on app/helpers/url_helper.rb
> +    response.status == 200 || 301
Removed.

2022-05-20 09:07 UTC, merged