[#2636] Abbreviation for Resource Profile 4.0
cyfronet-fid/marketplace pull request #2667
Opened 2022-05-17 14:48 UTC by goreck888

Add abbreviation string input to the Service model
Closes #2636

2022-05-18 14:22 UTC, kmarszalek commented on app/views/backoffice/services/_form.html.haml
> +            class: ("show" unless collapsed?(service, [:name, :abbreviation, :resource_organisation,
missing :abbreviation at line 41?

2022-05-18 14:23 UTC, kmarszalek commented on app/components/presentable/header_component.rb
> +    abbreviation: nil,
why nil?

2022-05-18 14:23 UTC, kmarszalek commented on app/components/presentable/header_component.html.haml
> +      - if @abbreviation
it's mandatory..

2022-05-18 14:25 UTC, kmarszalek requested changes
get @michal-szostak to approve of the no-mandatory approach (that will be visible in the PR) or make adjustments

2022-05-18 14:30 UTC, goreck888 commented on app/components/presentable/header_component.html.haml
> +      - if @abbreviation
The same reason, even if `service.abbreviation` is mandatory, the `@abbreviation` variable could be `nil`

2022-05-18 14:41 UTC, Marcelinna commented
Abbreviation should be not mandatory in Marketplace

2022-05-20 04:20 UTC, kmarszalek approved these changes

2022-05-20 04:21 UTC, kmarszalek approved these changes
Squash :)

2022-05-20 08:05 UTC, Marcelinna approved these changes

2022-05-20 11:05 UTC, merged