[#2660] Extend platforms
cyfronet-fid/marketplace pull request #2688
Opened 2022-05-27 15:10 UTC by goreck888

Add vocabulary fields to the Platforms table
Change displaying platforms field depending
on PROFILE_4_ENABLED value
Closes #2660

2022-05-27 15:13 UTC, kmarszalek requested changes
changelog

2022-05-27 15:33 UTC, goreck888 commented on app/helpers/presentable/details_helper.rb
> +    platforms = Rails.configuration.profile_4_enabled ? "platforms" : "related_platforms"
Done

2022-05-30 08:46 UTC, kmarszalek approved these changes

2022-05-30 09:48 UTC, Marcelinna approved these changes

2022-05-30 09:49 UTC, merged