[#2716] Add project to recommender dump
cyfronet-fid/marketplace pull request #2722
Opened 2022-07-08 18:24 UTC by wujuu

As the title says. Added project_id, user_id and ids of services used in a project to the serializer.

NOTE: If a service is included more than one time in a project, (for example it has two offers with the same service), it is serialized as many times as it appears in the project - this is to provide additional data to the recommender team.

2022-07-11 10:40 UTC, michal-szostak approved these changes

2022-07-11 11:39 UTC, Michal-Kolomanski requested changes
We merged this PR https://github.com/cyfronet-fid/marketplace/pull/2649/files
Please add the module Publishable to this feature.

2022-07-20 11:44 UTC, Michal-Kolomanski requested changes
I have tested this PR and it seems to not publish any event when updating the project (for example, adding a service to the already existing project). Events to the **mp_db_events** topic are published only during the creation of the project. 

The dump which is sent to the recommender looks good to me :clap:

2022-08-18 13:24 UTC, Michal-Kolomanski approved these changes

2022-08-18 13:29 UTC, merged