[#2769] Adjust recommendations request to changes in the recommender
cyfronet-fid/marketplace pull request #2781
Opened 2022-10-18 21:35 UTC by JanKapala

Closes #2769

2022-10-19 07:49 UTC, Michal-Kolomanski requested changes
Parse recommender response - recommendations are not shown [PR]([https://marketplace-9.docker-fid.grid.cyf-kr.edu.pl/services?scientific_domains%5B%5D=1&scientific[…]ic_domains%5B%5D=39&scientific_domains%5B%5D=40](https://marketplace-9.docker-fid.grid.cyf-kr.edu.pl/services?scientific_domains%5B%5D=1&scientific_domains%5B%5D=73&scientific_domains%5B%5D=38&scientific_domains%5B%5D=75&scientific_domains%5B%5D=42&scientific_domains%5B%5D=41&scientific_domains%5B%5D=39&scientific_domains%5B%5D=40)

2022-10-25 21:16 UTC, JanKapala commented
It is parsed correctly, I've tested MP <-> Recommender communication locally. I wonder what version of Recommender the MP test instance is using here: http://pr-2781.docker-fid.grid.cyf-kr.edu.pl/ ? Last release? If so, it obviously doesn't work because compatible changes are merged to the Recommender's main but not released yet.

2022-10-26 10:31 UTC, Michal-Kolomanski approved these changes
I trust your local tests! :pray:

2022-10-26 10:36 UTC, danielkryska approved these changes

2022-10-26 10:36 UTC, merged