[HOTFIX] `catalogue_data` task
cyfronet-fid/marketplace pull request #2795
Opened 2022-10-28 11:24 UTC by goreck888

Add migration task `rake migration:catalogue_data` 
for import missing catalogue for existing services and providers 

NOTICE!
Task depends on `MP_IMPORT_EOSC_REGISTRY_URL` env variable

2022-10-28 16:13 UTC, Marcelinna approved these changes

2022-10-28 17:21 UTC, michal-szostak requested changes

2022-10-28 17:21 UTC, michal-szostak commented on lib/tasks/migration.rake
> +        url = ENV["MP_IMPORT_EOSC_REGISTRY_URL"] || "https://api.eosc-portal.eu/#{type[:method]}/"
I think this would not work for env variable - `#{type[:method]}` should be concatenated to the whole URL

```
url = (ENV["MP_IMPORT_EOSC_REGISTRY_URL"] || "https://api.eosc-portal.eu") + "/#{type[:method]}/"
```

Also - in all other places where `MP_IMPORT_EOSC_REGISTRY_URL ` is used the default is `https://beta.providers.eosc-portal.eu/api` - maybe we should be consistent here.

2022-10-28 17:21 UTC, michal-szostak commented on lib/tasks/migration.rake
> +          r = Faraday.get("#{url}/#{obj.pid}")
`/` is added after `url` but above `url` ends with `/`

2022-10-31 03:12 UTC, goreck888 commented on lib/tasks/migration.rake
> +        url = ENV["MP_IMPORT_EOSC_REGISTRY_URL"] || "https://api.eosc-portal.eu/#{type[:method]}/"
Done

2022-11-02 12:19 UTC, michal-szostak approved these changes

2022-11-02 14:07 UTC, merged