[#2856] Set AAI to the new endpoints
cyfronet-fid/marketplace pull request #2857
Opened 2023-01-02 11:42 UTC by goreck888

Change endpoints in omniauth config
for AAI
Add new ENV `OIDC_AAI_OLD_API` to use old endpoints Closes #2856

2023-01-02 13:02 UTC, agpul requested changes
![image](https://user-images.githubusercontent.com/43000481/210234938-2cdf6920-532f-404e-9755-2ed2fd8144ac.png)

2023-01-02 13:44 UTC, agpul reviewed
Works for me, but let's wait for Marcelina's review.

2023-01-03 06:10 UTC, Marcelinna approved these changes

2023-01-03 11:01 UTC, agpul approved these changes

2023-01-03 11:59 UTC, merged