[#2850] Extend bundles functionality
cyfronet-fid/marketplace pull request #2893
Opened 2023-02-08 08:13 UTC by goreck888

Add Bundle model with additional fields
Add form to create bundles
Change views to displaying data
from bundle model instead of
offers (eg. name, description, etc.)

Closes #2850

2023-02-15 08:56 UTC, Marcelinna commented
when i click "edit" button on created bundle
![image](https://user-images.githubusercontent.com/59872096/218980468-fb6b760b-24c6-4e36-8534-6c14d9239555.png)

2023-02-15 11:31 UTC, Marcelinna commented
lack of Technical parameter
![image](https://user-images.githubusercontent.com/59872096/219015793-02272a5b-ef43-4f3c-b79f-3ff7845727da.png)

2023-02-15 11:40 UTC, Marcelinna commented
when I don't fill all data and click on button "Create bundle"
![image](https://user-images.githubusercontent.com/59872096/219017664-8c8341de-5edc-49e8-8ca1-e2b064850b45.png)

2023-02-15 11:45 UTC, Marcelinna commented
make filed mandator according with https://docs.google.com/spreadsheets/d/15pBonVmG0Vvz6uTq_ioJz0cpj3g5J3O0XeE6cnbqZQg/edit#gid=1974691285

2023-02-27 07:30 UTC, Marcelinna commented
@agpul @eldenkat 
Please add a message which fields in bundle are multi-select values ​​and their dictionary values

2023-03-02 11:33 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV
I created bundle from 3 offers
![image](https://user-images.githubusercontent.com/59872096/222417065-0b428398-814b-4355-8c78-dcad1a297e35.png)

When I am in order details I see only 2 offers
![image](https://user-images.githubusercontent.com/59872096/222417206-150598d8-4eac-4b8b-bd49-c9edcb8fa0fe.png)

2023-03-02 11:55 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

When I order bundle, its name should be visible in order step
![image](https://user-images.githubusercontent.com/59872096/222421277-72af8ee0-54ee-411a-8d5f-79c758486cbf.png)
![image](https://user-images.githubusercontent.com/59872096/222421615-630c7ae4-3a59-4dc8-a42e-875c8c8841e6.png)

same as we have for other offers
![image](https://user-images.githubusercontent.com/59872096/222421754-b2d17eba-2f42-4bda-be9e-717ee2e426e3.png)

2023-03-03 08:58 UTC, agpul requested changes
![image](https://user-images.githubusercontent.com/43000481/222676739-a8752e67-f581-49cd-aafc-8cff5377f4d3.png)
 I can't fill this fields (no list) and it cause that I can't create the bundle

2023-03-06 10:48 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

In bundle offer can't set order type -> order required internal

Simple offer
![image](https://user-images.githubusercontent.com/59872096/223089117-8d230b36-fcfe-4cbf-a89c-1423daf309bb.png)

Bundle offer
![image](https://user-images.githubusercontent.com/59872096/223089275-2a7cff3c-8331-44dd-b5b4-4c297dd93efd.png)

2023-03-06 10:52 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

When I create bundle for service and I want to click button "Access service"

![image](https://user-images.githubusercontent.com/59872096/223090385-cc1e6cb1-5c06-41aa-a4ec-442df38205da.png)

2023-03-06 11:03 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV
![image](https://user-images.githubusercontent.com/59872096/223092788-05cc317f-f3d2-423a-8c7b-642c3a4cc665.png)
Change to You can add a dedicated bundle for
your **service**

2023-03-06 11:09 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV
Add notification near Main offer [Main offer must be a offer which uses EOSC Portal as the order management platform]
![image](https://user-images.githubusercontent.com/59872096/223093611-686f224b-6610-4d7f-a5a5-0036cf55557e.png)

2023-03-06 11:46 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

1. I create 2 additional offers for Service Aiidalab (service has 3 offer)
![image](https://user-images.githubusercontent.com/59872096/223100556-e3bd323b-a5cf-4828-8e14-6d8826b6e46a.png)
2. Click "Add new bundle"
3. I can't find 2 other offers for the Service Aiidalab
![image](https://user-images.githubusercontent.com/59872096/223101552-dbfed3f6-cb9b-4e90-ad1b-a6a05cdd4def.png)

2023-03-15 09:36 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV
Beta
![image](https://user-images.githubusercontent.com/59872096/225268453-ae2d5520-3016-4d52-b6a2-5c9a00fc53cf.png)
PR when I have open access type I see checkbox "Use EOSC Portal as the order management platform" 
![image](https://user-images.githubusercontent.com/59872096/225268527-08b0205d-71e5-412a-82cc-e6a643f0bde4.png)

2023-03-15 09:41 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

offer created for bundle looks weird, should look like a normal offer
![image](https://user-images.githubusercontent.com/59872096/225269848-f5c02539-b1b1-4692-ae0b-703aa3dc97a5.png)

2023-03-21 06:53 UTC, Marcelinna commented on app/views/layouts/common_parts/services/_new_bundle.html.haml
> +            = _("Add new bundle")
please change to "data-e2e": "add-new-bundle-offer-btn"

2023-03-21 07:13 UTC, Marcelinna commented
- [ ] QA
- [ ] DEV

Bundle for EGI Nootebook is removed
When I click Access to service on EGI Nottebook page
![image](https://user-images.githubusercontent.com/59872096/226539247-2d1392b3-fe72-4788-9859-32838023d549.png)

2023-03-29 05:48 UTC, Marcelinna approved these changes

2023-03-29 08:48 UTC, agpul approved these changes

2023-03-29 09:34 UTC, merged