feat:[] Create task to create SOLR dumps
cyfronet-fid/marketplace pull request #2988
Opened 2023-05-20 12:58 UTC by goreck888

Add task rake ess:dump["#{collection}"] to get collections in json dump. Possible options:
- all
- providers
- services
- offers
- bundles and arrays like `ess:dump["services datasources"]

@wziajka description of connecting to the transformation API described in docs. The variables should be set on the worker container.

2023-05-22 17:20 UTC, Michal-Kolomanski commented on README.md
> +- all
data sources as well?

2023-05-22 17:31 UTC, Michal-Kolomanski approved these changes
LGTM

2023-05-22 17:49 UTC, goreck888 commented on README.md
> +- all
yes, forgot about it

2023-05-23 13:57 UTC, michal-szostak requested changes

2023-05-24 07:10 UTC, michal-szostak approved these changes

2023-05-24 10:26 UTC, merged