[#2970] Capabilities of goals suggestion in bundle form
cyfronet-fid/marketplace pull request #3044
Opened 2023-08-03 17:19 UTC by goreck888

Add a field to get capabilities of bundle goals suggestions
The field is visible when someone chooses "Not specified"
Closes #2970

2023-08-04 06:26 UTC, agpul requested changes
- [ ] I see that in the backoffice we have a short list of capabilities but in the issue it is long.
- [ ] I see field "Not specified" instead of "Other"

2023-08-28 10:05 UTC, Marcelinna commented
1. Save suggestion
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/e320b0ab-abdf-4b1d-b97c-663292ae4189)
2. Click "EDIT" on bundle
3. See problem - the suggestion is not visible anymore 

In Feature section I don't see entered suggestion
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/f42f96c8-584c-48e0-89d0-76fb5caca235)

2023-08-29 11:17 UTC, Marcelinna approved these changes

2023-08-29 13:56 UTC, michal-szostak approved these changes

2023-08-30 09:05 UTC, agpul approved these changes

2023-08-30 13:12 UTC, merged

2023-10-09 07:58 UTC, Marcelinna commented
rake rdt:add_internal_vocabularies