fix: alter a field for new project form
cyfronet-fid/marketplace pull request #3245
Opened 2024-03-11 16:22 UTC by maria-j-k

closes #3244

2024-03-12 12:27 UTC, goreck888 approved these changes
Everything is ok, just add a changelog entry as in following template:

## [3.56.0-milestone]

### Changed
- New project form fields validations (@maria-j-k)

2024-03-13 11:12 UTC, Marcelinna approved these changes

2024-03-13 11:15 UTC, Marcelinna requested changes
Please change here too text, and when the reason is empty, the section should not be visible in the details page
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/02853490-fa00-4f4e-806d-01bb56f46c25)

2024-03-13 13:41 UTC, goreck888 approved these changes

2024-03-14 14:56 UTC, merged