style: new design for bundles
cyfronet-fid/marketplace pull request #3294
Opened 2024-05-28 08:51 UTC by goreck888

2024-05-28 11:41 UTC, Marcelinna requested changes
- [ ] QA
- [x] DEV

![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/7b901b19-94ac-4d16-a521-a008e6eae714)

2024-05-31 08:06 UTC, Marcelinna commented
![image](https://github.com/cyfronet-fid/marketplace/assets/59872096/691f27db-b57a-4172-8dab-9f3e6132f316)

2024-05-31 11:31 UTC, Marcelinna approved these changes

2024-06-03 06:47 UTC, maria-j-k approved these changes

2024-06-03 08:59 UTC, merged