save as draft
cyfronet-fid/marketplace pull request #3357
Opened 2024-11-07 08:15 UTC by maria-j-k

2024-11-14 13:59 UTC, maria-j-k commented on app/controllers/backoffice/services/offers_controller.rb
> +      nil
added by rubocop...

2024-11-14 14:01 UTC, maria-j-k commented on app/controllers/backoffice/services/offers_controller.rb
> +    temp = transform_attributes(permitted_attributes(Offer), @service)
it was made to be consistant with the existing offer_template function

2024-11-14 14:01 UTC, maria-j-k commented on app/inputs/custom_input.rb
> +class CustomInput < SimpleForm::Inputs::StringInput
I've found it as a way to use in simple form based on model a custom field not related to the model

2024-11-14 14:06 UTC, maria-j-k commented on app/models/offer.rb
> +  before_validation :set_iid
We need this line for "regular" offer creation

2024-11-14 14:07 UTC, maria-j-k commented on app/models/offer.rb
> +  validate :proper_oms?, if: -> { primary_oms.present? && !draft? }
this validate=false in create didn't work recursivelly in 100%

2024-11-15 12:59 UTC, agpul commented
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/81053435-47f1-46f5-8eb1-dc39c736d206">
I think that this box should be just above the exit button (now I can't see on my laptop). I had to change the size of the page to see the box.

2024-11-15 13:01 UTC, agpul commented
Minor: 
1. I  entered to the offer (it had the name "Agnieszka")
2. I didn't change anything
3. I had to Save changes although I didn't change anything

2024-11-15 13:04 UTC, agpul commented
Issue, to consider: @AlicjaSwierad 
1. I entered the offer that was Publish only to see it!!
2. I didn't change anything
3. I click "Save as draft"
4. Then I entered the offer one more time because I wanted to Publish it and I could find the Publish button (it was in the end of the form, this is NOT intuitve

2024-11-15 14:09 UTC, maria-j-k commented on app/models/offer.rb
> +  before_validation :set_iid
it was used as validator
The only change is to make it a hook before validation - for consistency

2024-12-03 13:08 UTC, goreck888 requested changes
There are a few things you can improve to make this code more maintainable.

2024-12-04 13:28 UTC, AlicjaSwierad commented
1. The offer drafting basic functionality is working correctly; however, there are some styling issues, particularly with the colors. 

2. I drafted the offer, which was published. When I tried to publish it again, it wasn't possible because some fields that are mandatory were empty (I hadn't changed anything)

3. There is a **major issue related to identifying the required fields within the offer**, which (I guess) is expected to be fixed in a separate PR. 

4. Is it possible to display the popup only when changes have been made? in existing offer?

2024-12-05 10:26 UTC, goreck888 approved these changes
Just add a changelog entry :)

2024-12-05 13:13 UTC, AlicjaSwierad commented
Please apply styles from the file: https://www.figma.com/file/0F53l8h6P2Q7TpzLuFZ7qX/Offers%3A-Adding-and-Editing?type=design&node-id=557%3A13882&mode=design&t=dtSZerrGZ7tgwB8i-1

- [ ] Add an overlay with #000000 at 40% opacity

- [ ] Style the popup according to the design

- [ ] Fix the issue with the popup location, right now, it appears in the bottom right corner

@jarekzet

2024-12-10 11:42 UTC, jarekzet commented
added mods in exit modal display (positioning and styling):

![image](https://github.com/user-attachments/assets/fd23dc84-d985-4f17-a1bd-20ae505b0db1)

2024-12-10 13:14 UTC, AlicjaSwierad approved these changes

2024-12-11 08:19 UTC, merged